### ISSUE TITLE
Sending a deletion/tombstone message to a topic raises an error

### ISSUE THREAD

**Issue by seifertm** [robinhood/faust#143]
I am trying to send a deletion message (i.e. same key as a previous message, but `value=None`) to a Faust topic, but it fails. Am I using the API incorrectly or is this an issue with the default serializer?

## Checklist

- [x] I have included information about relevant versions
- [ ] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

Send a message with `value=None` to a topic.
```
import faust

app = faust.App('test', broker='kafka://localhost:9094', store='memory://')

class Item(faust.Record):
    id: str
    val: str

item_topic = app.topic('items', value_type=Item)
items = app.Table('items')

@app.agent(item_topic)
async def build_item_index(stream: faust.Stream):
    async for item in stream:
        if item:
            print(f'Adding {item.id} to index')
            items[item.id] = item
        else:
            print(f'Removing {item.id} from index')
            del items[item.id]

@app.task
async def on_started():
    await item_topic.send(key='1234', value=Item(1, 'a'))
    await item_topic.send(key='1234', value=None) # Causing the error
```

## Expected behavior
Agents that process `item_topic` receive an event that is `None`

## Actual behavior
Agents never receive the deletion event.

## Full traceback

```pytb
[2018-08-21 08:45:09,790: INFO]: [^Worker]: Ready
[2018-08-21 08:45:09,921: WARNING]: Adding 1 to index
[2018-08-21 08:45:09,994: ERROR]: [^---Agent*: api.test.build_item_index]: Crashed reason=ValueDecodeError('type object argument after ** must be a mapping, not NoneType',)
Traceback (most recent call last):
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/faust/serializers/registry.py", line 99, in loads_value
    return cast(V, self._prepare_payload(typ, payload))
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/faust/serializers/registry.py", line 122, in _prepare_payload
    return model.from_data(value, preferred_type=model)
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/faust/models/record.py", line 280, in from_data
    return (self_cls or cls)(**data, __strict__=False)
TypeError: type object argument after ** must be a mapping, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/faust/agents/agent.py", line 527, in _execute_task
    await coro
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/api/test.py", line 14, in build_item_index
    async for item in stream:
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/faust/streams.py", line 747, in __aiter__
    channel_value = await chan_slow_get()
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/faust/channels.py", line 301, in __anext__
    return await self.queue.get()
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/mode/utils/queues.py", line 125, in get
    return await super().get()
  File "/usr/lib64/python3.6/asyncio/queues.py", line 167, in get
    yield from getter
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/faust/transport/conductor.py", line 80, in on_message
    event = await chan.decode(message, propagate=True)
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/faust/topics.py", line 161, in decode
    value_type, message.value, serializer=value_serializer)
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/faust/serializers/registry.py", line 104, in loads_value
    sys.exc_info()[2]) from exc
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/faust/serializers/registry.py", line 99, in loads_value
    return cast(V, self._prepare_payload(typ, payload))
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/faust/serializers/registry.py", line 122, in _prepare_payload
    return model.from_data(value, preferred_type=model)
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/faust/models/record.py", line 280, in from_data
    return (self_cls or cls)(**data, __strict__=False)
faust.exceptions.ValueDecodeError: type object argument after ** must be a mapping, not NoneType
[2018-08-21 08:45:09,997: ERROR]: [^---Agent*: api.test.build_item_index]: Crashed reason=ValueDecodeError('type object argument after ** must be a mapping, not NoneType',)
Traceback (most recent call last):
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/faust/serializers/registry.py", line 99, in loads_value
    return cast(V, self._prepare_payload(typ, payload))
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/faust/serializers/registry.py", line 122, in _prepare_payload
    return model.from_data(value, preferred_type=model)
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/faust/models/record.py", line 280, in from_data
    return (self_cls or cls)(**data, __strict__=False)
TypeError: type object argument after ** must be a mapping, not NoneType

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/mode/services.py", line 688, in _execute_task
    await task
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/faust/agents/agent.py", line 527, in _execute_task
    await coro
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/api/test.py", line 14, in build_item_index
    async for item in stream:
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/faust/streams.py", line 747, in __aiter__
    channel_value = await chan_slow_get()
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/faust/channels.py", line 301, in __anext__
    return await self.queue.get()
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/mode/utils/queues.py", line 125, in get
    return await super().get()
  File "/usr/lib64/python3.6/asyncio/queues.py", line 167, in get
    yield from getter
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/faust/transport/conductor.py", line 80, in on_message
    event = await chan.decode(message, propagate=True)
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/faust/topics.py", line 161, in decode
    value_type, message.value, serializer=value_serializer)
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/faust/serializers/registry.py", line 104, in loads_value
    sys.exc_info()[2]) from exc
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/faust/serializers/registry.py", line 99, in loads_value
    return cast(V, self._prepare_payload(typ, payload))
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/faust/serializers/registry.py", line 122, in _prepare_payload
    return model.from_data(value, preferred_type=model)
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/faust/models/record.py", line 280, in from_data
    return (self_cls or cls)(**data, __strict__=False)
faust.exceptions.ValueDecodeError: type object argument after ** must be a mapping, not NoneType
```

# Versions

* Python version: 3.6.5
* Faust version: 1.0.30
* Operating system: Linux
* Kafka version: 1.0.1
* RocksDB version (if applicable)

**Comment by jacobBaumbach** [comment]
You are passing `val` something of `NoneType`, but you declared `val` to be of type `str`

**Comment by seifertm** [comment]
Fair point. But consider the following example:
I have a Kafka topic that stores user information. Every time a user account is created, a message is sent to the topic and the message key is set to the user ID. If users delete their account, I want to insert a Kafka tombstone message. Doing so allows me to leverage log compaction to drop the sensitive user data of the deleted account.

I assumed that Faust supports inserting tombstones by sending a message with `value=None`, because this is how kafka-python and aiokafka do it. Since my approach causes an error and no other way is mentioned in the docs, I opened this issue.

**Comment by mxcoder** [comment]
Hi @seifertm , I'd like to try to use this in a very similar way. Have you find any workaround? (after 2y)

**Comment by seifertm** [comment]
@mxcoder I did. The idea was to use a special Kafka message that marks deleted messages. I had to implement a custom codec for each message format, though. Here is some snippet:
```
class MyCodec(faust.Codec):
    tombstone: bytes = b'deleted'

    def _loads(self, binary: bytes) -> Any:
        if binary == self.tombstone:
            # We cannot return None here, because it would not be passed to the stream
            # See https://github.com/robinhood/faust/issues/143
            return False
          …

    def _dumps(self, my_object: Any) -> bytes:
        if my_object is None:
            # Faust cannot deal with None values. We need a placeholder for deleted messages.
            # See https://github.com/robinhood/faust/issues/143
            return self.tombstone
          …
```

**Comment by mxcoder** [comment]
Thank you!
