### ISSUE TITLE
Send to agent example from user guide not working

### ISSUE THREAD

**Issue by dynamicmindset** [robinhood/faust#155]
## Steps to reproduce

Tell us what you did to cause something to happen.
Just started with faust.
Tried running some examples and was able to send data using the agent CLI.
Also wanted to send data from a python module, so I took example from https://faust.readthedocs.io/en/stable/userguide/agents.html#id1
"Here’s a complete example of an app, having an agent that adds numbers:"
...
Started worker for "agent.py"
```faust -A test_faust.add.agent worker -l info```
```
...
┌Topic Partition Set────────────────┬────────────┐
│ topic                             │ partitions │
├───────────────────────────────────┼────────────┤
│ agent-example-__assignor-__leader │ {0}        │
│ adding                            │ {0}        │
└───────────────────────────────────┴────────────┘ for group agent-example
[2018-08-30 15:34:12,552: INFO]: [^--Fetcher]: Stopping...
[2018-08-30 15:34:12,552: INFO]: [^--Fetcher]: -Stopped!
[2018-08-30 15:34:12,552: INFO]: [^--TableManager]: Triggered recovery in background
[2018-08-30 15:34:12,553: INFO]: [^--TableManager]: New assignments found
[2018-08-30 15:34:12,553: INFO]: [^--TableManager]: Restoring state from changelog topics...
[2018-08-30 15:34:12,553: INFO]: [^--Fetcher]: Starting...
[2018-08-30 15:34:12,554: INFO]: [^--TableManager]: Done reading all changelogs
[2018-08-30 15:34:12,554: INFO]: [^--TableManager]: Done reading from changelog topics
[2018-08-30 15:34:12,554: INFO]: [^--Fetcher]: Stopping...
[2018-08-30 15:34:12,554: INFO]: [^--Fetcher]: -Stopped!
[2018-08-30 15:34:12,555: INFO]: [^--TableManager]: Stopped restoring
[2018-08-30 15:34:12,555: INFO]: [^--TableManager]: Restore complete!
[2018-08-30 15:34:12,559: INFO]: [^--TableManager]: Attempting to start standbys
[2018-08-30 15:34:12,560: INFO]: [^--TableManager]: New assignments handled
[2018-08-30 15:34:12,560: INFO]: [^--Fetcher]: Starting...
[2018-08-30 15:34:12,561: INFO]: [^--TableManager]: Worker ready
[2018-08-30 15:34:12,575: INFO]: [^Worker]: Ready
```
Run "send_to_agent.py"

## Expected behavior
Data is sent to topic.

## Actual behavior
Exception message.
## Full traceback

```pytb
File send_to_agent.py", line 10, in <module>
    loop.run_until_complete(send_value())
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "/stuff/repo/data-matcher/test_faust/add/send_to_agent.py", line 6, in send_value
    print(await adding.ask(Add(a=4, b=4)))
  File "/stuff/repo/data-matcher/.tox/py37/lib/python3.7/site-packages/faust/agents/agent.py", line 598, in ask
    reply_to=reply_to or self.app.conf.reply_to,
  File "/stuff/repo/data-matcher/.tox/py37/lib/python3.7/site-packages/faust/app/base.py", line 1024, in conf
    'App configuration accessed before app.finalize()')
faust.exceptions.ImproperlyConfigured: App configuration accessed before app.finalize()
```
Do you think it's something related to my environment or the example?
Thanks.

# Versions

* Python version
3.7
* Faust version
 1.0.30
* Operating system
Ubuntu 18.04
* Kafka version
2.0.0

**Comment by dynamicmindset** [comment]
Tried addind the @app.command decorator and got another exception:

```pytb
faust -A agent send_value
Traceback (most recent call last):
  File "/stuff/repo/data-matcher/.tox/py37/bin/faust", line 11, in <module>
    sys.exit(cli())
  File "/stuff/repo/data-matcher/.tox/py37/lib/python3.7/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/stuff/repo/data-matcher/.tox/py37/lib/python3.7/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/stuff/repo/data-matcher/.tox/py37/lib/python3.7/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/stuff/repo/data-matcher/.tox/py37/lib/python3.7/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/stuff/repo/data-matcher/.tox/py37/lib/python3.7/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/stuff/repo/data-matcher/.tox/py37/lib/python3.7/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/stuff/repo/data-matcher/.tox/py37/lib/python3.7/site-packages/faust/cli/base.py", line 361, in _inner
    return cmd()
  File "/stuff/repo/data-matcher/.tox/py37/lib/python3.7/site-packages/faust/cli/base.py", line 419, in __call__
    return loop.run_until_complete(self.run(*args, **kwargs))
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "/stuff/repo/data-matcher/agent.py", line 29, in send_value
    print(await adding.ask(Add(a=4, b=4)))
  File "/stuff/repo/data-matcher/.tox/py37/lib/python3.7/site-packages/faust/agents/agent.py", line 603, in ask
    await app._reply_consumer.add(p.correlation_id, p)
  File "/stuff/repo/data-matcher/.tox/py37/lib/python3.7/site-packages/faust/agents/replies.py", line 131, in add
    await self._start_fetcher(reply_topic)
  File "/stuff/repo/data-matcher/.tox/py37/lib/python3.7/site-packages/faust/agents/replies.py", line 140, in _start_fetcher
    await topic.maybe_declare()
  File "/stuff/repo/data-matcher/.tox/py37/lib/python3.7/site-packages/mode/utils/futures.py", line 36, in __call__
    result = await self.fun(*self.args, **self.kwargs)
  File "/stuff/repo/data-matcher/.tox/py37/lib/python3.7/site-packages/faust/topics.py", line 334, in maybe_declare
    await self.declare()
  File "/stuff/repo/data-matcher/.tox/py37/lib/python3.7/site-packages/faust/topics.py", line 352, in declare
    retention=self.retention,
  File "/stuff/repo/data-matcher/.tox/py37/lib/python3.7/site-packages/faust/transport/drivers/aiokafka.py", line 650, in create_topic
    ensure_created=ensure_created,
  File "/stuff/repo/data-matcher/.tox/py37/lib/python3.7/site-packages/faust/transport/drivers/aiokafka.py", line 741, in _create_topic
    await wrap()
  File "/stuff/repo/data-matcher/.tox/py37/lib/python3.7/site-packages/mode/utils/futures.py", line 36, in __call__
    result = await self.fun(*self.args, **self.kwargs)
  File "/stuff/repo/data-matcher/.tox/py37/lib/python3.7/site-packages/faust/transport/drivers/aiokafka.py", line 828, in _really_create_topic
    f'Cannot create topic: {topic} ({code}): {reason}')
rhkafka.errors.InvalidReplicationFactorError: [Error 38] InvalidReplicationFactorError: Cannot create topic: f-reply-4cda86bf-5193-4e52-83bb-b9c7980cdd97 (38): Replication factor must be larger than 0.
Task was destroyed but it is pending!
task: <Task pending coro=<AIOKafkaProducer._sender_routine() running at /stuff/repo/data-matcher/.tox/py37/lib/python3.7/site-packages/aiokafka/producer/producer.py:374> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f15ba2dc498>()]>>
```

**Comment by ask** [comment]
I removed the need for calling `app.finalize()` in master, but the replication_factor error here is important.

What's the value of `app.conf.topic_replication_factor` ?

**Comment by ub3132003** [comment]
yes ,I run the same case and i got Error on frist setp.   i just do not know why.

## faust -A .agent worker -l info
ƒaµS† v1.2.2─────────────────────────────────────────────────────────────────┐
│ id        │ agent-example                                                   │
│ transport │ kafka://192.168.1.201:9092                                      │
│ store     │ memory:                                                         │
│ web       │ http://desktop-b8i6sdg:6066                                     │
│ log       │ -stderr- (info)                                                 │
│ pid       │ 28132                                                           │
│ hostname  │ DESKTOP-B8I6SDG                                                 │
│ platform  │ CPython 3.6.2 (Windows AMD64)                                   │
│ drivers   │ aiokafka=0.4.18 aiohttp=3.4.4                                   │
│ datadir   │ C:\Users\user\OneDrive\myGit\mod\examples\agent-example-data    │
│ appdir    │ C:\Users\user\OneDrive\myGit\mod\examples\agent-example-data\v1 │
└───────────┴─────────────────────────────────────────────────────────────────┘
starting^[2018-11-15 15:08:58,603: ERROR]: [^Worker]: Error: NotImplementedError()
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\mode\worker.py", line 191, in execute_from_commandline
    self.loop.run_until_complete(self.start())
  File "c:\program files\python36\lib\asyncio\base_events.py", line 467, in run_until_complete
    return future.result()
  File "c:\program files\python36\lib\site-packages\mode\worker.py", line 243, in start
    await super().start()
  File "c:\program files\python36\lib\site-packages\mode\services.py", line 669, in start
    await self._default_start()
  File "c:\program files\python36\lib\site-packages\mode\services.py", line 674, in _default_start
    await self._actually_start()
  File "c:\program files\python36\lib\site-packages\mode\services.py", line 680, in _actually_start
    await self.on_first_start()
  File "c:\program files\python36\lib\site-packages\faust\worker.py", line 243, in on_first_start
    await self.default_on_first_start()
  File "c:\program files\python36\lib\site-packages\mode\worker.py", line 127, in default_on_first_start
    self.install_signal_handlers()
  File "c:\program files\python36\lib\site-packages\mode\worker.py", line 167, in install_signal_handlers
    self.loop.add_signal_handler(signal.SIGINT, self._on_sigint)
  File "c:\program files\python36\lib\asyncio\events.py", line 481, in add_signal_handler
    raise NotImplementedError
NotImplementedError
[2018-11-15 15:08:58,603: INFO]: [^Worker]: Stopping...
[2018-11-15 15:08:58,603: INFO]: [^-App]: Stopping...
[2018-11-15 15:08:58,603: INFO]: [^-App]: -Stopped!
[2018-11-15 15:08:58,603: INFO]: [^Worker]: -Stopped!
[2018-11-15 15:08:58,603: INFO]: [^Worker]: Gathering service tasks...
[2018-11-15 15:08:58,603: INFO]: [^Worker]: Gathering all futures...
[2018-11-15 15:08:59,712: INFO]: [^Worker]: Closing event loop

**Comment by stevespark** [comment]
I looked in into this as ask is not working at all for me. 

The replication 0 issue can be easily be be fixed with:

https://github.com/robinhood/faust/compare/master...stevespark:reply_topic_replication_error

It's possible to circumvent this issue by creating the reply topic manually and setting topic_replication_factor=1 and using reply_to when doing the ask. However ask seems broken anyway. 

I can see the correct reply in the reply topic but it never reaches asking process and await ask never returns. 

Anyone got any ideas how to solve this?

**Comment by ask** [comment]
This error is because you're running on Windows:
```
File "c:\program files\python36\lib\site-packages\mode\worker.py", line 167, in install_signal_handlers
selef.loop.add_signal_handler(signal.SIGINT, self._on_sigint)
```

I fixed this in mode master just now.

The RPC example should be working now, if you try examples/advanced/rpc.py
