### ISSUE TITLE
Multiple brokers unsupported

### ISSUE THREAD

**Issue by mwolting** [robinhood/faust#156]
When starting a Faust worker with a broker configuration shaped like "kafka://broker1:9092;broker2:9092" (which should be supported according to [the docs](https://faust.readthedocs.io/en/stable/userguide/settings.html#broker)), a fatal error is raised:

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/code/src/mypackage/__main__.py", line 15, in <module>
    app.main()
  File "/usr/local/lib/python3.6/site-packages/faust/app/base.py", line 400, in main
    self.finalize()
  File "/usr/local/lib/python3.6/site-packages/faust/app/base.py", line 337, in finalize
    id = self.conf.id
  File "/usr/local/lib/python3.6/site-packages/faust/app/base.py", line 1026, in conf
    self._configure()
  File "/usr/local/lib/python3.6/site-packages/faust/app/base.py", line 964, in _configure
    conf = self._load_settings(silent=silent)
  File "/usr/local/lib/python3.6/site-packages/faust/app/base.py", line 976, in _load_settings
    return Settings(appid, **self._prepare_compat_settings(conf))
  File "/usr/local/lib/python3.6/site-packages/faust/types/settings.py", line 319, in __init__
    self.broker = url or broker or BROKER_URL
  File "/usr/local/lib/python3.6/site-packages/faust/types/settings.py", line 458, in broker
    self._broker = URL(broker)
  File "/usr/local/lib/python3.6/site-packages/yarl/__init__.py", line 170, in __new__
    val.port,
  File "/usr/local/lib/python3.6/urllib/parse.py", line 169, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: '9092;broker2:9092'
```

Culprit appears to be the `Settings` type, [the broker property](https://github.com/robinhood/faust/blob/6f6d881f5e8a8ad243d62715ac637f1867ce56dc/faust/types/settings.py#L458) of which attempts to convert the provided field to a single URI even if it consists of multiple brokers.

**Comment by samdeleu** [comment]
The problem is within the yarl module. It does not parse multiple urls, just one

**Comment by Magical-Chicken** [comment]
I would also like to see support for multiple brokers implemented. If that's a longer term goal, it would be nice to update the settings documentation to inform users that multiple brokers are not yet supported.

**Comment by fisuk** [comment]
At least the documentation ought to be fixed.

**Comment by dude0001** [comment]
The documentation [here](https://faust.readthedocs.io/en/latest/userguide/settings.html#broker) says the 
type broker parameter is type `Union[str, URL, List[URL]]`. So it can take a string, a URL or a list of URLs. This works for me.

```
import faust
from typing import Optional
from yarl import URL

_faust_app: Optional[faust.App] = None

def set_faust_app_for_worker() -> Optional[faust.App]:
    global _faust_app

    _faust_app = faust.App(
        "worker",
        autodiscover=True,
        broker=[
            URL("kafka://broker1:9096"),
            URL("kafka://broker2:9096"),
            URL("kafka://broker3:9096"),
        ]
        origin="app.worker",
        store="memory://"
    )
```
