### ISSUE TITLE
crash with kafka message version 0.9.0

### ISSUE THREAD

**Issue by predmond** [robinhood/faust#159]
## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

producing kafka with version 0.9.0 messages causes faust to crash due to missing timestamp (added in kafka 0.10.0)

e.g., `log.message.format.version=0.9.0` in kafka/config/server.properties

## Expected behavior

Either document required kafka version or handle missing timestamp

## Actual behavior

crash due to division of NoneType

## Full traceback

```pytb
[2018-09-10 17:36:33,439: CRITICAL]: [^Worker]: We experienced a crash! Reraising original exception...
starting^Traceback (most recent call last):
  File "test.py", line 21, in <module>
    app.main()
  File "/usr/local/lib/python3.6/site-packages/faust/app/base.py", line 404, in main
    cli(app=self)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/faust/cli/base.py", line 361, in _inner
    return cmd()
  File "/usr/local/lib/python3.6/site-packages/faust/cli/worker.py", line 81, in __call__
    **{**self.kwargs, **kwargs})
  File "/usr/local/lib/python3.6/site-packages/faust/cli/worker.py", line 98, in start_worker
    return worker.execute_from_commandline()
  File "/usr/local/lib/python3.6/site-packages/mode/worker.py", line 193, in execute_from_commandline
    self.stop_and_shutdown()
  File "/usr/local/lib/python3.6/site-packages/mode/worker.py", line 198, in stop_and_shutdown
    self._shutdown_loop()
  File "/usr/local/lib/python3.6/site-packages/mode/worker.py", line 226, in _shutdown_loop
    raise self._crash_reason from self._crash_reason
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 688, in _execute_task
    await task
  File "/usr/local/lib/python3.6/site-packages/faust/transport/consumer.py", line 138, in _fetcher
    await self._drainer
  File "/usr/local/lib/python3.6/site-packages/faust/transport/consumer.py", line 497, in _drain_messages
    async for tp, message in ait:
  File "/usr/local/lib/python3.6/site-packages/faust/transport/drivers/aiokafka.py", line 445, in getmany
    record.timestamp / 1000.0,
TypeError: unsupported operand type(s) for /: 'NoneType' and 'float'
```

# Versions

* Python version
3.6
* Faust version
master
* Operating system
docker python3.6
* Kafka version

* RocksDB version (if applicable)

**Comment by amitripshtos** [comment]
Faust does support kafka 0.10+ only (I added a PR that adds this kind of data into FAQ)
