### ISSUE TITLE
Agent backed by an in-memory channel crashes when sending message

### ISSUE THREAD

**Issue by seifertm** [robinhood/faust#163]
## Checklist
- [x] I have included information about relevant versions
- [ ] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce
Put the following code into the module `test.py` and run it with `faust -A test worker -l info`

```
import faust

app = faust.App('test', broker='kafka://localhost:9094', store='memory://')

channel = app.channel(value_type=str)

@app.agent(channel)
async def my_agent(stream: faust.Stream):
    async for message in stream:
        print(message)

@app.task
async def send_to_channel():
    await my_agent.cast('Message')
```

## Expected behavior
Agent should print the received message

## Actual behavior
Agent crashes

## Full traceback
```pytb
[2018-09-13 09:25:31,422: INFO]: [^Worker]: Ready
[2018-09-13 09:25:31,425: ERROR]: [^---Agent*: test.my_agent]: Crashed reason=AttributeError("'PendingMessage' object has no attribute 'stream_meta'",)
Traceback (most recent call last):
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/faust/agents/agent.py", line 527, in _execute_task
    await coro
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/test.py", line 9, in my_agent
    async for message in stream:
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/faust/streams.py", line 776, in __aiter__
    on_stream_event_in(tp, offset, self, event)
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/faust/sensors/base.py", line 111, in on_stream_event_in
    sensor.on_stream_event_in(tp, offset, stream, event)
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/faust/sensors/monitor.py", line 304, in on_stream_event_in
    'time_total': None,
AttributeError: 'PendingMessage' object has no attribute 'stream_meta'
[2018-09-13 09:25:31,427: ERROR]: [^---Agent*: test.my_agent]: Crashed reason=AttributeError("'PendingMessage' object has no attribute 'stream_meta'",)
Traceback (most recent call last):
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/mode/services.py", line 688, in _execute_task
    await task
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/faust/agents/agent.py", line 527, in _execute_task
    await coro
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/test.py", line 9, in my_agent
    async for message in stream:
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/faust/streams.py", line 776, in __aiter__
    on_stream_event_in(tp, offset, self, event)
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/faust/sensors/base.py", line 111, in on_stream_event_in
    sensor.on_stream_event_in(tp, offset, stream, event)
  File "/home/michael/arbeit/digitalernachschub/ameto/ameto/api/venv/lib64/python3.6/site-packages/faust/sensors/monitor.py", line 304, in on_stream_event_in
    'time_total': None,
AttributeError: 'PendingMessage' object has no attribute 'stream_meta'
```

# Versions

* Python version: 3.6.5
* Faust version: 1.0.30
* Operating system: Linux
* Kafka version: 1.0.1

**Comment by seifertm** [comment]
As it turns out, this is already fixed in master. Sorry…
