### ISSUE TITLE
Exception: Controller node not found

### ISSUE THREAD

**Issue by HengfengLi** [robinhood/faust#165]
## Checklist

- [x] I have included information about relevant versions
- [ ] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

I was trying to run the `hello_world.py` in [https://faust.readthedocs.io/en/latest/playbooks/quickstart.html](https://faust.readthedocs.io/en/latest/playbooks/quickstart.html). But I got an error "Exception: Controller node not found". 

I used the code from [https://github.com/wurstmeister/kafka-docker](https://github.com/wurstmeister/kafka-docker) to run a kafka cluster. 

```python
import faust

app = faust.App(
    'hello-world',
    broker='kafka://localhost:32768',
    value_serializer='raw',
)

greetings_topic = app.topic('greetings')

@app.agent(greetings_topic)
async def greet(greetings):
    async for greeting in greetings:
        print(greeting)
```
Note: `32768` is correct, which is the port of my local kafka node. 

## Expected behavior

Running successfully. 

## Actual behavior

It throws an exception "Controller node not found". 

## Full traceback

```pytb
Paste the full traceback (if there is any)

┌ƒaµS† v1.1.0─────────────────────────────────────────────────────────────┐
│ id        │ hello-world                                                 │
│ transport │ kafka://localhost:32768                                     │
│ store     │ memory:                                                     │
│ web       │ http://localhost:6066/                                      │
│ log       │ -stderr- (info)                                             │
│ pid       │ 99801                                                       │
│ hostname  │ Hengfengs-MacBook-Pro-2.local                               │
│ platform  │ CPython 3.7.0 (Darwin x86_64)                               │
│ drivers   │ aiokafka=0.4.18 aiohttp=3.4.4                               │
│ datadir   │ /Users/hengfengli/github/faust-examples/hello-world-data    │
│ appdir    │ /Users/hengfengli/github/faust-examples/hello-world-data/v1 │
└───────────┴─────────────────────────────────────────────────────────────┘
[2018-09-15 16:09:10,804: INFO]: [^Worker]: Starting...
[2018-09-15 16:09:10,805: INFO]: [^-Website]: Starting...
[2018-09-15 16:09:10,805: INFO]: [^--Web]: Starting...
[2018-09-15 16:09:10,809: INFO]: [^---ServerThread]: Starting...
[2018-09-15 16:09:10,810: INFO]: [^--Web]: Serving on http://localhost:6066/
[2018-09-15 16:09:10,812: INFO]: [^-App]: Starting...
[2018-09-15 16:09:10,812: INFO]: [^--MonitorService]: Starting...
[2018-09-15 16:09:10,813: INFO]: [^--Producer]: Starting...
[2018-09-15 16:09:10,833: WARNING]: No broker metadata found in MetadataResponse
[2018-09-15 16:09:10,844: INFO]: [^--Consumer]: Starting...
[2018-09-15 16:09:10,851: WARNING]: No broker metadata found in MetadataResponse
[2018-09-15 16:09:10,858: INFO]: [^--LeaderAssignor]: Starting...
[2018-09-15 16:09:10,859: INFO]: [^--Producer]: Creating topic hello-world-__assignor-__leader
[2018-09-15 16:09:10,860: ERROR]: [^Worker]: Error: Exception('Controller node not found')
Traceback (most recent call last):
  File "/Users/hengfengli/.local/share/virtualenvs/faust-examples-U2wf8zL_/lib/python3.7/site-packages/mode/worker.py", line 189, in execute_from_commandline
    self.loop.run_until_complete(self.start())
  File "/usr/local/Cellar/python/3.7.0/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 568, in run_until_complete
    return future.result()
  File "/Users/hengfengli/.local/share/virtualenvs/faust-examples-U2wf8zL_/lib/python3.7/site-packages/mode/worker.py", line 241, in start
    await super().start()
  File "/Users/hengfengli/.local/share/virtualenvs/faust-examples-U2wf8zL_/lib/python3.7/site-packages/mode/services.py", line 657, in start
    await self._default_start()
  File "/Users/hengfengli/.local/share/virtualenvs/faust-examples-U2wf8zL_/lib/python3.7/site-packages/mode/services.py", line 662, in _default_start
    await self._actually_start()
  File "/Users/hengfengli/.local/share/virtualenvs/faust-examples-U2wf8zL_/lib/python3.7/site-packages/mode/services.py", line 678, in _actually_start
    await child.maybe_start()
  File "/Users/hengfengli/.local/share/virtualenvs/faust-examples-U2wf8zL_/lib/python3.7/site-packages/mode/proxy.py", line 50, in maybe_start
    await self._service.maybe_start()
  File "/Users/hengfengli/.local/share/virtualenvs/faust-examples-U2wf8zL_/lib/python3.7/site-packages/mode/services.py", line 701, in maybe_start
    await self.start()
  File "/Users/hengfengli/.local/share/virtualenvs/faust-examples-U2wf8zL_/lib/python3.7/site-packages/mode/services.py", line 657, in start
    await self._default_start()
  File "/Users/hengfengli/.local/share/virtualenvs/faust-examples-U2wf8zL_/lib/python3.7/site-packages/mode/services.py", line 662, in _default_start
    await self._actually_start()
  File "/Users/hengfengli/.local/share/virtualenvs/faust-examples-U2wf8zL_/lib/python3.7/site-packages/mode/services.py", line 678, in _actually_start
    await child.maybe_start()
  File "/Users/hengfengli/.local/share/virtualenvs/faust-examples-U2wf8zL_/lib/python3.7/site-packages/mode/services.py", line 701, in maybe_start
    await self.start()
  File "/Users/hengfengli/.local/share/virtualenvs/faust-examples-U2wf8zL_/lib/python3.7/site-packages/mode/services.py", line 657, in start
    await self._default_start()
  File "/Users/hengfengli/.local/share/virtualenvs/faust-examples-U2wf8zL_/lib/python3.7/site-packages/mode/services.py", line 662, in _default_start
    await self._actually_start()
  File "/Users/hengfengli/.local/share/virtualenvs/faust-examples-U2wf8zL_/lib/python3.7/site-packages/mode/services.py", line 673, in _actually_start
    await self.on_start()
  File "/Users/hengfengli/.local/share/virtualenvs/faust-examples-U2wf8zL_/lib/python3.7/site-packages/faust/assignor/leader_assignor.py", line 20, in on_start
    await leader_topic.maybe_declare()
  File "/Users/hengfengli/.local/share/virtualenvs/faust-examples-U2wf8zL_/lib/python3.7/site-packages/mode/utils/futures.py", line 36, in __call__
    result = await self.fun(*self.args, **self.kwargs)
  File "/Users/hengfengli/.local/share/virtualenvs/faust-examples-U2wf8zL_/lib/python3.7/site-packages/faust/topics.py", line 368, in maybe_declare
    await self.declare()
  File "/Users/hengfengli/.local/share/virtualenvs/faust-examples-U2wf8zL_/lib/python3.7/site-packages/faust/topics.py", line 386, in declare
    retention=self.retention,
  File "/Users/hengfengli/.local/share/virtualenvs/faust-examples-U2wf8zL_/lib/python3.7/site-packages/faust/transport/drivers/aiokafka.py", line 662, in create_topic
    ensure_created=ensure_created,
  File "/Users/hengfengli/.local/share/virtualenvs/faust-examples-U2wf8zL_/lib/python3.7/site-packages/faust/transport/drivers/aiokafka.py", line 753, in _create_topic
    await wrap()
  File "/Users/hengfengli/.local/share/virtualenvs/faust-examples-U2wf8zL_/lib/python3.7/site-packages/mode/utils/futures.py", line 36, in __call__
    result = await self.fun(*self.args, **self.kwargs)
  File "/Users/hengfengli/.local/share/virtualenvs/faust-examples-U2wf8zL_/lib/python3.7/site-packages/faust/transport/drivers/aiokafka.py", line 803, in _really_create_topic
    timeout=timeout)
  File "/Users/hengfengli/.local/share/virtualenvs/faust-examples-U2wf8zL_/lib/python3.7/site-packages/faust/transport/drivers/aiokafka.py", line 776, in _get_controller_node
    raise Exception(f'Controller node not found')
Exception: Controller node not found
[2018-09-15 16:09:10,864: INFO]: [^Worker]: Stopping...
[2018-09-15 16:09:10,864: INFO]: [^-App]: Stopping...
[2018-09-15 16:09:10,865: INFO]: [^--TableManager]: Stopping...
[2018-09-15 16:09:10,865: INFO]: [^--Fetcher]: Stopping...
[2018-09-15 16:09:10,865: INFO]: [^--Fetcher]: -Stopped!
[2018-09-15 16:09:10,865: INFO]: [^--TableManager]: -Stopped!
[2018-09-15 16:09:10,866: INFO]: [^--Conductor]: Stopping...
[2018-09-15 16:09:10,866: INFO]: [^--Conductor]: -Stopped!
[2018-09-15 16:09:10,866: INFO]: [^AgentManagerService]: Stopping...
[2018-09-15 16:09:10,867: INFO]: [^--Agent]: Stopping...
[2018-09-15 16:09:10,867: INFO]: [^--Agent]: -Stopped!
[2018-09-15 16:09:10,867: INFO]: [^AgentManagerService]: -Stopped!
[2018-09-15 16:09:10,867: INFO]: [^--ReplyConsumer]: Stopping...
[2018-09-15 16:09:10,868: INFO]: [^--ReplyConsumer]: -Stopped!
[2018-09-15 16:09:10,868: INFO]: [^--LeaderAssignor]: Stopping...
[2018-09-15 16:09:10,868: INFO]: [^--LeaderAssignor]: -Stopped!
[2018-09-15 16:09:10,868: INFO]: [^--Consumer]: Stopping...
[2018-09-15 16:09:10,869: INFO]: [^--Consumer]: -Stopped!
[2018-09-15 16:09:10,870: INFO]: [^--Producer]: Stopping...
[2018-09-15 16:09:10,871: INFO]: [^--Producer]: -Stopped!
[2018-09-15 16:09:10,871: INFO]: [^--MonitorService]: Stopping...
[2018-09-15 16:09:10,872: INFO]: [^--MonitorService]: -Stopped!
[2018-09-15 16:09:10,872: INFO]: [^-App]: -Stopped!
[2018-09-15 16:09:10,873: INFO]: [^-Website]: Stopping...
[2018-09-15 16:09:10,873: INFO]: [^--Web]: Stopping...
[2018-09-15 16:09:10,873: INFO]: [^---ServerThread]: Stopping...
[2018-09-15 16:09:10,874: INFO]: [^--Web]: Closing server
[2018-09-15 16:09:10,874: INFO]: [^--Web]: Waiting for server to close handle
[2018-09-15 16:09:10,875: INFO]: [^--Web]: Shutting down web application
[2018-09-15 16:09:10,875: INFO]: [^--Web]: Waiting for handler to shut down
[2018-09-15 16:09:10,875: INFO]: [^--Web]: Cleanup
[2018-09-15 16:09:10,876: INFO]: [^---ServerThread]: -Stopped!
[2018-09-15 16:09:10,876: INFO]: [^--Web]: -Stopped!
[2018-09-15 16:09:10,876: INFO]: [^-Website]: -Stopped!
[2018-09-15 16:09:10,877: INFO]: [^Worker]: -Stopped!
[2018-09-15 16:09:10,877: INFO]: [^Worker]: Gathering service tasks...
[2018-09-15 16:09:10,877: INFO]: [^Worker]: Gathering all futures...
[2018-09-15 16:09:11,980: INFO]: [^Worker]: Closing event loop
starting^
```

# Versions

* Python version: 3.7.0
* Faust version: 1.1.0
* Operating system: MacOS 10.13.3
* Kafka version: 2.0.0
* RocksDB version (if applicable)

**Comment by HengfengLi** [comment]
It's my bad. I didn't set up my kafka cluster properly due to the missing configuration of `KAFKA_ADVERTISED_HOST_NAME` in [https://github.com/wurstmeister/kafka-docker](https://github.com/wurstmeister/kafka-docker).
