### ISSUE TITLE
Error with abstract and inherited models

### ISSUE THREAD

**Issue by ghost** [robinhood/faust#168]
## Steps to reproduce

``` py

import faust
import asyncio
import signal

from faust import Record

class Model1Base(Record, abstract=True):
    pass

class Model1_1(Model1Base):
    field1: str
    field2: str

class Model1_2(Model1Base):
    field1: str
    field2: str

class Model2(Record):
    field1: str
    field2: str
    field3: Model1Base

async def main():
    m1 = Model1_1("field1", "field2")
    m2 = Model2("field1", "field2", m1)
    
    serialized = m2.dumps()
    
    m2_loads = Model2.loads(serialized)
    print(m2_loads)

# Stop the loop concurrently           
async def exit():                                              
    loop = asyncio.get_event_loop()                      
    print("Exiting gracefully...")                                        
    loop.stop()   

def ask_exit():                          
    for task in asyncio.Task.all_tasks():
        task.cancel()                    
    asyncio.ensure_future(exit()) 

if __name__ == '__main__':
    loop = asyncio.get_event_loop()                      
    asyncio.ensure_future(main()) 
    for sig in (signal.SIGINT, signal.SIGTERM):          
        loop.add_signal_handler(sig, ask_exit)           
    loop.run_forever()                                   
    loop.close() 
```

## Expected behavior

I expected the model to be deserialized to the correct sub-class of Model1Base with all the various functionality still in place, like printing, etc.

## Actual behavior

I get the traceback below.  Faust appears to be trying to deserialize the base class rather than the extended class that was actually passed.

edit: Actually, it may be deserializing, but some kind of error is creeping in when you try and access the model normally, i.e. you can't print it or "dumps()" it.

## Full traceback

```pytb
Traceback (most recent call last):
  File "test.py", line 42, in main
    print(m2_loads)
  File "/usr/local/anaconda2/envs/es_faust/lib/python3.7/site-packages/faust/models/base.py", line 361, in __repr__
    return f'<{type(self).__name__}: {self._humanize()}>'
  File "/usr/local/anaconda2/envs/es_faust/lib/python3.7/site-packages/faust/models/record.py", line 462, in _humanize
    return _kvrepr(fields)
  File "/usr/local/anaconda2/envs/es_faust/lib/python3.7/site-packages/faust/models/record.py", line 490, in _kvrepr
    return sep.join(f'{k}={v!r}' for k, v in d.items())
  File "/usr/local/anaconda2/envs/es_faust/lib/python3.7/site-packages/faust/models/record.py", line 490, in <genexpr>
    return sep.join(f'{k}={v!r}' for k, v in d.items())
  File "/usr/local/anaconda2/envs/es_faust/lib/python3.7/site-packages/faust/models/base.py", line 361, in __repr__
    return f'<{type(self).__name__}: {self._humanize()}>'
  File "/usr/local/anaconda2/envs/es_faust/lib/python3.7/site-packages/faust/models/record.py", line 456, in _humanize
    attrs, defaults = self.__dict__, self._options.defaults.items()
AttributeError: 'NoneType' object has no attribute 'items'
```

# Versions

Using Faust 1.1.2 with Python 3.7.0

**Comment by ask** [comment]
Oh, yeah, there is a bug there, the abstract class has self._options.defaults set to None so it crashes.

More importantly, your code will not work as-is.

To support polymorphic types models need to include the type of object in the payload.
If you look at the payload generated by `Model1_2` you can see it includes this special key:

```py
>>> Model1_2('foo', 'bar').dumps()
{'field1': 'foo', 'field2': 'bar', '__faust': {'ns': 'foo.Model1_2'}}
```

We refer to this as the "blessed key": it can be used to reconstruct the object back to its original class.
This is safe, it does not come with the security implications of allowing any class like pickle/pyyaml does, but there are also many cases where you don't want this to happen (for example the producer used a class you don't have access to).

To enable use of the blessed key you should do so in the abstract class:

```py
class Model1Base(Record, abstract=True, allow_blessed_key=True):
    pass
```

After this the model should be reconstructed the way you want it.

To make this more DWIM, perhaps blessed keys could be automatically allowed if key/value_type is set to an abstract model.

NOTE: You can disable adding the blessed key to the payload alltogether using `class X(faust.Record, include_metadata=False)`

**Comment by jeremyclimacell** [comment]
Yeah, I went back and looked at the code and the "blessed key" is generated in the JSON without the 'allow_blessed_key=True', so it seems logical that if the default is to generate the blessed key on ".dumps()", the library should use it by default on ".loads()", too.

Thanks for the help!
