### ISSUE TITLE
Problem with custom Codecs / Serializers

### ISSUE THREAD

**Issue by wuttem** [robinhood/faust#173]
## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce
I want to use custom serializers with binary formats.

Example Code
```python
import faust
import struct

from faust.serializers import codecs
from io import BytesIO
from typing import Any


class RawXY(faust.Record, serializer='raw_xy'):
    x: int
    y: int


class RawXYSerializer(codecs.Codec):
    def _dumps(self, obj: Any) -> bytes:
        payload = BytesIO()
        payload.write(struct.pack('f', obj["x"]))
        payload.write(struct.pack('f', obj["y"]))
        return payload.getvalue()

    def _loads(self, s: bytes) -> Any:
        payload = BytesIO(s)
        d = {}
        d["x"] = struct.unpack("f", payload.read(4))[0]
        d["y"] = struct.unpack("f", payload.read(4))[0]
        return d


codecs.register("raw_xy", RawXYSerializer())

app = faust.App('test', broker='kafka://localhost:29092', store='memory://', key_serializer='raw', value_serializer='raw')
message_topic = app.topic('messages', key_type=bytes, value_type=RawXY)


@app.agent(message_topic)
async def mystream(stream: faust.Stream):
    async for e in stream.events():
        print(e.key)
        print(e.value)


@app.task
async def on_started():
    await message_topic.send(key=b"abc", value=RawXY(x=2, y=2))

```

Example for working serialization

```python
# Using the Models like this works:
o1 = RawXY(x=2.0, y=2.0)
print(o1)
b = o1.dumps()
print(b)
o2 = RawXY.loads(b)
print(o2)
assert o1 == o2

```

## Expected behavior

Custom serializers and custom Record Classes work as expected

## Actual behavior

I tried a lot of different combinations but i could manage to get custom serializers and Records with binary data to work. I can reproduce problems when using just a single topic. As soon as a try to also use custom Records and serializers in Tables the problems get even worst. It looks like the serializers for the records are ignored on various code paths. I think this could be what #148 is refering to...

## Full traceback

```pytb
[^---Agent*: faust_bug.mystream]: Crashed reason=ValueDecodeError('type object argument after ** must be a mapping, not bytes',)
Traceback (most recent call last):
  File "/home/mths/Envs/faust_test/lib/python3.6/site-packages/faust/serializers/registry.py", line 99, in loads_value
    return cast(V, self._prepare_payload(typ, payload))
  File "/home/mths/Envs/faust_test/lib/python3.6/site-packages/faust/serializers/registry.py", line 122, in _prepare_payload
    return model.from_data(value, preferred_type=model)
  File "/home/mths/Envs/faust_test/lib/python3.6/site-packages/faust/models/record.py", line 303, in from_data
    return (self_cls or cls)(**data, __strict__=False)
TypeError: type object argument after ** must be a mapping, not bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/mths/Envs/faust_test/lib/python3.6/site-packages/mode/services.py", line 694, in _execute_task
    await task
  File "/home/mths/Envs/faust_test/lib/python3.6/site-packages/faust/agents/agent.py", line 559, in _execute_task
    await coro
  File "/mnt/c/Users/mths/smaxtec/anthillprocessing-stream/example/faust_bug.py", line 37, in mystream
    async for e in stream.events():
  File "/home/mths/Envs/faust_test/lib/python3.6/site-packages/faust/streams.py", line 297, in events
    async for _ in self:  # noqa: F841
  File "/home/mths/Envs/faust_test/lib/python3.6/site-packages/faust/streams.py", line 751, in __aiter__
    channel_value = await chan_slow_get()
  File "/home/mths/Envs/faust_test/lib/python3.6/site-packages/faust/channels.py", line 294, in __anext__
    return await self.queue.get()
  File "/home/mths/Envs/faust_test/lib/python3.6/site-packages/mode/utils/queues.py", line 125, in get
    return await super().get()
  File "/usr/lib/python3.6/asyncio/queues.py", line 167, in get
    yield from getter
  File "/home/mths/Envs/faust_test/lib/python3.6/site-packages/faust/transport/conductor.py", line 80, in on_message
    event = await chan.decode(message, propagate=True)
  File "/home/mths/Envs/faust_test/lib/python3.6/site-packages/faust/topics.py", line 195, in decode
    value_type, message.value, serializer=value_serializer)
  File "/home/mths/Envs/faust_test/lib/python3.6/site-packages/faust/serializers/registry.py", line 104, in loads_value
    sys.exc_info()[2]) from exc
  File "/home/mths/Envs/faust_test/lib/python3.6/site-packages/faust/serializers/registry.py", line 99, in loads_value
    return cast(V, self._prepare_payload(typ, payload))
  File "/home/mths/Envs/faust_test/lib/python3.6/site-packages/faust/serializers/registry.py", line 122, in _prepare_payload
    return model.from_data(value, preferred_type=model)
  File "/home/mths/Envs/faust_test/lib/python3.6/site-packages/faust/models/record.py", line 303, in from_data
    return (self_cls or cls)(**data, __strict__=False)
faust.exceptions.ValueDecodeError: type object argument after ** must be a mapping, not bytes

```

# Versions

* Python 3.6.5
* Faust: 1.1.3 (master branch)

**Comment by ask** [comment]
Thanks for reporting!
Fixed by 35233d3111b13bb7b140258afcb7b15d5f5d5ddf
