### ISSUE TITLE
Topic created with a single partition

### ISSUE THREAD

**Issue by wuttem** [robinhood/faust#178]
## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

Configure app or topic with more than 1 partition.

```python
import faust


app = faust.App('my_test', broker='kafka://localhost:29092', store='memory://', key_serializer='raw', value_serializer='raw', partitions=6)
message_topic = app.topic('my_topic', key_type=bytes, value_type=bytes, partitions=4)


@app.agent(message_topic)
async def mystream(stream: faust.Stream):
    async for e in stream.events():
        print(e.key)
        print(e.value)


@app.task
async def on_started():
    await message_topic.send(key=b"abc", value=b"abcdef", partition=0)
    await message_topic.send(key=b"abc", value=b"abcdef", partition=1)
    await message_topic.send(key=b"abc", value=b"abcdef", partition=2)
    await message_topic.send(key=b"abc", value=b"abcdef", partition=3)
```

## Expected behavior

Topic is created with the correct number of partitions.

## Actual behavior

Topic is created with a single partition. Sending an event to another partition than the first one raises an error.

## Full traceback

Error when trying to send to partition 1: 

```pytb
Traceback (most recent call last):
  File "/home/mths/.virtualenvs/stream/lib/python3.6/site-packages/mode/services.py", line 700, in _execute_task
    await task
  File "/mnt/c/workspace/faust/faust/app/base.py", line 619, in _wrapped
    return await task()
  File "/mnt/c/workspace/anthillprocessing-stream/faust_partition_bug.py", line 18, in on_started
    await message_topic.send(key=b"abc", value=b"abcdef", partition=1)
  File "/mnt/c/workspace/faust/faust/topics.py", line 175, in send
    callback=callback,
  File "/mnt/c/workspace/faust/faust/channels.py", line 201, in _send_now
    value_serializer, callback))
  File "/mnt/c/workspace/faust/faust/topics.py", line 355, in publish_message
    topic, key, value, partition=message.partition)
  File "/mnt/c/workspace/faust/faust/transport/drivers/aiokafka.py", line 681, in send
    topic, value, key=key, partition=partition))
  File "/home/mths/.virtualenvs/stream/lib/python3.6/site-packages/aiokafka/producer/producer.py", line 307, in send
    key_bytes, value_bytes)
  File "/home/mths/.virtualenvs/stream/lib/python3.6/site-packages/aiokafka/producer/producer.py", line 531, in _partition
    'Unrecognized partition'
AssertionError: Unrecognized partition
```

# Versions

```
┌ƒaµS† v1.2.0───────────────────────────────────────────────────────────┐
│ id        │ my_test                                                   │
│ transport │ kafka://localhost:29092                                   │
│ store     │ memory:                                                   │
│ web       │ http://mths0:6066                                         │
│ log       │ -stderr- (info)                                           │
│ pid       │ 433                                                       │
│ hostname  │ MTHS0                                                     │
│ platform  │ CPython 3.6.5 (Linux x86_64)                              │
│ drivers   │ aiokafka=0.4.18 aiohttp=3.4.4                             │
│ datadir   │ /mnt/c/workspace/anthillprocessing-stream/my_test-data    │
│ appdir    │ /mnt/c/workspace/anthillprocessing-stream/my_test-data/v1 │
└───────────┴───────────────────────────────────────────────────────────┘
```

**Comment by wuttem** [comment]
I just found out that Topics that are not marked as internal=True will not be created ... the creation in this cas is implicit by Kafka ...
