### ISSUE TITLE
Table routing for web views not working

### ISSUE THREAD

**Issue by amerski99** [robinhood/faust#180]
## Steps to reproduce

Try to access data on a table (rocksdb) via a web view when there are multiple workers (works correctly when there is only one worker).

The table has only one partition.  The partition is getting correctly assigned to a worker.  Reading/writing the table data from the agents/streams/etc all works correctly.  However, there seems to be an error in routing to the table.

Here is my code accessing the table:
```
@app.page('/progress/{run_id}')
@app.table_route(table=track_run_table, match_info='run_id')
async def get_progress_summary(web, request, run_id):
    value: RunSetTracker = track_run_table.get(run_id)
    if value:
        return web.json(summarize(value.asdict()))
    else:
        return web.json({'message': 'not-found'})
```

## Expected behavior

No error.

## Actual behavior

Getting this error:

```pytb
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_protocol.py", line 390, in start
    resp = await self._request_handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_app.py", line 366, in _handle
    resp = await handler(request)
  File "/usr/local/lib/python3.7/site-packages/aiohttp/web_urldispatcher.py", line 120, in handler_wrapper
    result = await result
  File "/usr/local/lib/python3.7/site-packages/faust/web/views.py", line 66, in __call__
    return await self.dispatch(request)
  File "/usr/local/lib/python3.7/site-packages/faust/web/views.py", line 77, in dispatch
    return await method(cast(Request, request), **kwargs)
  File "/usr/local/lib/python3.7/site-packages/faust/app/base.py", line 791, in get
    view.web, request)
  File "/usr/local/lib/python3.7/site-packages/faust/app/router.py", line 50, in route_req
    dest_url: URL = app.router.key_store(table_name, key)
  File "/usr/local/lib/python3.7/site-packages/faust/app/router.py", line 26, in key_store
    return self._assignor.key_store(topic, k)
  File "/usr/local/lib/python3.7/site-packages/faust/assignor/partition_assignor.py", line 302, in key_store
    return URL(self._tps_url[self.app.producer.key_partition(topic, key)])
KeyError: TP(topic='rhino-track_run-changelog', partition=0)
```

# Versions

* Python version:  python 3.7 / CPython 3.7.0 (Linux x86_64)  
       aiokafka=0.4.18 aiohttp=3.4.4
* Faust version: 1.2.0
* Operating system: ubuntu/16.04
* Kafka version: 2.11

**Comment by hartmutbehrens** [comment]
Assuming run_id is an int, try: track_run_table.get(int(run_id))

**Comment by ask** [comment]
Is this happening at startup?

This error used to be raised when the table was routed to before partition assignment has happened.
It should now return HTTP 503 SERVICE UNAVAILABLE when this happens.

**Comment by roshangeorge93** [comment]
Any update on this issue?

**Comment by vandenbogart** [comment]
Also recently encountered this issue. If I start the program with multiple workers and empty partitions, events I publish to the stream are processed by each of the workers. However, when trying to use table_route to view each key I am routed to the incorrect worker.

If I kill all but one worker so partitions are reassigned and entire table exists on this single worker, then starting new workers will correctly distribute the table and routing will work correctly.

**Comment by szicari-farmobile** [comment]
For what it's worth, I tested with `NO_CYTHON=true` and without the `[fast]` extensions. In both cases, I started with 1 instance and scaled up one at a time. Consistently, table routing was broken when I got to 3 instances running.

**Comment by szicari-farmobile** [comment]
I'm going to amend that and say I'm seeing undefined behavior. Some table lookups work between instances and some don't. I can't tell yet what is common to those that don't.

**Comment by szicari-farmobile** [comment]
In my case, I just found that the app router is raising the SameNode exception when looking up which instance has the data. So maybe the app isn't registering new instances when they come online?
```Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/faust/app/base.py", line 1273, in get
    return await self.router.route_req(table.name, key,
  File "/usr/local/lib/python3.8/site-packages/faust/app/router.py", line 70, in route_req
    raise SameNode()
faust.exceptions.SameNode
```
