### ISSUE TITLE
Running with isolated_partitions and more than 2 workers crashes

### ISSUE THREAD

**Issue by barelyreal** [robinhood/faust#181]
## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

- set "isolated_partitions=True" when declaring the agent.
- start 3 worker instances.

## Expected behavior

- Run normally with no crash

## Actual behavior

After repartitioning, one of the workers crashed with an assertion error.

## Full traceback

```pytb
[2018-10-10 13:13:15,634: INFO]: [^Worker]: Closing event loop
starting^[2018-10-10 13:13:15,636: CRITICAL]: [^Worker]: We experienced a crash! Reraising original exception...
Traceback (most recent call last):
  File "/usr/bin/faust", line 11, in <module>
    sys.exit(cli())
  File "/usr/lib/python3.6/site-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib/python3.6/site-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib/python3.6/site-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/lib/python3.6/site-packages/faust/cli/base.py", line 457, in _inner
    return cmd()
  File "/usr/lib/python3.6/site-packages/faust/cli/base.py", line 529, in __call__
    self.run_using_worker(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/faust/cli/base.py", line 538, in run_using_worker
    return worker.execute_from_commandline()
  File "/usr/lib/python3.6/site-packages/mode/worker.py", line 195, in execute_from_commandline
    self.stop_and_shutdown()
  File "/usr/lib/python3.6/site-packages/mode/worker.py", line 200, in stop_and_shutdown
    self._shutdown_loop()
  File "/usr/lib/python3.6/site-packages/mode/worker.py", line 228, in _shutdown_loop
    raise self._crash_reason from self._crash_reason
  File "/usr/lib/python3.6/site-packages/faust/app/base.py", line 986, in _on_partitions_assigned
    await self.topics.on_partitions_assigned(assigned)
  File "/usr/lib/python3.6/site-packages/faust/transport/conductor.py", line 256, in on_partitions_assigned
    self._update_tp_index(assigned)
  File "/usr/lib/python3.6/site-packages/faust/transport/conductor.py", line 266, in _update_tp_index
    assert topic.active_partitions.issubset(assigned)
AssertionError
```

# Versions

* Python version 3.6
* Faust version 1.2.0
* Operating system CentOS 7
* Kafka version 11
* RocksDB version (if applicable) N/A

**Comment by ask** [comment]
How many partitions does the source topic have?

I'm guessing this assert does not account for when there are more workers than partitions,
and this worker was not assigned any partitions.

**Comment by michalmo** [comment]
I've been able to reproduce this issue with a very simple example.

# Steps to reproduce
- Define an agent with `isolated_partitions=True` and `topic_partitions` greater than 1.
- Start a single worker instance.
- Start another worker instance.

# Expected behavior
Run normally with no crash.

# Actual behavior
After repartitioning, the original worker crashes with the above assertion error.

# Cause
The `_update_tp_index` method is iterating over the set of topics (https://github.com/robinhood/faust/blob/v1.10.3/faust/transport/conductor.py#L306).

Each Actor instance, started for an isolated partition, receives a stream from the topic, cloned with active_partitions set appropriately. When the Actor starts iterating over the stream, which in turn iterates over the topic, the topic is added to the conductor (https://github.com/robinhood/faust/blob/v1.10.3/faust/topics.py#L488).

Since the topic is never removed from the conductor, the described error is triggered when repartitioning, if the assigned partitions are a subset of the previously assigned partitions, because the old topics are iterated over and fail the issubset check.
