### ISSUE TITLE
Currently master doesn't pass flake8 test scripts

### ISSUE THREAD

**Issue by omarrayward** [robinhood/faust#195]
## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

With master set at 359d63312f3d49d61cb23ce79a4f90f091241a82, remove all requirements and run `tox`, we get an exception:

```bash
AttributeError: module 'pycodestyle' has no attribute 'break_after_binary_operator'
```

## Expected behavior

No exceptions

## Actual behavior

The `flake8` command doesn't succeed because of this exception:
```bash
AttributeError: module 'pycodestyle' has no attribute 'break_after_binary_operator'
```

## Full traceback

```pytb
flake8 runtests: commands[0] | flake8 /home/travis/build/robinhood/faust/faust /home/travis/build/robinhood/faust/t /home/travis/build/robinhood/faust/examples
  /home/travis/build/robinhood/faust$ /home/travis/build/robinhood/faust/.tox/flake8/bin/flake8 /home/travis/build/robinhood/faust/faust /home/travis/build/robinhood/faust/t /home/travis/build/robinhood/faust/examples 
/home/travis/build/robinhood/faust/.tox/flake8/lib/python3.7/site-packages/pycodestyle.py:113: FutureWarning: Possible nested set at position 1
  EXTRANEOUS_WHITESPACE_REGEX = re.compile(r'[[({] | []}),;:]')
Traceback (most recent call last):
  File "/home/travis/build/robinhood/faust/.tox/flake8/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2351, in resolve
    return functools.reduce(getattr, self.attrs, module)
AttributeError: module 'pycodestyle' has no attribute 'break_after_binary_operator'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/build/robinhood/faust/.tox/flake8/lib/python3.7/site-packages/flake8/plugins/manager.py", line 182, in load_plugin
    self._load(verify_requirements)
  File "/home/travis/build/robinhood/faust/.tox/flake8/lib/python3.7/site-packages/flake8/plugins/manager.py", line 154, in _load
    self._plugin = resolve()
  File "/home/travis/build/robinhood/faust/.tox/flake8/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2353, in resolve
    raise ImportError(str(exc))
ImportError: module 'pycodestyle' has no attribute 'break_after_binary_operator'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/home/travis/build/robinhood/faust/.tox/flake8/bin/flake8", line 11, in <module>
    sys.exit(main())
  File "/home/travis/build/robinhood/faust/.tox/flake8/lib/python3.7/site-packages/flake8/main/cli.py", line 16, in main
    app.run(argv)
  File "/home/travis/build/robinhood/faust/.tox/flake8/lib/python3.7/site-packages/flake8/main/application.py", line 412, in run
    self._run(argv)
  File "/home/travis/build/robinhood/faust/.tox/flake8/lib/python3.7/site-packages/flake8/main/application.py", line 399, in _run
    self.initialize(argv)
  File "/home/travis/build/robinhood/faust/.tox/flake8/lib/python3.7/site-packages/flake8/main/application.py", line 381, in initialize
    self.find_plugins()
  File "/home/travis/build/robinhood/faust/.tox/flake8/lib/python3.7/site-packages/flake8/main/application.py", line 197, in find_plugins
    self.check_plugins.load_plugins()
  File "/home/travis/build/robinhood/faust/.tox/flake8/lib/python3.7/site-packages/flake8/plugins/manager.py", line 434, in load_plugins
    plugins = list(self.manager.map(load_plugin))
  File "/home/travis/build/robinhood/faust/.tox/flake8/lib/python3.7/site-packages/flake8/plugins/manager.py", line 319, in map
    yield func(self.plugins[name], *args, **kwargs)
  File "/home/travis/build/robinhood/faust/.tox/flake8/lib/python3.7/site-packages/flake8/plugins/manager.py", line 432, in load_plugin
    return plugin.load_plugin()
  File "/home/travis/build/robinhood/faust/.tox/flake8/lib/python3.7/site-packages/flake8/plugins/manager.py", line 189, in load_plugin
    raise failed_to_load
flake8.exceptions.FailedToLoadPlugin: Flake8 failed to load plugin "pycodestyle.break_after_binary_operator" due to module 'pycodestyle' has no attribute 'break_after_binary_operator'.
ERROR: InvocationError for command '/home/travis/build/robinhood/faust/.tox/flake8/bin/flake8 /home/travis/build/robinhood/faust/faust /home/travis/build/robinhood/faust/t /home/travis/build/robinhood/faust/examples' (exited with code 1)
___________________________________ summary ____________________________________
ERROR:   flake8: commands failed
```

# Versions

* Python version: 3.7.0
* Faust version:  1.2.1
* Operating system: ?? (Travis CI)
* Kafka version: N/A
* RocksDB version (if applicable) N/A

# Description of issue

The issue is that 3 days ago, flake8 version 3.6.0 was released. 
[One of the commits](https://gitlab.com/pycqa/flake8/commit/69b1eb33795943118ec58717d21040f7f0bde422) that went into this release, requires `pycodestyle >2.4.0` which conflicts with [`pycodestyle<2.4.0`](https://github.com/robinhood/faust/blob/master/requirements/flakes.txt#L13)

# Possible solutions

- Change `flake8` requirements to `flake8>3.6.0` and remove `pycodestyle<2.4.0`. This throws a bunch of linting errors that I'm not sure how @ask / @vineetgoel want to deal with them (either fix them or ignore them). There is a [WIP PR](https://github.com/robinhood/faust/pull/197) in which I left some questions around how to solve the linting errors.  

- Change `flake8` requirements to `flake8>=2.5.4,<3.6.0`, which was already done [here](https://github.com/robinhood/faust/pull/194)

**Comment by omarrayward** [comment]
This specific issue was solved here https://github.com/robinhood/faust/pull/197
