### ISSUE TITLE
Unable to fetch stream from kafka topic

### ISSUE THREAD

**Issue by learnermaxRL** [robinhood/faust#225]
## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

```
import faust

class Greeting(faust.Record):
    # from_name: str
    # to_name: str
    time = str
    image = str
    camera = str
    height = str
    width = str

app = faust.App('hello-app', broker='kafka://localhost:9092',topic_partitions=4)
topic = app.topic('camera_streams', value_type=Greeting)

@app.agent(topic)
async def process(stream):
    async for value in stream:
         print(value)


if __name__ == '__main__':
    app.main()

```
 Command - `faust -A stream_process worker -l info`

## Expected behavior

Print values from kafka stream for the topic - "camera_streams",but instead faust shuts down with timeout error,my main goal is to consume the streams from kafka and process it using some function and then finally dump it in a sink.

## Actual behavior

Timeout,and is not able to connect and print the stream values from kafka topic

## Full traceback

Paste the full traceback (if there is any)

```pytb

┌ƒaµS† v1.3.2───────────────────────────────────────────────────────────────────────────────────────────┐
│ id        │ hello-app                                                                                 │
│ transport │ kafka://localhost:9092                                                                    │
│ store     │ memory:                                                                                   │
│ web       │ http://localhost:6066/                                                                    │
│ log       │ -stderr- (info)                                                                           │
│ pid       │ 14515                                                                                     │
│ hostname  │ ms                                                                                     │
│ platform  │ CPython 3.6.6 (Linux x86_64)                                                              │
│ drivers   │ aiokafka=0.4.19 aiohttp=3.4.4                                                             │
│ datadir   │ /home/ms/Downloads/faster_rcnn_inception_v2_coco_2018_01_28/utils_ob/hello-app-data    │
│ appdir    │ /home/ms/Downloads/faster_rcnn_inception_v2_coco_2018_01_28/utils_ob/hello-app-data/v1 │
└───────────┴───────────────────────────────────────────────────────────────────────────────────────────┘
[2018-11-26 18:14:54,510: INFO]: [^Worker]: Starting...
[2018-11-26 18:14:54,514: INFO]: [^-App]: Starting...
[2018-11-26 18:14:54,514: INFO]: [^--Monitor]: Starting...
[2018-11-26 18:14:54,514: INFO]: [^CacheBackend]: Starting...
[2018-11-26 18:14:54,514: INFO]: [^Web]: Starting...
[2018-11-26 18:14:54,518: INFO]: [^-ServerThread]: Starting...
[2018-11-26 18:14:54,519: INFO]: [^Web]: Serving on http://localhost:6066/
[2018-11-26 18:14:54,520: INFO]: [^--Producer]: Starting...
[2018-11-26 18:14:54,633: INFO]: [^--Consumer]: Starting...
[2018-11-26 18:14:54,749: INFO]: [^--LeaderAssignor]: Starting...
[2018-11-26 18:14:54,750: INFO]: [^--Producer]: Creating topic hello-app-__assignor-__leader
[2018-11-26 18:15:34,758: ERROR]: [^Worker]: Error: RequestTimedOutError()
Traceback (most recent call last):
  File "/home/ms/anaconda3/envs/tf_env/lib/python3.6/site-packages/aiokafka/client.py", line 432, in send
    result = yield from future
  File "/home/ms/anaconda3/envs/tf_env/lib/python3.6/asyncio/tasks.py", line 362, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/ms/anaconda3/envs/tf_env/lib/python3.6/site-packages/mode/worker.py", line 191, in execute_from_commandline
    self.loop.run_until_complete(self.start())
  File "/home/ms/anaconda3/envs/tf_env/lib/python3.6/asyncio/base_events.py", line 468, in run_until_complete
    return future.result()
  File "/home/ms/anaconda3/envs/tf_env/lib/python3.6/site-packages/mode/worker.py", line 243, in start
    await super().start()
  File "/home/ms/anaconda3/envs/tf_env/lib/python3.6/site-packages/mode/services.py", line 706, in start
    await self._default_start()
  File "/home/ms/anaconda3/envs/tf_env/lib/python3.6/site-packages/mode/services.py", line 713, in _default_start
    await self._actually_start()
  File "/home/ms/anaconda3/envs/tf_env/lib/python3.6/site-packages/mode/services.py", line 729, in _actually_start
    await child.maybe_start()
  File "/home/ms/anaconda3/envs/tf_env/lib/python3.6/site-packages/mode/services.py", line 752, in maybe_start
    await self.start()
  File "/home/ms/anaconda3/envs/tf_env/lib/python3.6/site-packages/mode/services.py", line 706, in start
    await self._default_start()
  File "/home/ms/anaconda3/envs/tf_env/lib/python3.6/site-packages/mode/services.py", line 713, in _default_start
    await self._actually_start()
  File "/home/ms/anaconda3/envs/tf_env/lib/python3.6/site-packages/mode/services.py", line 729, in _actually_start
    await child.maybe_start()
  File "/home/ms/anaconda3/envs/tf_env/lib/python3.6/site-packages/mode/services.py", line 752, in maybe_start
    await self.start()
  File "/home/ms/anaconda3/envs/tf_env/lib/python3.6/site-packages/mode/services.py", line 706, in start
    await self._default_start()
  File "/home/ms/anaconda3/envs/tf_env/lib/python3.6/site-packages/mode/services.py", line 713, in _default_start
    await self._actually_start()
  File "/home/ms/anaconda3/envs/tf_env/lib/python3.6/site-packages/mode/services.py", line 724, in _actually_start
    await self.on_start()
  File "/home/ms/anaconda3/envs/tf_env/lib/python3.6/site-packages/faust/assignor/leader_assignor.py", line 20, in on_start
    await leader_topic.maybe_declare()
  File "/home/ms/anaconda3/envs/tf_env/lib/python3.6/site-packages/mode/utils/futures.py", line 36, in __call__
    result = await self.fun(*self.args, **self.kwargs)
  File "/home/ms/anaconda3/envs/tf_env/lib/python3.6/site-packages/faust/topics.py", line 388, in maybe_declare
    await self.declare()
  File "/home/ms/anaconda3/envs/tf_env/lib/python3.6/site-packages/faust/topics.py", line 406, in declare
    retention=self.retention,
  File "/home/ms/anaconda3/envs/tf_env/lib/python3.6/site-packages/faust/transport/drivers/aiokafka.py", line 610, in create_topic
    ensure_created=ensure_created,
  File "/home/ms/anaconda3/envs/tf_env/lib/python3.6/site-packages/faust/transport/drivers/aiokafka.py", line 704, in _create_topic
    await wrap()
  File "/home/ms/anaconda3/envs/tf_env/lib/python3.6/site-packages/mode/utils/futures.py", line 36, in __call__
    result = await self.fun(*self.args, **self.kwargs)
  File "/home/ms/anaconda3/envs/tf_env/lib/python3.6/site-packages/faust/transport/drivers/aiokafka.py", line 754, in _really_create_topic
    timeout=timeout)
  File "/home/ms/anaconda3/envs/tf_env/lib/python3.6/site-packages/faust/transport/drivers/aiokafka.py", line 720, in _get_controller_node
    timeout=timeout,
  File "/home/ms/anaconda3/envs/tf_env/lib/python3.6/site-packages/mode/services.py", line 618, in wait
    return await self._wait_one(coros[0], timeout=timeout)
  File "/home/ms/anaconda3/envs/tf_env/lib/python3.6/site-packages/mode/services.py", line 684, in _wait_one
    results = await self.wait_first(coro, timeout=timeout)
  File "/home/ms/anaconda3/envs/tf_env/lib/python3.6/site-packages/mode/services.py", line 662, in wait_first
    f.result()  # propagate exceptions
  File "/home/ms/anaconda3/envs/tf_env/lib/python3.6/site-packages/aiokafka/client.py", line 439, in send
    raise RequestTimedOutError()
rhkafka.errors.RequestTimedOutError: [Error 7] RequestTimedOutError
[2018-11-26 18:15:34,768: INFO]: [^Worker]: Stopping...
[2018-11-26 18:15:34,769: INFO]: [^-App]: Stopping...
[2018-11-26 18:15:34,769: INFO]: [^-App]: Flush producer buffer...
[2018-11-26 18:15:34,769: INFO]: [^--TableManager]: Stopping...
[2018-11-26 18:15:34,770: INFO]: [^--Fetcher]: Stopping...
[2018-11-26 18:15:34,770: INFO]: [^--Fetcher]: -Stopped!
[2018-11-26 18:15:34,771: INFO]: [^--TableManager]: -Stopped!
[2018-11-26 18:15:34,771: INFO]: [^--Conductor]: Stopping...
[2018-11-26 18:15:34,771: INFO]: [^--Conductor]: -Stopped!
[2018-11-26 18:15:34,772: INFO]: [^AgentManager]: Stopping...
[2018-11-26 18:15:34,772: INFO]: [^Agent: stream_process.process]: Stopping...
[2018-11-26 18:15:34,773: INFO]: [^Agent: stream_process.process]: -Stopped!
[2018-11-26 18:15:34,773: INFO]: [^AgentManager]: -Stopped!
[2018-11-26 18:15:34,773: INFO]: [^--ReplyConsumer]: Stopping...
[2018-11-26 18:15:34,774: INFO]: [^--ReplyConsumer]: -Stopped!
[2018-11-26 18:15:34,774: INFO]: [^--LeaderAssignor]: Stopping...
[2018-11-26 18:15:34,774: INFO]: [^--LeaderAssignor]: -Stopped!
[2018-11-26 18:15:34,775: INFO]: [^--Consumer]: Stopping...
[2018-11-26 18:15:34,779: INFO]: [^--Consumer]: -Stopped!
[2018-11-26 18:15:34,780: INFO]: [^--Producer]: Stopping...
[2018-11-26 18:15:34,781: INFO]: [^--Producer]: -Stopped!
[2018-11-26 18:15:34,782: INFO]: [^Web]: Stopping...
[2018-11-26 18:15:34,782: INFO]: [^-ServerThread]: Stopping...
[2018-11-26 18:15:34,783: INFO]: [^Web]: Closing server
[2018-11-26 18:15:34,784: INFO]: [^Web]: Waiting for server to close handle
[2018-11-26 18:15:34,784: INFO]: [^Web]: Shutting down web application
[2018-11-26 18:15:34,784: INFO]: [^Web]: Waiting for handler to shut down
[2018-11-26 18:15:34,785: INFO]: [^Web]: Cleanup
[2018-11-26 18:15:34,785: INFO]: [^-ServerThread]: -Stopped!
[2018-11-26 18:15:34,786: INFO]: [^Web]: -Stopped!
[2018-11-26 18:15:34,786: INFO]: [^CacheBackend]: Stopping...
[2018-11-26 18:15:34,786: INFO]: [^CacheBackend]: -Stopped!
[2018-11-26 18:15:34,787: INFO]: [^--Monitor]: Stopping...
[2018-11-26 18:15:34,788: INFO]: [^--Monitor]: -Stopped!
[2018-11-26 18:15:34,788: INFO]: [^-App]: -Stopped!
[2018-11-26 18:15:34,789: INFO]: [^Worker]: -Stopped!
[2018-11-26 18:15:34,789: INFO]: [^Worker]: Gathering service tasks...
[2018-11-26 18:15:34,790: INFO]: [^Worker]: Gathering all futures...
[2018-11-26 18:15:35,892: INFO]: [^Worker]: Closing event loop

```
# Versions

* Python version - 3.6
* Faust version - 1.3.2
* Operating system - ubuntu 16.04
* Kafka version - kafka_2.11-0.9.0.0
* RocksDB version (if applicable)

**Comment by ask** [comment]
Does the Kafka logs say anything?  Looks like it has difficulty communicating with Kafka

**Comment by learnermaxRL** [comment]
ERROR Processor got uncaught exception. (kafka.network.Processor)
java.lang.ArrayIndexOutOfBoundsException: 18
	at org.apache.kafka.common.protocol.ApiKeys.forId(ApiKeys.java:68)
	at org.apache.kafka.common.requests.AbstractRequest.getRequest(AbstractRequest.java:39)
	at kafka.network.RequestChannel$Request.<init>(RequestChannel.scala:79)
	at kafka.network.Processor$$anonfun$run$11.apply(SocketServer.scala:426)
	at kafka.network.Processor$$anonfun$run$11.apply(SocketServer.scala:421)
	at scala.collection.Iterator$class.foreach(Iterator.scala:742)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1194)
	at scala.collection.IterableLike$class.foreach(IterableLike.scala:72)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:54)
	at kafka.network.Processor.run(SocketServer.scala:421)
	at java.lang.Thread.run(Thread.java:748)

Do you think its due to some version mismatch?

**Comment by learnermaxRL** [comment]
Solved by switching to - kafka_2.11-0.9.0.0

**Comment by rwhitten577** [comment]
@learnermaxRL what were you on before? Your OP also says kafka_2.11-0.9.0.0. Having this issue connecting to our dev broker that is on kafka_2.11-0.9.0.1.

**Comment by learnermaxRL** [comment]
Aplogies for the wrong version. Please use kafka_2.11-2.1.0 binary version.It should work
