### ISSUE TITLE
Starting a worker without Kafka

### ISSUE THREAD

**Issue by devchakraborty** [robinhood/faust#234]
Is there a way to start a worker without needing it to bootstrap with Kafka? Basically I'd like to be able to run a worker that doesn't do anything with Kafka, but uses channels directly (and maybe other transports I implement). A simple example that I'd like to work is the following:

```python
import faust

app = faust.App('test_app')

channel = app.channel(value_type=str)

@app.timer(interval=1)
async def publish():
    await channel.put('test')

@app.agent(channel)
async def channel_log(stream):
    async for message in stream:
        print(message)

if __name__ == "__main__":
    app.main()
```

**Comment by ask** [comment]
You can do this in the latest version:

```py

import faust
from faust.app.base import BootStrategy
class App(faust.App):

    class BootStrategy(BootStrategy):
         enable_kafka = False


app = App('test_app')
```

**Comment by zibuyu1995** [comment]
@ask  'BootStrategy' is not declared in __all__

**Comment by zibuyu1995** [comment]
@ask if ``` enable_kafka = False ```  run faust  error:

###  code:
```python
import faust
from faust.app.base import BootStrategy
class App(faust.App):

    class BootStrategy(BootStrategy):
         enable_kafka = False

app = App('test_app') 

faust -A app worker -l info
```

### error mssage:
```json
Traceback (most recent call last):
  File "/Users/taodekun/.virtualenvs/actorcloud-backend-50a8KvmJ/lib/python3.6/site-packages/mode/worker.py", line 219, in execute_from_commandline
    self.loop.run_until_complete(self._starting_fut)
  File "uvloop/loop.pyx", line 1446, in uvloop.loop.Loop.run_until_complete
  File "/Users/taodekun/.virtualenvs/actorcloud-backend-50a8KvmJ/lib/python3.6/site-packages/mode/worker.py", line 280, in start
    await super().start()
  File "/Users/taodekun/.virtualenvs/actorcloud-backend-50a8KvmJ/lib/python3.6/site-packages/mode/services.py", line 706, in start
    await self._default_start()
  File "/Users/taodekun/.virtualenvs/actorcloud-backend-50a8KvmJ/lib/python3.6/site-packages/mode/services.py", line 713, in _default_start
    await self._actually_start()
  File "/Users/taodekun/.virtualenvs/actorcloud-backend-50a8KvmJ/lib/python3.6/site-packages/mode/services.py", line 732, in _actually_start
    await child.maybe_start()
  File "/Users/taodekun/.virtualenvs/actorcloud-backend-50a8KvmJ/lib/python3.6/site-packages/mode/services.py", line 758, in maybe_start
    await self.start()
  File "/Users/taodekun/.virtualenvs/actorcloud-backend-50a8KvmJ/lib/python3.6/site-packages/mode/services.py", line 706, in start
    await self._default_start()
  File "/Users/taodekun/.virtualenvs/actorcloud-backend-50a8KvmJ/lib/python3.6/site-packages/mode/services.py", line 713, in _default_start
    await self._actually_start()
  File "/Users/taodekun/.virtualenvs/actorcloud-backend-50a8KvmJ/lib/python3.6/site-packages/mode/services.py", line 732, in _actually_start
    await child.maybe_start()
  File "/Users/taodekun/.virtualenvs/actorcloud-backend-50a8KvmJ/lib/python3.6/site-packages/mode/services.py", line 758, in maybe_start
    await self.start()
  File "/Users/taodekun/.virtualenvs/actorcloud-backend-50a8KvmJ/lib/python3.6/site-packages/mode/services.py", line 706, in start
    await self._default_start()
  File "/Users/taodekun/.virtualenvs/actorcloud-backend-50a8KvmJ/lib/python3.6/site-packages/mode/services.py", line 713, in _default_start
    await self._actually_start()
  File "/Users/taodekun/.virtualenvs/actorcloud-backend-50a8KvmJ/lib/python3.6/site-packages/mode/services.py", line 725, in _actually_start
    await self.on_start()
  File "/Users/taodekun/.virtualenvs/actorcloud-backend-50a8KvmJ/lib/python3.6/site-packages/faust/tables/manager.py", line 74, in on_start
    await self._update_channels()
  File "/Users/taodekun/.virtualenvs/actorcloud-backend-50a8KvmJ/lib/python3.6/site-packages/faust/tables/manager.py", line 86, in _update_channels
    tp for tp in self.app.consumer.assignment()
  File "/Users/taodekun/.virtualenvs/actorcloud-backend-50a8KvmJ/lib/python3.6/site-packages/faust/transport/drivers/aiokafka.py", line 543, in assignment
    return self._thread.assignment()
  File "/Users/taodekun/.virtualenvs/actorcloud-backend-50a8KvmJ/lib/python3.6/site-packages/faust/transport/drivers/aiokafka.py", line 660, in assignment
    return cast(Set[TP], self._ensure_consumer().assignment())
  File "/Users/taodekun/.virtualenvs/actorcloud-backend-50a8KvmJ/lib/python3.6/site-packages/faust/transport/drivers/aiokafka.py", line 681, in _ensure_consumer
    raise ConsumerNotStarted('Consumer thread not yet started')
faust.exceptions.ConsumerNotStarted: Consumer thread not yet started
```

**Comment by groundnuty** [comment]
The above example still produces exactly the same `error: Consumer thread not yet started`  error in fast 1.5.2 (pull request #278 is included in that release)

**Comment by SaschaSchlemmer** [comment]
I just tried the example above and the error `Consumer thread not yet started` still occurs (1.9.0). Any reason in particular this issue has been closed?

**Comment by allisonwang** [comment]
Maybe try
```python
import faust
from faust.app.base import BootStrategy

class App(faust.App):

    producer_only = True

    class BootStrategy(BootStrategy):
        enable_kafka = False

app = App('test_app') 
```
