### ISSUE TITLE
Logger setup in worker initialization is breaking 

### ISSUE THREAD

**Issue by anomit** [robinhood/faust#244]
I have a pretty straight forward code base currently. Just playing around trying to build a prototype of a websocket server that consumes from kafka streams and pushes relevant data out.

I took the approach of initing the faust.Worker from within the code base by scheduling it to be run in the asyncio event loop. This is the general structure:

```pytb
async def start_faust_worker(worker: faust.Worker):
    print('Starting faust worker...')
    await worker.start()

if __name__ == '__main__':
    ev_loop = asyncio.get_event_loop()
    faust_worker = faust.Worker(app=app, loop=ev_loop)
    ev_loop.run_until_complete(start_faust_worker(faust_worker))
    try:
        ev_loop.run_forever()
    finally:
        faust_worker.stop_and_shutdown()

```

```pytb
Starting faust worker...
Traceback (most recent call last):
  File "proto-vanilla.py", line 88, in <module>
    ev_loop.run_until_complete(start_faust_worker(faust_worker))
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "proto-vanilla.py", line 83, in start_faust_worker
    await worker.start()
  File "/Users/anomit/.venv-py3/lib/python3.6/site-packages/mode/worker.py", line 280, in start
    await super().start()
  File "/Users/anomit/.venv-py3/lib/python3.6/site-packages/mode/services.py", line 706, in start
    await self._default_start()
  File "/Users/anomit/.venv-py3/lib/python3.6/site-packages/mode/services.py", line 713, in _default_start
    await self._actually_start()
  File "/Users/anomit/.venv-py3/lib/python3.6/site-packages/mode/services.py", line 720, in _actually_start
    await self.on_first_start()
  File "/Users/anomit/.venv-py3/lib/python3.6/site-packages/faust/worker.py", line 242, in on_first_start
    await self.default_on_first_start()
  File "/Users/anomit/.venv-py3/lib/python3.6/site-packages/mode/worker.py", line 132, in default_on_first_start
    self._setup_logging()
  File "/Users/anomit/.venv-py3/lib/python3.6/site-packages/mode/worker.py", line 158, in _setup_logging
    self.on_setup_root_logger(_logging.root, _loglevel)
  File "/Users/anomit/.venv-py3/lib/python3.6/site-packages/faust/worker.py", line 282, in on_setup_root_logger
    self._setup_spinner_handler(logger, level)
  File "/Users/anomit/.venv-py3/lib/python3.6/site-packages/faust/worker.py", line 291, in _setup_spinner_handler
    logger.handlers[0].setLevel(level)
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 825, in setLevel
    self.level = _checkLevel(level)
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 198, in _checkLevel
    raise TypeError("Level not an integer or a valid string: %r" % level)
TypeError: Level not an integer or a valid string: None
```

Using Python 3.6, faust==1.4.2

**Comment by ask** [comment]
It's currently expecting a loglevel argument to be passed into it:

 faust_worker = faust.Worker(app=app, loop=ev_loop, loglevel="ERROR")

**Comment by anomit** [comment]
That did move things to the next stage, it just has quite a few stumbling blocks with the logging feature IMHO

```pytb
Starting faust worker...
[2018-12-21 13:15:52,375: ERROR]: Task exception was never retrieved
future: <Task finished coro=<start_faust_worker() done, defined at proto-vanilla.py:81> exception=UnicodeEncodeError('ascii', 'starting\u27a2 ', 8, 9, 'ordinal not in range(128)')>
Traceback (most recent call last):
  File "proto-vanilla.py", line 83, in start_faust_worker
    await worker.start()
  File "/Users/anomit/.venv-py3/lib/python3.6/site-packages/mode/worker.py", line 280, in start
    await super().start()
  File "/Users/anomit/.venv-py3/lib/python3.6/site-packages/mode/services.py", line 706, in start
    await self._default_start()
  File "/Users/anomit/.venv-py3/lib/python3.6/site-packages/mode/services.py", line 713, in _default_start
    await self._actually_start()
  File "/Users/anomit/.venv-py3/lib/python3.6/site-packages/mode/services.py", line 720, in _actually_start
    await self.on_first_start()
  File "/Users/anomit/.venv-py3/lib/python3.6/site-packages/faust/worker.py", line 242, in on_first_start
    await self.default_on_first_start()
  File "/Users/anomit/.venv-py3/lib/python3.6/site-packages/mode/worker.py", line 133, in default_on_first_start
    await self.on_execute()
  File "/Users/anomit/.venv-py3/lib/python3.6/site-packages/faust/worker.py", line 269, in on_execute
    self._say('starting\u27a2 ', end='', flush=True)
  File "/Users/anomit/.venv-py3/lib/python3.6/site-packages/mode/worker.py", line 123, in _say
    print(msg, file=file, end=end, **kwargs)  # noqa: T003
UnicodeEncodeError: 'ascii' codec can't encode character '\u27a2' in position 8: ordinal not in range(128)
[2018-12-21 13:15:52,381: ERROR]: Exception in default exception handler
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 1290, in call_exception_handler
    self.default_exception_handler(context)
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 1265, in default_exception_handler
    logger.error('\n'.join(log_lines), exc_info=exc_info)
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1335, in error
    self._log(ERROR, msg, args, **kwargs)
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1442, in _log
    self.handle(record)
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1452, in handle
    self.callHandlers(record)
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 1514, in callHandlers
    hdlr.handle(record)
  File "/usr/local/Cellar/python3/3.6.4/Frameworks/Python.framework/Versions/3.6/lib/python3.6/logging/__init__.py", line 863, in handle
    self.emit(record)
  File "/Users/anomit/.venv-py3/lib/python3.6/site-packages/faust/utils/terminal/spinners.py", line 106, in emit
    self.spinner.update()
  File "/Users/anomit/.venv-py3/lib/python3.6/site-packages/faust/utils/terminal/spinners.py", line 59, in update
    self.write(self.sprites[i])
  File "/Users/anomit/.venv-py3/lib/python3.6/site-packages/faust/utils/terminal/spinners.py", line 70, in write
    self._print(f'{self.bell * self.width}{s.ljust(self.width)}')
  File "/Users/anomit/.venv-py3/lib/python3.6/site-packages/faust/utils/terminal/spinners.py", line 74, in _print
    print(s, end='', file=self.file)
UnicodeEncodeError: 'ascii' codec can't encode character '\u25dc' in position 0: ordinal not in range(128)
```
