### ISSUE TITLE
Autodiscover=True triggers exceptions while scanning the code

### ISSUE THREAD

**Issue by thibserot** [robinhood/faust#247]
## Checklist

- [*] I have included information about relevant versions
- [*] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

When playing with the Django example (the modified version with PR #246 as I can't make the provided example work out of the box with gevent), if I try to install some third party packages like django-extensions or socialauth, the worker won't be able to start with some random errors.

For example with [django-extensions](https://django-extensions.readthedocs.io/en/latest/index.html), you issue:
`pip install django-extensions`
and add in the INSTALLED_APPS section 'django_extensions'

When running the worker:
`proj-faust worker -l info`

You'll get the following error:

```> proj-faust worker -l info
/home/thibanir/.virtualenvs/faust36/lib/python3.6/site-packages/faust-1.4.2-py3.6.egg/faust/fixups/django.py:51: UserWarning: Using settings.DEBUG leads to a memory leak, never
use this setting in production environments!

  warnings.warn(WARN_DEBUG_ENABLED)
Traceback (most recent call last):
  File "/home/thibanir/.virtualenvs/faust36/lib/python3.6/site-packages/django_extensions/db/fields/encrypted.py", line 12, in <module>
    from keyczar import keyczar
ModuleNotFoundError: No module named 'keyczar'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/thibanir/.virtualenvs/faust36/bin/proj-faust", line 11, in <module>
    load_entry_point('proj', 'console_scripts', 'proj-faust')()
  File "/home/thibanir/.virtualenvs/faust36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/thibanir/.virtualenvs/faust36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/home/thibanir/.virtualenvs/faust36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/home/thibanir/.virtualenvs/faust36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/thibanir/Project/faust/examples/django/faustapp/__main__.py", line 2, in <module>
    app.main()  # start entrypoint for :program:`faust`
  File "/home/thibanir/.virtualenvs/faust36/lib/python3.6/site-packages/faust-1.4.2-py3.6.egg/faust/app/base.py", line 649, in main
    self.discover()
  File "/home/thibanir/.virtualenvs/faust36/lib/python3.6/site-packages/faust-1.4.2-py3.6.egg/faust/app/base.py", line 620, in discover
    categories=tuple(categories),
  File "/home/thibanir/.virtualenvs/faust36/lib/python3.6/site-packages/venusian-1.1.0-py3.6.egg/venusian/__init__.py", line 230, in scan
    __import__(modname)
  File "/home/thibanir/.virtualenvs/faust36/lib/python3.6/site-packages/django_extensions/db/fields/encrypted.py", line 14, in <module>
    raise ImportError('Using an encrypted field requires the Keyczar module. '
ImportError: Using an encrypted field requires the Keyczar module. You can obtain Keyczar from http://www.keyczar.org/.
```

I can provide another example with socialauth if needed.

My guess is that when venusian tries to discover all the decorators it will load classes that were supposed to be lazy loaded only when needed and this cause the exception.

An even simpler reproducer:
Create a file dummy.py inside the account app and put the following in it:
`raise ImportError("This is just a test")`

It's important to note that dummy.py is imported nowhere in the code!!!
And here is what you get when trying to start the worker (To be noted that runserver will work fine)
```proj-faust worker -l info
/home/thibanir/.virtualenvs/faust36/lib/python3.6/site-packages/faust-1.4.2-py3.6.egg/faust/fixups/django.py:51: UserWarning: Using settings.DEBUG leads to a memory leak, never
use this setting in production environments!

  warnings.warn(WARN_DEBUG_ENABLED)
Traceback (most recent call last):
  File "/home/thibanir/.virtualenvs/faust36/bin/proj-faust", line 11, in <module>
    load_entry_point('proj', 'console_scripts', 'proj-faust')()
  File "/home/thibanir/.virtualenvs/faust36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 487, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/home/thibanir/.virtualenvs/faust36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2728, in load_entry_point
    return ep.load()
  File "/home/thibanir/.virtualenvs/faust36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2346, in load
    return self.resolve()
  File "/home/thibanir/.virtualenvs/faust36/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2352, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/home/thibanir/Project/faust/examples/django/faustapp/__main__.py", line 2, in <module>
    app.main()  # start entrypoint for :program:`faust`
  File "/home/thibanir/.virtualenvs/faust36/lib/python3.6/site-packages/faust-1.4.2-py3.6.egg/faust/app/base.py", line 649, in main
    self.discover()
  File "/home/thibanir/.virtualenvs/faust36/lib/python3.6/site-packages/faust-1.4.2-py3.6.egg/faust/app/base.py", line 620, in discover
    categories=tuple(categories),
  File "/home/thibanir/.virtualenvs/faust36/lib/python3.6/site-packages/venusian-1.1.0-py3.6.egg/venusian/__init__.py", line 230, in scan
    __import__(modname)
  File "/home/thibanir/Project/faust/examples/django/accounts/dummy.py", line 2, in <module>
    raise ImportError("This is just a test")
ImportError: This is just a test
```

## Expected behavior

I would expect the discover=True to register all tags it finds but to never throw an error if it encounters some exceptions while parsing the code

## Actual behavior

An exception was thrown

## Full traceback

See above

# Versions

* Python version: 3.6
* Faust version: 1.4.2
* Operating system: Ubuntu 16.04
* Kafka version: kafka_2.12-2.1.0
* RocksDB version (if applicable): N/A
* Venusian 1.1.0

**Comment by thibserot** [comment]
After looking more in depth in the venusia documentation; I found out the onerror and ignore options for the scanner that allows to mitigate the problem.
The onerror callback isn't available in the discover function....should it be?
The ignore callback isn't available in the constructor of app (you need to explicitely call the app.discover(ignore=ignore_pattern)

Should we push back those options as part of the App constructor? I can submit a PR if that's ok with you

**Comment by thibserot** [comment]
Actually I tried to use onerror and ignore and never managed to have the auto discover working...
I keep getting errors like django.core.exceptions.appregistrynotready: apps aren't loaded yet. and if I disable it and trigger the discover in the __main__ section, I get two different instance of app and so it doesn't works...

**Comment by ask** [comment]
venusian is a very brute force kind of approach, it recursively imports packages and that may not work for all frameworks.

For Django we should at least wait until `django.setup()`/etc.. is called before doing autodiscovery.

**Comment by thibserot** [comment]
Agreed, but using the decorator @app.discover I can't ensure that the django.setup has been run already

**Comment by thibserot** [comment]
thank you for the fix!

**Comment by divyamamgai** [comment]
Can we add an **exclude list** for autodiscovery? I'm having issues with certain packages, there are lot of error logs on startup which I would rather not have.
