### ISSUE TITLE
Faust --debug crashes with aiomonitor v0.4.0 and Python 3.6

### ISSUE THREAD

**Issue by nemosupremo** [robinhood/faust#263]
## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

1. Install aiomonitor v0.4.0 with Python 3.6
2. Start a faust worker with `--debug`

## Expected behavior

Faust worker starts with debug mode with aiomonitoring

## Actual behavior

Faust worker crashes

## Full traceback

```pytb
Error: RuntimeError('This event loop is already running',)
Traceback (most recent call last):
  File "/Users/nimi/.pyenv/versions/3.6.3/lib/python3.6/site-packages/mode/worker.py", line 219, in execute_from_commandline
    self.loop.run_until_complete(self._starting_fut)
  File "/Users/nimi/.pyenv/versions/3.6.3/lib/python3.6/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/Users/nimi/.pyenv/versions/3.6.3/lib/python3.6/site-packages/mode/worker.py", line 280, in start
    await super().start()
  File "/Users/nimi/.pyenv/versions/3.6.3/lib/python3.6/site-packages/mode/services.py", line 706, in start
    await self._default_start()
  File "/Users/nimi/.pyenv/versions/3.6.3/lib/python3.6/site-packages/mode/services.py", line 713, in _default_start
    await self._actually_start()
  File "/Users/nimi/.pyenv/versions/3.6.3/lib/python3.6/site-packages/mode/services.py", line 720, in _actually_start
    await self.on_first_start()
  File "/Users/nimi/.pyenv/versions/3.6.3/lib/python3.6/site-packages/faust/worker.py", line 242, in on_first_start
    await self.default_on_first_start()
  File "/Users/nimi/.pyenv/versions/3.6.3/lib/python3.6/site-packages/mode/worker.py", line 135, in default_on_first_start
    await self._add_monitor()
  File "/Users/nimi/.pyenv/versions/3.6.3/lib/python3.6/site-packages/mode/worker.py", line 292, in _add_monitor
    loop=self.loop,
  File "/Users/nimi/.pyenv/versions/3.6.3/lib/python3.6/site-packages/aiomonitor/monitor.py", line 411, in start_monitor
    m.start()
  File "/Users/nimi/.pyenv/versions/3.6.3/lib/python3.6/site-packages/aiomonitor/monitor.py", line 112, in start
    self._host, self._console_port, self._locals, self._loop)
  File "/Users/nimi/.pyenv/versions/3.6.3/lib/python3.6/site-packages/aiomonitor/utils.py", line 73, in init_console_server
    server = loop.run_until_complete(coro)  # type: Server
  File "/Users/nimi/.pyenv/versions/3.6.3/lib/python3.6/asyncio/base_events.py", line 454, in run_until_complete
    self.run_forever()
  File "/Users/nimi/.pyenv/versions/3.6.3/lib/python3.6/asyncio/base_events.py", line 408, in run_forever
    raise RuntimeError('This event loop is already running')
RuntimeError: This event loop is already running
```

# Versions

* **Python version** 3.6.7
* **Faust version** 1.4.2
* **Operating system** OS X 10.3.6
* **Kafka version** n/a
* **RocksDB version (if applicable)** n/a

**Comment by Atreus-Technologies** [comment]
I get the same issue on Python 3.7.1 and Faust 1.4.5.

**Comment by ask** [comment]
Looks like it works fine in aiomonitor==0.4.4
