### ISSUE TITLE
Neither faust[gevent] or faust[eventlet] work with Python 3.7

### ISSUE THREAD

**Issue by arel** [robinhood/faust#272]
## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

I have been trying to integrate faust with a flask app, and following the documentation (https://faust.readthedocs.io/en/latest/faq.html) I have tried both `aioeventlet` and `aiogevent` integrations. Both libraries fail.

Attempting to install `pip install faust[gevent]` fails completely (the project seems to have been removed from PyPI) #182.
```
Collecting aiogevent
  Could not find a version that satisfies the requirement aiogevent (from versions: )
No matching distribution found for aiogevent
```

So I tried `pip install faust[eventlet]`, which also fails with a Syntax error at import time (with Python 3.7).

```
In [1]: import aioeventlet                                                                                                                   
Traceback (most recent call last):

  File "/home/ubuntu/.local/share/virtualenvs/b-YiSOAUOy/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-1-ebb10c4f53e9>", line 1, in <module>
    import aioeventlet

  File "/home/ubuntu/.local/share/virtualenvs/b-YiSOAUOy/lib/python3.7/site-packages/aioeventlet.py", line 332
    future = asyncio.async(future, loop=loop)
                         ^
SyntaxError: invalid syntax
```

I'm new to `asyncio` so I'm finding it confusing to integrate faust with flask, and it would be helpful to update the documentation to provide a working example, or at least convey the limitations of these libraries with Python 3.7.

## Expected behavior

I would expect the examples and references in the documentation to work on Python 3.7.

# Versions

* Python version 3.7
* Faust version 1.4.2
* Operating system: Ubuntu 16.04
* Kafka version: n/a
* RocksDB version n/a

**Comment by stevanmilic** [comment]
`async` and `await` are reserved keywords in Python 3.7, thus the error. I suggest using [sync_to_async ](https://github.com/django/asgiref/blob/master/asgiref/sync.py#L104) that Andrew wrote.

**Comment by gitavi** [comment]
So if using `eventlet` with `Flask`, is doing something like this:
```python
async def func():
    await sync_to_async(faust_agent.send)(...)
```
and running the faust worker with ` faust -L eventlet -A myproj worker -l info` what you mean? An example would really be appreciated thanks!

**Comment by stevanmilic** [comment]
1. You don't need `eventlet` loop
2. `faust_agent.send` is already using async library, so no need to _port_ it


Example:
```python
@app.agent()
async def add_account(accounts: StreamT[AccountRecord]):
    async for account in accounts:
        await create_account(account)


@sync_to_async
def create_account(account: AccountRecord):
    Account.objects.create(
        name=account.name,
        score=Decimal(str(account.score)),
        active=account.active,
    )
```
`create_account` function is decorated with `sync_to_async`, but you could use `await sync_to_async(...)(...)` syntax too.


Check Andrew's [blog post](https://www.aeracode.org/2018/02/19/python-async-simplified/) for more info, especially _Sync From Async_ section.

**Comment by lsabi** [comment]
@arel now `pip3 install faust[eventlet]` works, while faust[gevent] does not.

Also, do you have a working example of how you did it? I'm having some hard times understanding how to use both flask and faust together.

Thanks

**Comment by arel** [comment]
Thanks, @lsabi. I don't have a working example; I ended up not using flask and faust together, but I would still like to see a working example if anyone else has one.

**Comment by lsabi** [comment]
The same from my side. I started using faust as standalone server (which, I have to say, is not bad), but I agree about the example of faust + flask.

Or even in the most general case, a working example on how to use faust[gevent] / faust[eventlet] outside django (which is different from other frameworks such as flask)

**Comment by yeralin** [comment]
Hey @ask any ideas on this?

I'm also trying to integrate faust as a module to my aiohttp server. Tried using `aioeventlet`, but now it throws:
```
future = asyncio.async(future, loop=loop)
                         ^
SyntaxError: invalid syntax
```
`python==3.7.5`

**Comment by m3nd1s** [comment]
Is there any word on this? I am trying to run the simplest greeting example in **Quickstart** with faust[eventlet] and starting the worker with `-L eventlet`. I am running the example with a docker image built from python:3.7-latest and the worker fails with `File "/usr/local/lib/python3.7/site-packages/aioeventlet.py", line 332
    future = asyncio.async(future, loop=loop)
                         ^
SyntaxError: invalid syntax`

**Comment by lightoyou** [comment]
Up on this : File "/usr/local/lib/python3.7/site-packages/aioeventlet.py", line 332 future = asyncio.async(future, loop=loop) ^ SyntaxError: invalid syntax

**Comment by lightoyou** [comment]
Who can help me to fix ?

**Comment by rotten** [comment]
I noticed when I hover over the "asyncio" word in the latest FAQ it says `(in Python 3.9)` .  Does this mean it only works with a version of Python that is still in development?

**Comment by dzlabs** [comment]
also an issue for us

**Comment by iXioN** [comment]
As I can see there are still no fix on that, 
I'm trying to fix this since 2 days and still without any result. 

My final use case will be to `my_topic.send()` from django but I still can do it properly because I get or FuturMessage or some kind of promise. Even when I try t use the `my_topic.send_soon()` which seems to do what I'm trying to do.

Does anyone already sent value in a topic from a Django app here ?

**Comment by mashkovd** [comment]
thx for [post](https://github.com/robinhood/faust/issues/272#issuecomment-498020307)
follow working example
```
import faust
from faust.types import StreamT
from faustapp.app import app
from .models import Account
from asgiref.sync import sync_to_async


class AccountRecord(faust.Record):
    name: str
    score: float
    active: bool


@app.agent()
async def add_account(accounts: StreamT[AccountRecord]):
    async for account in accounts:
        await create_account(account)


@sync_to_async
def create_account(account):
    result = Account.objects.create(
        name=account.get('name'),
        score=Decimal(str(account.get('score'))),
        active=0)
    return result.pk


@app.agent()
async def disable_account(account_ids: StreamT[int]):
    async for account_id in account_ids:
        account = Account.objects.get(pk=account_id)
        account.active = False
        account.save()
        yield account.active
```

**Comment by rotten** [comment]
FWIW, we switched to the faust-streaming fork and haven't looked back:  https://github.com/faust-streaming/faust
