### ISSUE TITLE
In-memory transport is broken

### ISSUE THREAD

**Issue by mwolting** [robinhood/faust#295]
## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

Run a Faust worker (e.g. examples/hello_world.py) with `memory://` as the broker URL.

## Expected behavior

The code runs as expected.

## Actual behavior

The program crashes on consumer startup due to missing implementations for several abstract methods

## Full traceback

```pytb
 Error: TypeError("Can't instantiate abstract class Consumer with abstract methods resume_flow, seek_wait, stop_flow, topic_partitions")
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mode/worker.py", line 219, in execute_from_commandline
    self.loop.run_until_complete(self._starting_fut)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/site-packages/mode/worker.py", line 280, in start
    await super().start()
  File "/usr/local/lib/python3.7/site-packages/mode/services.py", line 706, in start
    await self._default_start()
  File "/usr/local/lib/python3.7/site-packages/mode/services.py", line 713, in _default_start
    await self._actually_start()
  File "/usr/local/lib/python3.7/site-packages/mode/services.py", line 732, in _actually_start
    await child.maybe_start()
  File "/usr/local/lib/python3.7/site-packages/mode/services.py", line 758, in maybe_start
    await self.start()
  File "/usr/local/lib/python3.7/site-packages/mode/services.py", line 706, in start
    await self._default_start()
  File "/usr/local/lib/python3.7/site-packages/mode/services.py", line 713, in _default_start
    await self._actually_start()
  File "/usr/local/lib/python3.7/site-packages/mode/services.py", line 719, in _actually_start
    self._children.extend(self.on_init_dependencies())
  File "/usr/local/lib/python3.7/site-packages/faust/app/base.py", line 490, in on_init_dependencies
    return self.boot_strategy.server()
  File "/usr/local/lib/python3.7/site-packages/faust/app/base.py", line 230, in server
    self.kafka_consumer(),
  File "/usr/local/lib/python3.7/site-packages/faust/app/base.py", line 274, in kafka_consumer
    self.app.consumer,
  File "/usr/local/lib/python3.7/site-packages/faust/app/base.py", line 1440, in consumer
    self._consumer = self._new_consumer()
  File "/usr/local/lib/python3.7/site-packages/faust/app/base.py", line 1315, in _new_consumer
    beacon=self.beacon,
  File "/usr/local/lib/python3.7/site-packages/faust/transport/base.py", line 68, in create_consumer
    return self.Consumer(self, callback=callback, loop=self.loop, **kwargs)
  File "/usr/local/lib/python3.7/typing.py", line 811, in __new__
    obj = super().__new__(cls)
TypeError: Can't instantiate abstract class Consumer with abstract methods resume_flow, seek_wait, stop_flow, topic_partitions
```

# Versions

* Python version: 3.7.2
* Faust version: 1.4.6, 1.5.0b1
* Operating system: Debian Stretch
* Kafka version: N/A
* RocksDB version (if applicable): N/A

**Comment by ask** [comment]
Thanks!

I think this is something we started to write for testing purposes, but not sure there is any
practical uses for it.

Maybe we should just remove it

**Comment by ask** [comment]
The memory transport was removed!
