### ISSUE TITLE
Faust hangs when deleting key from table [BUG]

### ISSUE THREAD

**Issue by axsauze** [robinhood/faust#311]
# Overview

When deleting to a table using `del table[key]` or `table.pop(key)` Faust hangs. This is an attempt to tackle #310. It was attempted both with Table and SetTable, and both hang. The content of the string is a medium-sized json, but I tried it with short strings as well and it also hangs. (Also not sure if related but #176 may be relevant).

# Code example

``` python
app = faust.App("stream-processor", 
    broker="kafka://...", 
    key_serializer="json",
    topic_partitions=3)

stream_topic = app.topic("stream_topic")

table = app.Table("bulk_table", value_type=str, partitions=3)

def do_something_with_relevant_values(curr_keys, table):
    pass

@app.timer(10.0)
async def bulk_process_stream():
    # Key to filter out everything after the last minute
    minute_key_str = (datetime.now() - timedelta(minute=1))
        .strftime('%Y-%m-%dT%H:%M')
    # Get keys older than 1 minute
    curr_keys = [key for key in table.keys() if key < minute_key_str]
    do_something_with_relevant_values(curr_keys, table)
    # Attempt to delete all keys
    for key in curr_keys:
        # Here is where it just hangs
        del table[key]
        # Running table.pop(key) instead also hangs

# Topic that adds stream topics to table
@app.agent(stream_topic)
async def process_stream(stream):
    # key is str, val is json
    async for key, val in stream.items():
        created_date_str = val["created_date"]
        date_minute_key = created_date_str[:15] # Up to minute for key
        table[date_minute_key + "-" + str(key)] = json.dumps(val)
```

# Versions

* Python version 3.6.7
* Faust version 1.4.7
* Operating system: Ubuntu 18.04.
* Kafka version 2.1.1

**Comment by ask** [comment]
It's not hanging for me, but I was also not expecting that to happen. What I expected to happen
was for the table operation to raise an error:

```
[^-App]: Crashed reason=TypeError('Deleting table key from outside of stream iteration')
Traceback (most recent call last):
  File "/opt/devel/mode/mode/services.py", line 762, in _execute_task
    await task
  File "/opt/devel/faust/faust/app/base.py", line 892, in _wrapped
    return await task()
  File "/opt/devel/faust/faust/app/base.py", line 941, in around_timer
    await fun(*args)  # type: ignore
  File "examples/i311.py", line 24, in bulk_process_stream
    del table[key]
  File "/opt/devel/mode/mode/utils/collections.py", line 509, in __delitem__
    self.on_key_del(key)
  File "/opt/devel/faust/faust/tables/table.py", line 87, in on_key_del
    'Deleting table key from outside of stream iteration')
TypeError: Deleting table key from outside of stream iteration
```

Our rule has been that you are not allowed to modify the table outside of stream processing,
but in this case I think it should be OK to delete keys.

What is the use case here?
I'm not sure I understand what the purpose of this code is.

If you want to filter out keys that are older than a minute, then this is not filtering: you are deleting them.
