### ISSUE TITLE
pytest fail on 1.5+ with concurrency

### ISSUE THREAD

**Issue by DeoLeung** [robinhood/faust#322]
## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

my last pytest failed with 
```bash
pyfuncitem = <Function test_process_message>

    @pytest.mark.tryfirst
    def pytest_pyfunc_call(pyfuncitem):
        """
        Run asyncio marked test functions in an event loop instead of a normal
        function call.
        """
        for marker_name, fixture_name in _markers_2_fixtures.items():
            if marker_name in pyfuncitem.keywords \
                    and not getattr(pyfuncitem.obj, 'is_hypothesis_test', False):
                event_loop = pyfuncitem.funcargs[fixture_name]

                funcargs = pyfuncitem.funcargs
                testargs = {arg: funcargs[arg]
                            for arg in pyfuncitem._fixtureinfo.argnames}

                event_loop.run_until_complete(
                    asyncio.ensure_future(
>                       pyfuncitem.obj(**testargs), loop=event_loop))

/usr/local/lib/python3.7/site-packages/pytest_asyncio/plugin.py:158:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <_UnixSelectorEventLoop running=False closed=False debug=False>, future = <Task cancelled coro=<test_process_message() done, defined at /tmp/test/streams/slack_test.py:17>>

    def run_until_complete(self, future):
        """Run until the Future is done.

        If the argument is a coroutine, it is wrapped in a Task.

        WARNING: It would be disastrous to call run_until_complete()
        with the same coroutine twice -- it would wrap it in two
        different Tasks and that can't be good.

        Return the Future's result, or raise its exception.
        """
        self._check_closed()

        new_task = not futures.isfuture(future)
        future = tasks.ensure_future(future, loop=self)
        if new_task:
            # An exception is raised if the future didn't complete, so there
            # is no need to log the "destroy pending task" message
            future._log_destroy_pending = False

        future.add_done_callback(_run_until_complete_cb)
        try:
            self.run_forever()
        except:
            if new_task and future.done() and not future.cancelled():
                # The coroutine raised a BaseException. Consume the exception
                # to not log a warning, the caller doesn't have access to the
                # local task.
                future.exception()
            raise
        finally:
            future.remove_done_callback(_run_until_complete_cb)
        if not future.done():
            raise RuntimeError('Event loop stopped before Future completed.')

>       return future.result()
E       concurrent.futures._base.CancelledError

/usr/local/lib/python3.7/asyncio/base_events.py:584: CancelledError
```

## Expected behavior

It works on 1.4.9, failing with 1.5.1

## Actual behavior

Tell us what happened instead.

## Full traceback

```pytb
Paste the full traceback (if there is any)
```

# Versions

* Python version: 3.7.2
* Faust version: 1.5.1
* Operating system
* Kafka version
* RocksDB version (if applicable)

the error is not obvious to me, will research further later

**Comment by ask** [comment]
Is this your own test suite, or the Faust test suite?  What is the test doing?  I imagine there could be a case where we used to silence CancelledError that is now propagating it, but would need to know what the code is doing.

**Comment by DeoLeung** [comment]
it's just one of my specific tests, I tried to reproduce with a minimal step but it works...so far I can't post the origin code , is there a way to check which `Future` cause the `CancelledError`?

**Comment by DeoLeung** [comment]
@ask 
after doing some binary search finally I figure out the cause
```python
@app.agent(topic, concurrency=2)
```

if `concurrency` bigger than one, `CancelledError` will raise

I can stick to 1 for testing, but it will better to have a way to test concurrency

**Comment by itsnotapt** [comment]
Not sure if this is related, but the given example for Testing -> Basics produces the same issue (seems to be related to the interaction between `agent.test_context` and `stream.group_by`.

```python
import faust

app = faust.App('test-example')

class Order(faust.Record, serializer='json'):
    account_id: str
    product_id: str
    amount: int
    price: float

orders_topic = app.topic('orders', value_type=Order)
orders_for_account = app.Table('order-count-by-account', default=int)

@app.agent(orders_topic)
async def order_func(orders):
    async for order in orders.group_by(Order.account_id):
        orders_for_account[order.account_id] += 1
        yield order

async def test_order():
    # start and stop the agent in this block
    async with order_func.test_context() as agent:
        order = Order(account_id='1', product_id='2', amount=1, price=300)
        # sent order to the test agents local channel, and wait
        # the agent to process it.
        await agent.put(order)
        # at this point the agent already updated the table
        assert orders_for_account[order.account_id] == 1
        await agent.put(order)
        assert orders_for_account[order.account_id] == 2

async def run_tests():
    app.conf.store = 'memory://'   # tables must be in-memory
    await test_order()

if __name__ == '__main__':
    import asyncio
    loop = asyncio.get_event_loop()
    loop.run_until_complete(run_tests())
```

```
Traceback (most recent call last):
  File "test.py", line 39, in <module>
    loop.run_until_complete(run_tests())
  File "C:\Users\user\Anaconda3\envs\test_faust\lib\asyncio\base_events.py", line 584, in run_until_complete
    return future.result()
concurrent.futures._base.CancelledError
```

Python == `3.7.3`
Faust == `1.5.4`

**Comment by itsnotapt** [comment]
Oddly enough, the following produces the CancelledError when the line for the `orders_for_account` table is commented. But works if the line `orders_for_account` is uncommented.

```python
import faust
import pytest

app = faust.App('test-example')

class Order(faust.Record, serializer='json'):
    account_id: str
    product_id: str
    amount: int
    price: float

orders_topic = app.topic('orders', value_type=Order)
#orders_for_account = app.Table('order-count-by-account', default=int)

@app.agent(orders_topic)
async def order_func(orders):
    async for order in orders.group_by(Order.account_id):
        yield order

@pytest.mark.asyncio()
async def test_order():
    app.conf.store = 'memory://'   # tables must be in-memory
    async with order_func.test_context() as agent:
        order = Order(account_id='1', product_id='2', amount=1, price=300)
        event = await agent.put(order)
        assert agent.results[event.message.offset].account_id == '1'
```

**Comment by ask** [comment]
Thanks everyone!

I managed to reproduce this issue and wrote a fix. Please let me know if it is not working for you!
