### ISSUE TITLE
Can't instantiate abstract class ConfluentConsumerThread with abstract methods key_partition

### ISSUE THREAD

**Issue by andresjaor** [robinhood/faust#329]
## Steps to reproduce
Using confluent broker `broker="confluent://<host:port>` raise `Can't instantiate abstract class ConfluentConsumerThread with abstract methods key_partition` error on staring faust.

It seems that `key_partition` abstract method is not overridden in `ConfluentConsumerThread` class

## Full traceback

```pytb
[^Worker]: Error: TypeError("Can't instantiate abstract class ConfluentConsumerThread with abstract methods key_partition",) 
Traceback (most recent call last):
  File "/Users/andresjaramillo/Documents/ENV/audit-service/lib/python3.6/site-packages/mode/worker.py", line 261, in execute_from_commandline
    self.loop.run_until_complete(self._starting_fut)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/Users/andresjaramillo/Documents/ENV/audit-service/lib/python3.6/site-packages/mode/worker.py", line 326, in start
    await super().start()
  File "/Users/andresjaramillo/Documents/ENV/audit-service/lib/python3.6/site-packages/mode/services.py", line 719, in start
    await self._default_start()
  File "/Users/andresjaramillo/Documents/ENV/audit-service/lib/python3.6/site-packages/mode/services.py", line 726, in _default_start
    await self._actually_start()
  File "/Users/andresjaramillo/Documents/ENV/audit-service/lib/python3.6/site-packages/mode/services.py", line 750, in _actually_start
    await child.maybe_start()
  File "/Users/andresjaramillo/Documents/ENV/audit-service/lib/python3.6/site-packages/mode/services.py", line 776, in maybe_start
    await self.start()
  File "/Users/andresjaramillo/Documents/ENV/audit-service/lib/python3.6/site-packages/mode/services.py", line 719, in start
    await self._default_start()
  File "/Users/andresjaramillo/Documents/ENV/audit-service/lib/python3.6/site-packages/mode/services.py", line 726, in _default_start
    await self._actually_start()
  File "/Users/andresjaramillo/Documents/ENV/audit-service/lib/python3.6/site-packages/mode/services.py", line 732, in _actually_start
    for dep in self.on_init_dependencies():
  File "/Users/andresjaramillo/Documents/ENV/audit-service/lib/python3.6/site-packages/faust/app/base.py", line 522, in on_init_dependencies
    return self.boot_strategy.server()
  File "/Users/andresjaramillo/Documents/ENV/audit-service/lib/python3.6/site-packages/faust/app/base.py", line 258, in server
    self.kafka_consumer(),
  File "/Users/andresjaramillo/Documents/ENV/audit-service/lib/python3.6/site-packages/faust/app/base.py", line 302, in kafka_consumer
    self.app.consumer,
  File "/Users/andresjaramillo/Documents/ENV/audit-service/lib/python3.6/site-packages/faust/app/base.py", line 1594, in consumer
    self._consumer = self._new_consumer()
  File "/Users/andresjaramillo/Documents/ENV/audit-service/lib/python3.6/site-packages/faust/app/base.py", line 1463, in _new_consumer
    beacon=self.beacon,
  File "/Users/andresjaramillo/Documents/ENV/audit-service/lib/python3.6/site-packages/faust/transport/base.py", line 68, in create_consumer
    **kwargs)
  File "/Users/andresjaramillo/Documents/ENV/audit-service/lib/python3.6/site-packages/faust/transport/consumer.py", line 1110, in __init__
    self._thread = self._new_consumer_thread()
  File "/Users/andresjaramillo/Documents/ENV/audit-service/lib/python3.6/site-packages/faust/transport/drivers/confluent.py", line 70, in _new_consumer_thread
    self, loop=self.loop, beacon=self.beacon)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/typing.py", line 1126, in __new__
    return _generic_new(cls.__next_in_mro__, cls, *args, **kwds)
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/typing.py", line 1087, in _generic_new
    return base_cls.__new__(cls)
TypeError: Can't instantiate abstract class ConfluentConsumerThread with abstract methods key_partition

```

# Versions

* Python version 3.6
* Faust version 1.5.3
* Operating system macOS

**Comment by ask** [comment]
The confluent kafka transport is currently experimental and should not be used in production.

If you want to help maintain it you are welcome to implement the missing methods,
but I'm guessing you will want to use the default transport.
