### ISSUE TITLE
Can't run the Django example on latest master

### ISSUE THREAD

**Issue by swist** [robinhood/faust#348]
## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce
Clone the repo then:
```
python setup.py develop
proj-faust -l info
```
## Expected behavior
I expected to get a running faust worker instance

## Actual behavior
The worker fails to boot with the following exception:

## Full traceback

```pytb
Traceback (most recent call last):
  File "/Users/swistak/code/faust/examples/django/bin/proj-faust", line 11, in <module>
    load_entry_point('proj', 'console_scripts', 'proj-faust')()
  File "/Users/swistak/code/faust/examples/django/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/Users/swistak/code/faust/examples/django/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/Users/swistak/code/faust/examples/django/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/Users/swistak/code/faust/examples/django/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/Users/swistak/code/faust/examples/django/faustapp/__main__.py", line 3, in <module>
    app.main()  # start entry point for :program:`faust`
  File "/Users/swistak/code/faust/examples/django/lib/python3.7/site-packages/faust/app/base.py", line 674, in main
    self.discover()
  File "/Users/swistak/code/faust/examples/django/lib/python3.7/site-packages/faust/app/base.py", line 638, in discover
    modules |= set(fixup.autodiscover_modules())
  File "/Users/swistak/code/faust/examples/django/lib/python3.7/site-packages/faust/fixups/django.py", line 66, in autodiscover_modules
    return [config.name for config in self.apps.get_app_configs()]
  File "/Users/swistak/code/faust/examples/django/lib/python3.7/site-packages/django/apps/registry.py", line 144, in get_app_configs
    self.check_apps_ready()
  File "/Users/swistak/code/faust/examples/django/lib/python3.7/site-packages/django/apps/registry.py", line 135, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
```

# Versions

* Python version: 3.7.2
* Faust version: 1.6.1 - 1.7.0a1
* Operating system: OS X 10.14.4
* Kafka version: 0.11
* RocksDB version (if applicable) N/A

**Comment by swist** [comment]
I came across this trying to make a minimal reproducible repository while debugging the same problem running faust inside of an existing project, but with a different invocation: ```faust -A myapp.app worker -l info```
