### ISSUE TITLE
Pytest fails with RuntimeError "<Future pending> attached to a different loop" when "put" more than 2 events

### ISSUE THREAD

**Issue by enkot** [robinhood/faust#350]
## Checklist

- [x] I have included information about relevant versions
- [ ] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

Thx for the great lib! :) But there is a problem, I am trying to test data aggregation into table. 
My app, events grouped by user_id:
```py
def create_app(config = Config()):
    return App(
        'user_events',
        broker=config.CONSUMER_KAFKA_URL,
        store=config.FAUST_STORE_URL
    )

app = create_app()

class Event(Record, serializer='json'):
    user_id: str
    user_data: dict

events_topic = app.topic('events', value_type=Event)
events_by_user = app.Table('events_by_user', default=list)

@app.agent(events_topic)
async def process(events: Stream[Event]) -> None:
    async for event in events.group_by(Event.user_id):
        user_events = events_by_user[event.user_id]
        user_events.append(event)
        events_by_user[event.user_id] = user_events
        yield event
```
Working test:
```py
@pytest.fixture()
def test_app(event_loop):
    app = create_app()
    app.finalize()
    app.conf.store = 'memory://'
    app.flow_control.resume()
    return app

@pytest.mark.asyncio
async def test_process(test_app):
    async with process.test_context() as agent:
        sample1 = Event(user_id='111', user_data={'value': 100})
        await agent.put(sample1)

        sample3 = Event(user_id='111', user_data={'value': 300})
        await agent.put(sample3)

        assert events_by_user['111'] == [sample1, sample3]
```
But when I "put" more than 2 events - it fails. Example:
```py
@pytest.mark.asyncio
async def test_process(test_app):
    async with process.test_context() as agent:
        sample1 = Event(user_id='111', user_data={'value': 100})
        await agent.put(sample1)

        sample2 = Event(user_id='222', user_data={'value': 200})
        await agent.put(sample2)

        sample3 = Event(user_id='111', user_data={'value': 300})
        await agent.put(sample3) # <- fails here

        assert events_by_user['111'] == [sample1, sample3]
        assert events_by_user['222'] == [sample2]
``` 
## Expected behavior

Pytest should pass the test.

## Actual behavior

It throws RuntimeError:
```sh
self = <ThrowableQueue at 0x1234ba518 maxsize=4096 _queue=[<Event: k=None v=<Event: user_id='111', type='EventData', check_data={'screenX': 300}>>] tasks=4>

    async def get(self):
        """Remove and return an item from the queue.
    
        If queue is empty, wait until an item is available.
        """
        while self.empty():
            getter = self._loop.create_future()
            self._getters.append(getter)
            try:
>               await getter
E               RuntimeError: Task <Task pending coro=<Service._execute_task() running at /Users/tarasbatenkov/Projects/s777/engine-ml/venv/lib/python3.7/site-packages/mode/services.py:762> cb=[Service._on_future_done()]> got Future <Future pending> attached to a different loop

/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/queues.py:159: RuntimeError
```

## Full traceback

```pytb
ERROR    faust.agents.actor:logging.py:230 [^--AgentTestWrapper*: app.agents.process]: Crashed reason=RuntimeError('Task <Task pending coro=<Service._execute_task() running at /Users/tarasbatenkov/Projects/s777/engine-ml/venv/lib/python3.7/site-packages/mode/services.py:762> cb=[Service._on_future_done()]> got Future <Future pending> attached to a different loop')
Traceback (most recent call last):
  File "/Users/tarasbatenkov/Projects/s777/engine-ml/venv/lib/python3.7/site-packages/faust/agents/agent.py", line 601, in _execute_task
    await coro
  File "/Users/tarasbatenkov/Projects/s777/engine-ml/venv/lib/python3.7/site-packages/faust/agents/agent.py", line 618, in _slurp
    async for value in it:
  File "/Users/tarasbatenkov/Projects/s777/engine-ml/app/agents.py", line 11, in process
    async for event in events.group_by(Event.user_id):
  File "/Users/tarasbatenkov/Projects/s777/engine-ml/venv/lib/python3.7/site-packages/faust/streams.py", line 805, in _py_aiter
    raise chan_errors.popleft()
  File "/Users/tarasbatenkov/Projects/s777/engine-ml/venv/lib/python3.7/site-packages/faust/streams.py", line 456, in _passive_drainer
    async for item in self:  # pragma: no cover
  File "/Users/tarasbatenkov/Projects/s777/engine-ml/venv/lib/python3.7/site-packages/faust/streams.py", line 807, in _py_aiter
    channel_value = await chan_slow_get()
  File "/Users/tarasbatenkov/Projects/s777/engine-ml/venv/lib/python3.7/site-packages/faust/channels.py", line 327, in __anext__
    return await self.queue.get()
  File "/Users/tarasbatenkov/Projects/s777/engine-ml/venv/lib/python3.7/site-packages/mode/utils/queues.py", line 128, in get
    return await super().get()
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/queues.py", line 159, in get
    await getter
RuntimeError: Task <Task pending coro=<Service._execute_task() running at /Users/tarasbatenkov/Projects/s777/engine-ml/venv/lib/python3.7/site-packages/mode/services.py:762> cb=[Service._on_future_done()]> got Future <Future pending> attached to a different loop
```

# Versions

* Python version - 3.7.2
* Faust version - 1.6.0 (with 1.6.1 have this issue - #346)
* Operating system - macOS Mojave, 10.14.4
* Kafka version - NA
* RocksDB version (if applicable) - NA

**Comment by nickraptis** [comment]
Hello, I'm a different developer trying to adopt to faust, so I did a little digging into this issue.

I was able to reproduce it, using the master branches for both faust and pytest-asyncio
To reproduce the test, I used https://github.com/robinhood/faust/blob/master/t/docs/testing/test_figC_windowed_table.py , adding 3 put calls instead of the one in the test.

Removing the groupby makes the test pass, that may hint into where a new loop gets introduced.

This seems to be a problem coming from pytest-asyncio and how they set up the loop fixture through a policy. https://github.com/pytest-dev/pytest-asyncio/blob/master/pytest_asyncio/plugin.py
The non pytest-async example https://faust.readthedocs.io/en/latest/userguide/testing.html#id1 does not have this issue with multiple puts, even though it has a groupby.

Digging into pytest-asyncio 's backlog https://github.com/pytest-dev/pytest-asyncio/issues?utf8=%E2%9C%93&q=is%3Aissue+attached+to+a+different+loop suggests they are open to working with async frameworks to solve these kinds of issues.
Maybe faust should open a ticket with them and work from there.

**Comment by wowpoppy** [comment]
It happens to me as well with more than two `agent.put(event)` calls in a single test
