### ISSUE TITLE
Permission Denied for creating data directory

### ISSUE THREAD

**Issue by milankaku** [robinhood/faust#380]
## Checklist

- [X ] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

I am currently trying to deploy a faust worker to Kubernetes. Here is my Dockerfile:
`# Using lightweight alpine image
FROM python:3.6-alpine

# Installing packages
RUN apk update
RUN apk add --no-cache curl python3 pkgconfig snappy-dev python3-dev g++ gcc libxml2-dev libxslt-dev openssl-dev libffi-dev musl-dev make gcc

# Defining working directory and adding source code
WORKDIR /usr
COPY requirements.txt ./
COPY src ./src
COPY schemas ./schemas

# Install API dependencies
RUN pip3 install -r requirements.txt

RUN chmod -R 755 .

WORKDIR /usr/src

CMD faust -A producer -l info worker`

## Expected behavior

I expect the worker to run as it does locally

## Actual behavior

This is the error I am getting in Kubernetes logs for this pod:
`+ƒaµS† v1.7.0-+------------------------------------------------+
| id          | producer                                       |
| transport   | [URL('kafka://ovp.com:9093')]     |
| store       | memory:                                        |
| web         | http://localhost:6066/                         |
| log         | -stderr- (info)                                |
| pid         | 1                                              |
| hostname    | faust-demo-producer-master-28-7bdbc9f9f6-qxbh5 |
| platform    | CPython 3.6.8 (Linux x86_64)                   |
| drivers     |                                                |
|   transport | aiokafka=1.0.3                                 |
|   web       | aiohttp=3.5.4                                  |
| datadir     | /usr/src/producer-data                         |
| appdir      | /usr/src/producer-data/v1                      |
+-------------+------------------------------------------------+
[2019-07-08 21:08:38,677: INFO]: [^Worker]: Starting...
[2019-07-08 21:08:38,684: ERROR]: [^Worker]: Error: PermissionError(13, 'Permission denied')
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mode/worker.py", line 264, in execute_from_commandline
    self.loop.run_until_complete(self._starting_fut)
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 719, in start
    await self._default_start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 726, in _default_start
    await self._actually_start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 750, in _actually_start
    await child.maybe_start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 778, in maybe_start
    await self.start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 719, in start
    await self._default_start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 726, in _default_start
    await self._actually_start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 734, in _actually_start
    await self.on_first_start()
  File "/usr/local/lib/python3.6/site-packages/faust/app/base.py", line 562, in on_first_start
    self._create_directories()
  File "/usr/local/lib/python3.6/site-packages/faust/app/base.py", line 1607, in _create_directories
    self.conf.datadir.mkdir(exist_ok=True)
  File "/usr/local/lib/python3.6/pathlib.py", line 1248, in mkdir
    self._accessor.mkdir(self, mode)
  File "/usr/local/lib/python3.6/pathlib.py", line 387, in wrapped
    return strfunc(str(pathobj), *args)
PermissionError: [Errno 13] Permission denied: 'producer-data'`

Any ideas on why I continue to get this error? I have tried variations on the Dockerfile, such as creating the producer-data directory before hand but I am still getting the same error

# Versions

* Python version
* Faust version
* Operating system
* Kafka version
* RocksDB version (if applicable)

**Comment by milankaku** [comment]
Closed, was issue with permissions on Dockerfile

**Comment by anilgaddamatbell** [comment]
I am running into the same issue. Would you remember what change did you make in your docker file?
