### ISSUE TITLE
AttributeError: 'faust.transport._cython.conductor.ConductorHandler' object has no attribute 'wait_until_producer_ebb'

### ISSUE THREAD

**Issue by ritvikgautam** [robinhood/faust#388]
## Checklist

- [x] I have included information about relevant versions
- [ ] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

I'm trying to run the full example given [here](https://faust.readthedocs.io/en/latest/userguide/agents.html) in the docs.

1. Create a `main.py` file with the example code. 
2. Run it: `faust -A main worker -l info` 

## Expected behavior

The application should start and listen to the input kafka topic for records.

## Actual behavior

The application crashes while starting. Trace below.

## Full traceback

```pytb
Crashed reason=AttributeError("'faust.transport._cython.conductor.ConductorHandler' object has no attribute 'wait_until_producer_ebb'")
Traceback (most recent call last):
  File "/Users/ritvik/.local/share/virtualenvs/faust-o7o3ulFq/lib/python3.7/site-packages/faust/app/base.py", line 1535, in _on_partitions_assigned
    await T(self.topics.on_partitions_assigned)(assigned)
  File "/Users/ritvik/.local/share/virtualenvs/faust-o7o3ulFq/lib/python3.7/site-packages/faust/utils/tracing.py", line 121, in corowrapped
    await_ret = await ret
  File "/Users/ritvik/.local/share/virtualenvs/faust-o7o3ulFq/lib/python3.7/site-packages/faust/transport/conductor.py", line 287, in on_partitions_assigned
    T(self._update_callback_map)()
  File "/Users/ritvik/.local/share/virtualenvs/faust-o7o3ulFq/lib/python3.7/site-packages/faust/utils/tracing.py", line 86, in _inner
    child, fun, callback, *args, **kwargs)
  File "/Users/ritvik/.local/share/virtualenvs/faust-o7o3ulFq/lib/python3.7/site-packages/faust/utils/tracing.py", line 110, in call_with_trace
    ret = fun(*args, **kwargs)
  File "/Users/ritvik/.local/share/virtualenvs/faust-o7o3ulFq/lib/python3.7/site-packages/faust/transport/conductor.py", line 317, in _update_callback_map
    for tp, channels in self._tp_index.items()
  File "/Users/ritvik/.local/share/virtualenvs/faust-o7o3ulFq/lib/python3.7/site-packages/faust/transport/conductor.py", line 317, in <genexpr>
    for tp, channels in self._tp_index.items()
  File "/Users/ritvik/.local/share/virtualenvs/faust-o7o3ulFq/lib/python3.7/site-packages/faust/transport/conductor.py", line 324, in _build_handler
    return ConductorHandler(self, tp, channels)
  File "faust/transport/_cython/conductor.pyx", line 28, in faust.transport._cython.conductor.ConductorHandler.__init__
AttributeError: 'faust.transport._cython.conductor.ConductorHandler' object has no attribute 'wait_until_producer_ebb'
```

# Versions

* Python version: 3.7.3
* Faust version: 1.7.3
* Operating system: macOS 10.14.5
* Kafka version: 2.2.1
* RocksDB version (if applicable)

**Comment by ritvikgautam** [comment]
Fixed on faust 1.7.4. Thanks for the quick patch!
