### ISSUE TITLE
Regression: custom coercions crash when used with typing.Optional

### ISSUE THREAD

**Issue by yungchin** [robinhood/faust#393]
## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

Here's the script I used to `git bisect` this:

```python
from typing import Optional
from uuid import UUID, uuid4

import faust


class X(faust.Record, coercions={UUID: UUID}):
    uid: Optional[UUID]


x = X(uuid4())
print("yay we didn't crash")
```

## Expected behavior

This used to work fine, we could instantiate a record as expected.

## Actual behavior

As of commit 5ec28de9d4d29ce102defddb8ea426f06016bbbf and up to and including master, this raises an exception when instantiating `X`.

## Full traceback

```pytb
Traceback (most recent call last):
  File "debug_coercions.py", line 11, in <module>
    x = X(uuid4())
  File "<string>", line 3, in __init__
  File "/Users/yungchin/src/faust/faust/models/record.py", line 514, in _init_field
    value = initfun(value)
  File "/Users/yungchin/src/faust/faust/models/record.py", line 320, in _init_maybe_coerce
    if isinstance(value, typ):
  File "/nix/store/x56821haw51fxp0rli8bjkbkhak2nxls-python3-3.7.2/lib/python3.7/typing.py", line 708, in __instancecheck__                                                                                                                   
    return self.__subclasscheck__(type(obj))
  File "/nix/store/x56821haw51fxp0rli8bjkbkhak2nxls-python3-3.7.2/lib/python3.7/typing.py", line 716, in __subclasscheck__                                                                                                                   
    raise TypeError("Subscripted generics cannot be used with"
TypeError: Subscripted generics cannot be used with class and instance checks
```

# Versions

* Python version 3.7.2
* Faust version 1.7.4
* Operating system MacOS 10.14.5

**Comment by yungchin** [comment]
There's potentially more to this, but I haven't managed to boil that one down to a simple test case yet (this is just a snippet out of our pytest output):

```
    self = typing.Union[datetime.datetime, NoneType], cls = <class 'datetime.datetime'>
    
        def __subclasscheck__(self, cls):
            if self._special:
                if not isinstance(cls, _GenericAlias):
                    return issubclass(cls, self.__origin__)
                if cls._special:
                    return issubclass(cls.__origin__, self.__origin__)
    >       raise TypeError("Subscripted generics cannot be used with"
                            " class and instance checks")
    E       TypeError: Subscripted generics cannot be used with class and instance checks
    
    /nix/store/x56821haw51fxp0rli8bjkbkhak2nxls-python3-3.7.2/lib/python3.7/typing.py:716: TypeError
```
... which suggests it doesn't necessarily play nice with `Optional[datetime]` either. But this is from a horrendous record definition with a bunch of inheritance, and I need to figure out how to get a simple test case out of it. In any case: git-bisect points to the same commit as above for this one.

**Comment by martinmaillard** [comment]
Here is a simple test case:
```python
class X(faust.Record, coercions={str: str}):
    y: Optional[str]

x = X(y='test')
```
Raises: `TypeError: Subscripted generics cannot be used with class and instance checks`

**Comment by martinmaillard** [comment]
This is now fixed in master :)

**Comment by yungchin** [comment]
Works great, many thanks for this!
