### ISSUE TITLE
Faust worker crashes when it fails to create assignor leader topic

### ISSUE THREAD

**Issue by bvarghese1** [robinhood/faust#400]
## Steps to reproduce

Started seeing this error after upgrading faust version to 1.7.1
This happens intermittently.

## Expected behavior

Application retries to create the assignor leader topic

## Actual behavior

Application worker crashes

## Full traceback

```pytb
[2019-08-09 18:08:21,830: ERROR]: [^Worker]: Error: RequestTimedOutError('Cannot create topic: extractor-__assignor-__leader (7): None')
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/mode/worker.py", line 264, in execute_from_commandline
    self.loop.run_until_complete(self._starting_fut)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.7/site-packages/mode/services.py", line 719, in start
    await self._default_start()
  File "/usr/local/lib/python3.7/site-packages/mode/services.py", line 726, in _default_start
    await self._actually_start()
  File "/usr/local/lib/python3.7/site-packages/mode/services.py", line 750, in _actually_start
    await child.maybe_start()
  File "/usr/local/lib/python3.7/site-packages/mode/services.py", line 778, in maybe_start
    await self.start()
  File "/usr/local/lib/python3.7/site-packages/mode/services.py", line 719, in start
    await self._default_start()
  File "/usr/local/lib/python3.7/site-packages/mode/services.py", line 726, in _default_start
    await self._actually_start()
  File "/usr/local/lib/python3.7/site-packages/mode/services.py", line 750, in _actually_start
    await child.maybe_start()
  File "/usr/local/lib/python3.7/site-packages/mode/services.py", line 778, in maybe_start
    await self.start()
  File "/usr/local/lib/python3.7/site-packages/mode/services.py", line 719, in start
    await self._default_start()
  File "/usr/local/lib/python3.7/site-packages/mode/services.py", line 726, in _default_start
    await self._actually_start()
  File "/usr/local/lib/python3.7/site-packages/mode/services.py", line 743, in _actually_start
    await self.on_start()
  File "/usr/local/lib/python3.7/site-packages/faust/assignor/leader_assignor.py", line 20, in on_start
    await self._enable_leader_topic()
  File "/usr/local/lib/python3.7/site-packages/faust/assignor/leader_assignor.py", line 24, in _enable_leader_topic
    await leader_topic.maybe_declare()
  File "/usr/local/lib/python3.7/site-packages/mode/utils/futures.py", line 54, in __call__
    result = await self.fun(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/faust/topics.py", line 499, in maybe_declare
    await self.declare()
  File "/usr/local/lib/python3.7/site-packages/faust/topics.py", line 519, in declare
    retention=self.retention,
  File "/usr/local/lib/python3.7/site-packages/faust/transport/drivers/aiokafka.py", line 635, in create_topic
    ensure_created=ensure_created,
  File "/usr/local/lib/python3.7/site-packages/faust/transport/drivers/aiokafka.py", line 791, in _create_topic
    await wrap()
  File "/usr/local/lib/python3.7/site-packages/mode/utils/futures.py", line 54, in __call__
    result = await self.fun(*self.args, **self.kwargs)
  File "/usr/local/lib/python3.7/site-packages/faust/transport/drivers/aiokafka.py", line 880, in _really_create_topic
    f'Cannot create topic: {topic} ({code}): {reason}')
kafka.errors.RequestTimedOutError: [Error 7] RequestTimedOutError: Cannot create topic: extractor-__assignor-__leader (7): None
```

# Versions

* Python version - 3.6
* Faust version - 1.7.1
* Operating system - Debian GNU/Linux 9 (stretch)
* Kafka version - 2.1
  * aiokafka - 1.0.3

**Comment by ask** [comment]
So I guess we should retry this operation?

**Comment by bvarghese1** [comment]
@ask Retry would make sense. How does faust behave when the worker crashes for any other reason?
