### ISSUE TITLE
Can't create custom but optional Fields

### ISSUE THREAD

**Issue by guhcampos** [robinhood/faust#430]
## Steps to reproduce

I'm trying to use the custom field approach for field validation in Faust Models, but I can't seem to build a valid syntax. I'm not sure if I'm doing something wrong or maybe this is actually a bug.

I have a model with a custom field such as 
```python
class DatalivePersonRecord(faust.Record, validation=True):
    gender: str = ChoiceField(["F", "M", "N", ""])
 ```

But then the model's init complains with: `TypeError: __init__() missing 1 required positional argument: 'gender'`.

I tried several other syntax approaches such as:

```python
    gender: str = Optional[GenderField()]
```

Without much success. 

## Expected behavior

I wanted to have field validation set for optional fields. Validation should then pass for a valid present field and ignore an absent field. Validation should fail by present fields which did not
pass the validation.

## Actual behavior

Errors mentioned above.

## Full traceback

```pytb
[2019-09-22 22:43:39,486: INFO]: Timer Monitor.sampler woke up too late, with a drift of +0.43837748800069676 
[2019-09-22 22:43:39,521: ERROR]: [^---Agent*: ingest.rec[.]ingest_record_agent]: Crashed reason=TypeError("__init__() missing 1 required positional argument: 'gender'") 
Traceback (most recent call last):
  File "/home/gustavo/.local/share/virtualenvs/ingest-EalAiwRa/lib/python3.7/site-packages/faust/agents/agent.py", line 625, in _execute_task
    await coro
  File "/home/gustavo/workspace/maio/services/ingest/ingest/records/agents.py", line 34, in ingest_record_agent
    person_record = DatalivePersonRecord(business_unit=record.business_unit)
TypeError: __init__() missing 1 required positional argument: 'gender'
```

# Versions

* Python 3.7
* Faust 1.7.4
* Ubuntu 19.04
* Kafka 2.12

**Comment by guhcampos** [comment]
Another failed attempt:

```python
    gender: str = Optional[GenderField(required=False)]
```

yields:

```
  File "ingest/persons/agents.py", line 12, in <module>
    from ingest.persons.models import DatalivePersonRecord
  File "/home/gustavo/workspace/maio/services/ingest/ingest/persons/models.py", line 27, in <module>
    gender: str = Optional[GenderField(required=False)]
  File "/usr/lib/python3.7/typing.py", line 248, in inner
    return cached(*args, **kwds)
  File "/usr/lib/python3.7/typing.py", line 354, in __getitem__
    arg = _type_check(parameters, "Optional[t] requires a single type.")
  File "/usr/lib/python3.7/typing.py", line 139, in _type_check
    raise TypeError(f"{msg} Got {arg!r:.100}.")
  File "/home/gustavo/.local/share/virtualenvs/ingest-EalAiwRa/lib/python3.7/site-packages/faust/models/fields.py", line 215, in __repr__
    return f'<{type(self).__name__}: {self.ident}: {typ}{default}>'
  File "/home/gustavo/.local/share/virtualenvs/ingest-EalAiwRa/lib/python3.7/site-packages/faust/models/fields.py", line 220, in ident
    return f'{self.model.__name__}.{self.field}'
AttributeError: 'NoneType' object has no attribute '__name__'
```

**Comment by ask** [comment]
In this case it must be either:

```py

class DatalivePersonRecord(faust.Record, validation=True):
    gender: str = ChoiceField(["F", "M", "N", ""], required=False)

```

or 

```py

class DatalivePersonRecord(faust.Record, validation=True):
    gender: Optional[str] = ChoiceField(["F", "M", "N", ""])

```

but currently custom fields need to handle optional, so I merged a patch so that is handled by default.

the example does beg the question, what on earth is considered the default gender...

**Comment by guhcampos** [comment]
Thanks for the tips @ask, I'm new to Faust and never really used type annotations in python before, so please forgive the confusion. 

The default handling of optionals will come in handy, which brings me to your question: 

In the particular system I'm working in every single field is optional, but for some reason it was modeled over a SQL columnar database. The default here does not represent the answer someone gave, but rather that the system does not have the information. 

This is actually one of the reasons I chose Faust: I'm turning a traditional CRUD system into an event source, where different events will have only subsets of data and state is constructed by merging multiple events into a single record. Events may even override a previously existing field with the empty state.

(P.S.: the example comes from a clothing store, and the field was previously a bool choice named `sex`, which I'm hoping to improve upon. Every feedback, Faust related or not, is humbly appreciated!)
