### ISSUE TITLE
Fails to create leader topic

### ISSUE THREAD

**Issue by LeonardAukea** [robinhood/faust#443]
## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

I'm running kafka on kubernetes (strimzi) installation with the configuration `topic.auto.create.enable: True`. I'm trying to start a simple faust app but it fails due to `TopicAuthorizationFailedError`: 

```python 
import faust
import ssl
import logging

logging.basicConfig(level=logging.DEBUG)

ssl_context = ssl.create_default_context(
    purpose=ssl.Purpose.SERVER_AUTH, cafile=ssl_cafile)
ssl_context.load_cert_chain(ssl_certfile, 
                            keyfile=ssl_keyfile)

app = faust.App('faust_test', 
                broker=host,  
                broker_credentials=ssl_context,
                value_serializer='raw')


dev_topic = app.topic('dev')

@app.agent(dev_topic)
async def greet(numbers):
    async for n in numbers:
        print(n)
```

## Expected behavior

I expected `faust_test-__assignor-__leader` topic to be created and the application to start

## Actual behavior

faust app does not start due to fails due to `TopicAuthorizationFailedError`. 

## Full traceback

```pytb
[2019-10-09 10:34:10,867: INFO]: [^Worker]: Starting... 
[2019-10-09 10:34:10,870: INFO]: [^-App]: Starting... 
[2019-10-09 10:34:10,870: INFO]: [^--Monitor]: Starting... 
[2019-10-09 10:34:10,870: INFO]: [^--Producer]: Starting... 
[2019-10-09 10:34:12,273: INFO]: [^--CacheBackend]: Starting... 
[2019-10-09 10:34:12,273: INFO]: [^--Web]: Starting... 
[2019-10-09 10:34:12,279: INFO]: [^---Server]: Starting... 
[2019-10-09 10:34:12,280: INFO]: [^--Consumer]: Starting... 
[2019-10-09 10:34:12,280: INFO]: [^---AIOKafkaConsumerThread]: Starting... 
[2019-10-09 10:34:13,872: INFO]: [^--LeaderAssignor]: Starting... 
[2019-10-09 10:34:13,872: INFO]: [^--Producer]: Creating topic 'faust_test-__assignor-__leader' 
[2019-10-09 10:34:14,953: ERROR]: [^Worker]: Error: TopicAuthorizationFailedError('Cannot create topic: faust_test-__assignor-__leader (29): Authorization failed.') 
Traceback (most recent call last):
  File "/Users/laukea/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/mode/worker.py", line 261, in execute_from_commandline
    self.loop.run_until_complete(self._starting_fut)
  File "/Users/laukea/.pyenv/versions/miniconda3-latest/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/Users/laukea/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/mode/worker.py", line 326, in start
    await super().start()
  File "/Users/laukea/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/mode/services.py", line 719, in start
    await self._default_start()
  File "/Users/laukea/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/mode/services.py", line 726, in _default_start
    await self._actually_start()
  File "/Users/laukea/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/mode/services.py", line 750, in _actually_start
    await child.maybe_start()
  File "/Users/laukea/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/mode/services.py", line 776, in maybe_start
    await self.start()
  File "/Users/laukea/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/mode/services.py", line 719, in start
    await self._default_start()
  File "/Users/laukea/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/mode/services.py", line 726, in _default_start
    await self._actually_start()
  File "/Users/laukea/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/mode/services.py", line 750, in _actually_start
    await child.maybe_start()
  File "/Users/laukea/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/mode/services.py", line 776, in maybe_start
    await self.start()
  File "/Users/laukea/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/mode/services.py", line 719, in start
    await self._default_start()
  File "/Users/laukea/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/mode/services.py", line 726, in _default_start
    await self._actually_start()
  File "/Users/laukea/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/mode/services.py", line 743, in _actually_start
    await self.on_start()
  File "/Users/laukea/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/faust/assignor/leader_assignor.py", line 20, in on_start
    await leader_topic.maybe_declare()
  File "/Users/laukea/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/mode/utils/futures.py", line 53, in __call__
    result = await self.fun(*self.args, **self.kwargs)
  File "/Users/laukea/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/faust/topics.py", line 427, in maybe_declare
    await self.declare()
  File "/Users/laukea/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/faust/topics.py", line 446, in declare
    retention=self.retention,
  File "/Users/laukea/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/faust/transport/drivers/aiokafka.py", line 587, in create_topic
    ensure_created=ensure_created,
  File "/Users/laukea/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/faust/transport/drivers/aiokafka.py", line 731, in _create_topic
    await wrap()
  File "/Users/laukea/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/mode/utils/futures.py", line 53, in __call__
    result = await self.fun(*self.args, **self.kwargs)
  File "/Users/laukea/.pyenv/versions/miniconda3-latest/lib/python3.7/site-packages/faust/transport/drivers/aiokafka.py", line 820, in _really_create_topic
    f'Cannot create topic: {topic} ({code}): {reason}')
kafka.errors.TopicAuthorizationFailedError: [Error 29] TopicAuthorizationFailedError: Cannot create topic: faust_test-__assignor-__leader (29): Authorization failed.
[2019-10-09 10:34:14,957: INFO]: [^Worker]: Stopping... 
[2019-10-09 10:34:14,957: INFO]: [^-App]: Stopping... 
[2019-10-09 10:34:14,957: INFO]: [^-App]: Flush producer buffer... 
[2019-10-09 10:34:14,958: INFO]: [^--TableManager]: Stopping... 
[2019-10-09 10:34:14,958: INFO]: [^--Fetcher]: Stopping... 
[2019-10-09 10:34:14,958: INFO]: [^--Conductor]: Stopping... 
[2019-10-09 10:34:14,958: INFO]: [^--AgentManager]: Stopping... 
[2019-10-09 10:34:14,958: INFO]: [^Agent: faust_test.greet]: Stopping... 
[2019-10-09 10:34:14,959: INFO]: [^--ReplyConsumer]: Stopping... 
[2019-10-09 10:34:14,959: INFO]: [^--LeaderAssignor]: Stopping... 
[2019-10-09 10:34:14,959: INFO]: [^--Consumer]: Stopping... 
[2019-10-09 10:34:14,959: INFO]: [^---AIOKafkaConsumerThread]: Stopping... 
[2019-10-09 10:34:15,873: INFO]: [^--Web]: Stopping... 
[2019-10-09 10:34:15,873: INFO]: [^---Server]: Stopping... 
[2019-10-09 10:34:15,874: INFO]: [^--Web]: Cleanup 
[2019-10-09 10:34:15,874: INFO]: [^--CacheBackend]: Stopping... 
[2019-10-09 10:34:15,874: INFO]: [^--Producer]: Stopping... 
[2019-10-09 10:34:15,985: INFO]: [^--Monitor]: Stopping... 
[2019-10-09 10:34:15,986: INFO]: [^Worker]: Gathering service tasks... 
[2019-10-09 10:34:15,986: INFO]: [^Worker]: Gathering all futures... 
[2019-10-09 10:34:16,989: INFO]: [^Worker]: Closing event loop 
```

# Versions

* Python version
* Faust version faust, version Faust 1.6.1
* Operating system kubernetes 
* Kafka version https://strimzi.io/
* RocksDB version (if applicable)

Any help is much appreciated!

**Comment by LeonardAukea** [comment]
In case anyone is trying the same thing the solution is to create a superuser on strimzi for faust to use. 

Set the user as super user:
```
apiVersion: kafka.strimzi.io/v1beta1
kind: Kafka
spec:
  kafka:
    # ...
    authorization:
      type: tls
      superUsers:
        - CN=super-user
    # ...
  zookeeper:
    # ...
```
Create the user with authentication only:
```
apiVersion: kafka.strimzi.io/v1beta1
kind: KafkaUser
metadata:
  name: super-user
  labels:
    strimzi.io/cluster: my-cluster
spec:
  authentication:
    type: tls
```

https://strimzi.io/docs/latest/full.html#super_users

**Comment by LeonardAukea** [comment]
Issue can be closed

**Comment by matthewi** [comment]
Just a note that on Python 3.7, Faust 1.8, and Strimzi 0.14 we did not observe this behavior.
