### ISSUE TITLE
cannot launch example tableofset

### ISSUE THREAD

**Issue by PGDataHome** [robinhood/faust#445]
## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

Tell us what you did to cause something to happen.

## Expected behavior

Tell us what you expected to happen.

## Actual behavior

Tell us what happened instead.

## Full traceback

```pytb
Paste the full traceback (if there is any)
```
faust -A tableofset worker |more
+ƒaµS† v1.7.4-+------------------------------------------------------------------------------------+
| id          | table-of-sets-windowed-v2                                                          |
| transport   | [URL('kafka://localhost:9092')]                                                    |
| store       | memory:                                                                            |
| web         | http://localhost:6066/                                                             |
| log         | -stderr- (warn)                                                                    |
| pid         | 22478                                                                              |
| hostname    | pascal-asus                                                                        |
| platform    | CPython 3.7.3 (Linux x86_64)                                                       |
| drivers     |                                                                                    |
|   transport | aiokafka=1.0.4                                                                     |
|   web       | aiohttp=3.5.4                                                                      |
| datadir     | /home/hadoop/kafka_2.11-2.3.0/faust-master/examples/table-of-sets-windowed-data    |
| appdir      | /home/hadoop/kafka_2.11-2.3.0/faust-master/examples/table-of-sets-windowed-data/v2 |
+-------------+------------------------------------------------------------------------------------+
[2019-10-13 17:29:19,486: ERROR]: [^Worker]: Error: TypeError("Channel must be channel, topic, or str; not <class 'coroutine'>") 
Traceback (most recent call last):
  File "/home/hadoop/.local/lib/python3.7/site-packages/mode/worker.py", line 264, in execute_from_commandline
    self.loop.run_until_complete(self._starting_fut)
  File "/usr/lib/python3.7/asyncio/base_events.py", line 584, in run_until_complete
    return future.result()
  File "/home/hadoop/.local/lib/python3.7/site-packages/mode/services.py", line 719, in start
    await self._default_start()
  File "/home/hadoop/.local/lib/python3.7/site-packages/mode/services.py", line 726, in _default_start
    await self._actually_start()
  File "/home/hadoop/.local/lib/python3.7/site-packages/mode/services.py", line 750, in _actually_start
    await child.maybe_start()
  File "/home/hadoop/.local/lib/python3.7/site-packages/mode/services.py", line 778, in maybe_start
    await self.start()
  File "/home/hadoop/.local/lib/python3.7/site-packages/mode/services.py", line 719, in start
    await self._default_start()
  File "/home/hadoop/.local/lib/python3.7/site-packages/mode/services.py", line 726, in _default_start
    await self._actually_start()
  File "/home/hadoop/.local/lib/python3.7/site-packages/mode/services.py", line 750, in _actually_start
    await child.maybe_start()
  File "/home/hadoop/.local/lib/python3.7/site-packages/mode/services.py", line 778, in maybe_start
    await self.start()
  File "/home/hadoop/.local/lib/python3.7/site-packages/mode/services.py", line 719, in start
    await self._default_start()
  File "/home/hadoop/.local/lib/python3.7/site-packages/mode/services.py", line 726, in _default_start
    await self._actually_start()
  File "/home/hadoop/.local/lib/python3.7/site-packages/mode/services.py", line 743, in _actually_start
    await self.on_start()
  File "/usr/local/lib/python3.7/dist-packages/faust/agents/manager.py", line 31, in on_start
    self.update_topic_index()
  File "/usr/local/lib/python3.7/dist-packages/faust/agents/manager.py", line 64, in update_topic_index
    for topic in agent.get_topic_names():
  File "/usr/local/lib/python3.7/dist-packages/faust/agents/agent.py", line 965, in get_topic_names
    channel = self.channel
  File "/usr/local/lib/python3.7/dist-packages/faust/agents/agent.py", line 978, in channel
    **self._channel_kwargs,
  File "/usr/local/lib/python3.7/dist-packages/faust/agents/agent.py", line 488, in _prepare_channel
    f'Channel must be channel, topic, or str; not {type(channel)}')
TypeError: Channel must be channel, topic, or str; not <class 'coroutine'>

# Versions

* Python version 2.7.16 3.7.3
* Faust version 1.7.4
* Operating system ubuntu 19.04
* Kafka version 2.11-2.3.0
* RocksDB version (if applicable)

**Comment by PGDataHome** [comment]
I tried install v180, but unforyunately the same applies

**Comment by fr-ser** [comment]
First of all: I mean no disrespect, but the formatting of your question is horrible (use backticks for the logs for example). Also, you didn't delete the boilerplate and did not post anything but the changelogs and the versions...

But, I tried to run the tableofset exmaple and it worked for me. You can find a reproducible repo here: https://github.com/fr-ser/faust-bugs/tree/master/tableofset_issue_445

If you still have trouble, please reformat your original question, add some info to your setup or check out my repo and tell me what does not work.

**Comment by PGDataHome** [comment]
Hello, 
I was and am not aware of what you ment.
ionned that annoyed you.
But what i have put in the yiicket is not a log trace, but only the command issued, and its outout

And also, I havetried running this example, with new 181 version, and (at least for mr ...), it doesn't function, but final message of the output trace has changed .

So here I give the command issued,  and its trace outpput :

--------------------------- BEGIN TRACE --------------------------
pipenv run faust -A tableofset joining here sergej
Traceback (most recent call last):
  File "/usr/local/bin/faust", line 11, in <module>
    load_entry_point('faust==1.8.1', 'console_scripts', 'faust')()
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 716, in main
    with self.make_context(prog_name, args, **extra) as ctx:
  File "/usr/local/lib/python3.7/dist-packages/faust-1.8.1-py3.7-linux-x86_64.egg/faust/cli/base.py", line 401, in make_context
    self._maybe_import_app()
  File "/usr/local/lib/python3.7/dist-packages/faust-1.8.1-py3.7-linux-x86_64.egg/faust/cli/base.py", line 366, in _maybe_import_app
    find_app(appstr)
  File "/usr/local/lib/python3.7/dist-packages/faust-1.8.1-py3.7-linux-x86_64.egg/faust/cli/base.py", line 293, in find_app
    val = symbol_by_name(app, imp=imp)
  File "/usr/local/lib/python3.7/dist-packages/mode-4.1.2-py3.7.egg/mode/utils/imports.py", line 201, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/mode-4.1.2-py3.7.egg/mode/utils/imports.py", line 305, in import_from_cwd
    return imp(module, package=package)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tableofset'
----------------------------------- END TRACE -----------------------------------------

Sorry for annoyance

**Comment by fr-ser** [comment]
Did you check out my repo and try it?
Your stack trace shows you using 1.8.1 (I haven't tried that version)

Other than than that the stacktrace just looks to me, like your file (tableofset) is named differently or you are in the wrong folder...

**Comment by PGDataHome** [comment]
yes I checked, but I do/didn-t know/find ant difference

**Comment by PGDataHome** [comment]
Ok, i'm not used with pipenv and all that  stuff so tried to reproduce as
you did, but that"s not very successful

I tried to runit in the right place . Here's the trace,

---------------------------------------------

hadoop@pascal-asus:~/kafka/faust-master$ faust -A tableofset
Traceback (most recent call last):
  File "/usr/local/bin/faust", line 11, in <module>
    load_entry_point('faust==1.8.1', 'console_scripts', 'faust')()
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 764, in
__call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/click/core.py", line 716, in
main
    with self.make_context(prog_name, args, **extra) as ctx:
  File
"/usr/local/lib/python3.7/dist-packages/faust-1.8.1-py3.7-linux-x86_64.egg/faust/cli/base.py",
line 401, in make_context
    self._maybe_import_app()
  File
"/usr/local/lib/python3.7/dist-packages/faust-1.8.1-py3.7-linux-x86_64.egg/faust/cli/base.py",
line 366, in _maybe_import_app
    find_app(appstr)
  File
"/usr/local/lib/python3.7/dist-packages/faust-1.8.1-py3.7-linux-x86_64.egg/faust/cli/base.py",
line 293, in find_app
    val = symbol_by_name(app, imp=imp)
  File
"/usr/local/lib/python3.7/dist-packages/mode-4.1.2-py3.7.egg/mode/utils/imports.py",
line 201, in symbol_by_name
    module = imp(module_name, package=package, **kwargs)
  File
"/usr/local/lib/python3.7/dist-packages/mode-4.1.2-py3.7.egg/mode/utils/imports.py",
line 305, in import_from_cwd
    return imp(module, package=package)
  File "/usr/lib/python3.7/importlib/__init__.py", line 127, in
import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'tableofset'
hadoop@pascal-asus:~/kafka/faust-master$

--------------------------------------------------------------------------------

Le dim. 20 oct. 2019 à 08:37, Sergej Herbert <notifications@github.com> a
écrit :

**Comment by fr-ser** [comment]
Ok, since the example works for me there is nothing else I can do unless you provide some way to reproduce the issue (e.g. a repo)

**Comment by PGDataHome** [comment]
Ok
Could you tell how I can provide you with a repo

Le dim. 20 oct. 2019 à 08:57, Sergej Herbert <notifications@github.com> a
écrit :

**Comment by fr-ser** [comment]
Create a new public repo on github and create a minimal, locally running application there, which produces the error (pretty much the same as I did with my repo)

**Comment by PGDataHome** [comment]
https://github.com/fr-ser/faust-bugs/issues/1

**Comment by ask** [comment]
This doesn't seem like an issue anymore, but feel free to reopen.

Note: when running this from the faust source directory you should use `faust -A examples.tableofset.py`

**Comment by PGDataHome** [comment]
Sorry, but for me, it doesnt function.
I have updated my repo

**Comment by PGDataHome** [comment]
sorry again, but answer from https://github.com/fr-ser/faust-bugs/tree/master/tableofset_issue_445
functions but is only half satisfactory :

ok, it functions, when removing, the maybe-declare

although, it is not completely satisfactory, it could be viewed as a bug in faust, but also it functions without i, it's only a wrap-around to get global-functionning

Now, and it was the reason why I tried to run this example, could you tell me what is wrong in the analytics.py program or else tell me where I could get some help with Faust

I have updated the repo master branch

Thx
