### ISSUE TITLE
Consumer freezes after "Please make sure it's hanging before restart." warning

### ISSUE THREAD

**Issue by pkisztelinski** [robinhood/faust#459]
## Checklist

- [x] I have included information about relevant versions
- [ ] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

not sure how to reproduce yet

## Expected behavior

process messages or restart systemd service

## Actual behavior

I have faust application set as a systemd service, also I use CrashingSupervisor as a supervisor strategy, so systemd service is restarted after every error. however, after several errors and several restarts I get warning: "Please make sure it's hanging before restart." and consumer freezes, does not process messages any more, also does not restart service. 

## Full traceback

```pytb
[22775] [WARNING] [^--Consumer]: Warning: Task timed out!
[22775] [WARNING] [^--Consumer]: Please make sure it's hanging before restart.
```

# Versions

* Python version 3.7.2
* Faust version 1.8.1
* Operating system ubuntu
* Kafka version 2.1.1

**Comment by ask** [comment]
Do you have more context for these logs?

**Comment by chyidl** [comment]
```
[2020-05-27 21:12:25,951] [74331] [WARNING] [^--Consumer]: Warning: Task timed out!
[2020-05-27 21:12:25,952] [74331] [WARNING] [^--Consumer]: Please make sure it's hanging before restart.
[2020-05-27 21:12:25,952] [74331] [INFO] [^--Consumer]: [Flight Recorder-530] (started at Wed May 27 21:07:25 2020) Replaying logs...
[2020-05-27 21:12:25,952] [74331] [INFO] [^--Consumer]: [Flight Recorder-530] (Wed May 27 21:07:25 2020) +consumer.commit()
[2020-05-27 21:12:25,952] [74331] [INFO] [^--Consumer]: [Flight Recorder-530] -End of log-
[2020-05-27 21:12:25,952] [74331] [INFO] [^--Consumer]: [Flight Recorder-530] Task traceback
[2020-05-27 21:12:25,958] [74331] [INFO] [^--Consumer]: Stack for <Task pending coro=<Service._execute_task() running at /Users/yogo/.virtualenvs/sirius/lib/python3.7/site-packages/mode/services.py:779> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x106fb6510>()]> cb=[Service._on_future_done()]> (most recent call last):
  File "/Users/yogo/.virtualenvs/sirius/lib/python3.7/site-packages/mode/services.py", line 779, in _execute_task
    await task
  File "/Users/yogo/.virtualenvs/sirius/lib/python3.7/site-packages/faust/transport/consumer.py", line 783, in _commit_handler
    await self.commit()
  File "/Users/yogo/.virtualenvs/sirius/lib/python3.7/site-packages/faust/transport/consumer.py", line 824, in commit
    start_new_transaction=start_new_transaction,
  File "/Users/yogo/.virtualenvs/sirius/lib/python3.7/site-packages/mode/services.py", line 459, in _and_transition
    return await fun(self, *args, **kwargs)
  File "/Users/yogo/.virtualenvs/sirius/lib/python3.7/site-packages/faust/transport/consumer.py", line 858, in force_commit
    commit_tps, start_new_transaction=start_new_transaction)
  File "/Users/yogo/.virtualenvs/sirius/lib/python3.7/site-packages/faust/transport/consumer.py", line 876, in _commit_tps
    start_new_transaction=start_new_transaction)
  File "/Users/yogo/.virtualenvs/sirius/lib/python3.7/site-packages/faust/transport/consumer.py", line 943, in _commit_offsets
    did_commit = await self._commit(committable_offsets)
  File "/Users/yogo/.virtualenvs/sirius/lib/python3.7/site-packages/faust/transport/consumer.py", line 1311, in _commit
    return await self._thread.commit(offsets)
  File "/Users/yogo/.virtualenvs/sirius/lib/python3.7/site-packages/faust/transport/drivers/aiokafka.py", line 523, in commit
    return await self.call_thread(self._commit, offsets)
  File "/Users/yogo/.virtualenvs/sirius/lib/python3.7/site-packages/mode/threads.py", line 436, in call_thread
    result = await promise
```
> I encountered the same problem, 
```
python version: Python 3.7.7
faust version: faust==1.10.4
```

**Comment by dzlabs** [comment]
Also having this issue, seems to be related to using take `.take(100, within=300)`

**Comment by lachuta** [comment]
Also seeing this error. The consumer crashes with `Crashed reason=RuntimeError('coroutine raised StopIteration')`, the worker start `Stopping...` and 5 minutes later the error on the title shows along with `Warning: Task timed out!`:

```
2022-11-24T00:04:53.529Z nid_martens_sa_stream_processor INFO [request_id={2b6b8e0f-c9e4-4de7-be54-2d25c372dc84} transaction_id={f0dd17f1-66f5-4b78-bbd2-1ff253fbb97d} logger={nid_martens_sa_stream_processor.addr_pair_refresh.agents}] Start processing event KEY: 15088920090919205143
2022-11-24T00:04:53.617Z nid_martens_sa_stream_processor ERROR [logger={mode.threads}] [^-----MethodQueueWorker@0x7f970a4c59d0 index=0]: Crashed reason=RuntimeError('coroutine raised StopIteration')
Traceback (most recent call last):
  File "/opt/abc/nid-martens-sa-stream-processor/releases/20221122T140114/venv/lib64/python3.8/site-packages/mode/threads.py", line 388, in _process_enqueued
    promise._loop.call_soon_threadsafe(
StopIteration: {}

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/abc/nid-martens-sa-stream-processor/releases/20221122T140114/venv/lib64/python3.8/site-packages/mode/services.py", line 779, in _execute_task
    await task
  File "/opt/abc/nid-martens-sa-stream-processor/releases/20221122T140114/venv/lib64/python3.8/site-packages/mode/threads.py", line 310, in _method_queue_do_work
    await process_enqueued(item)
RuntimeError: coroutine raised StopIteration
2022-11-24T00:04:53.628Z nid_martens_sa_stream_processor INFO [request_id={2b6b8e0f-c9e4-4de7-be54-2d25c372dc84} transaction_id={f0dd17f1-66f5-4b78-bbd2-1ff253fbb97d} logger={nid_martens_sa_stream_processor.addr_pair_refresh.agents}] End processing event KEY: 15088920090919205143. Duration: 98 ms
2022-11-24T00:04:53.630Z nid_martens_sa_stream_processor INFO [request_id={07a1090a-ce8e-4901-ba6e-6689e5837e2b} transaction_id={0b18cae0-5c96-4b1f-bc12-1179ee617ca5} logger={nid_martens_sa_stream_processor.addr_pair_refresh.agents}] Start processing event KEY: 23727620090919205143
2022-11-24T00:04:53.633Z nid_martens_sa_stream_processor INFO [logger={aiokafka.consumer.group_coordinator}] LeaveGroup request succeeded
2022-11-24T00:04:53.633Z nid_martens_sa_stream_processor INFO [logger={faust.worker}] [^Worker]: Stopping...
2022-11-24T00:04:53.636Z nid_martens_sa_stream_processor INFO [logger={abc_logging_faust.app}] [^-abcLoggingFaustApp]: Stopping...
2022-11-24T00:04:53.637Z nid_martens_sa_stream_processor INFO [logger={faust.transport.consumer}] [^---Fetcher]: Stopping...
2022-11-24T00:04:53.637Z nid_martens_sa_stream_processor INFO [logger={faust.transport.drivers.aiokafka}] [^--Consumer]: Consumer shutting down for user cancel.
2022-11-24T00:04:53.638Z nid_martens_sa_stream_processor INFO [logger={abc_logging_faust.app}] [^-abcLoggingFaustApp]: Wait for streams...
2022-11-24T00:04:53.778Z nid_martens_sa_stream_processor INFO [request_id={07a1090a-ce8e-4901-ba6e-6689e5837e2b} transaction_id={0b18cae0-5c96-4b1f-bc12-1179ee617ca5} logger={nid_martens_sa_stream_processor.addr_pair_refresh.agents}] End processing event KEY: 23727620090919205143. Duration: 148 ms
2022-11-24T00:09:53.645Z nid_martens_sa_stream_processor WARNING [logger={faust.transport.drivers.aiokafka}] [^--Consumer]: Warning: Task timed out!
2022-11-24T00:09:53.646Z nid_martens_sa_stream_processor WARNING [logger={faust.transport.drivers.aiokafka}] [^--Consumer]: Please make sure it's hanging before restart.
2022-11-24T00:09:53.646Z nid_martens_sa_stream_processor INFO [logger={faust.transport.drivers.aiokafka}] [^--Consumer]: [Flight Recorder-2417] (started at Thu Nov 24 00:04:53 2022) Replaying logs...
2022-11-24T00:09:53.647Z nid_martens_sa_stream_processor INFO [logger={faust.transport.drivers.aiokafka}] [^--Consumer]: [Flight Recorder-2417] (Thu Nov 24 00:04:53 2022) +consumer.commit()
2022-11-24T00:09:53.647Z nid_martens_sa_stream_processor INFO [logger={faust.transport.drivers.aiokafka}] [^--Consumer]: [Flight Recorder-2417] -End of log-
2022-11-24T00:09:53.647Z nid_martens_sa_stream_processor INFO [logger={faust.transport.drivers.aiokafka}] [^--Consumer]: [Flight Recorder-2417] Task traceback
2022-11-24T00:09:53.649Z nid_martens_sa_stream_processor INFO [logger={faust.transport.drivers.aiokafka}] [^--Consumer]: Stack for <Task pending name='Task-1692839' coro=<Service.stop() running at /opt/abc/nid-martens-sa-stream-processor/releases/20221122T140114/venv/lib64/python3.8/site-packages/mode/services.py:839> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f9708951550>()]> cb=[shield.<locals>._inner_done_callback() at /opt/rh/rh-python38/root/usr/lib64/python3.8/asyncio/tasks.py:885]> (most recent call last):

  File "/opt/abc/nid-martens-sa-stream-processor/releases/20221122T140114/venv/lib64/python3.8/site-packages/faust/transport/consumer.py", line 768, in commit_and_end_transactions
    await self.commit(start_new_transaction=False)
  File "/opt/abc/nid-martens-sa-stream-processor/releases/20221122T140114/venv/lib64/python3.8/site-packages/faust/transport/consumer.py", line 822, in commit
    return await self.force_commit(
  File "/opt/abc/nid-martens-sa-stream-processor/releases/20221122T140114/venv/lib64/python3.8/site-packages/mode/services.py", line 459, in _and_transition
    return await fun(self, *args, **kwargs)
  File "/opt/abc/nid-martens-sa-stream-processor/releases/20221122T140114/venv/lib64/python3.8/site-packages/faust/transport/consumer.py", line 857, in force_commit
    did_commit = await self._commit_tps(
  File "/opt/abc/nid-martens-sa-stream-processor/releases/20221122T140114/venv/lib64/python3.8/site-packages/faust/transport/consumer.py", line 874, in _commit_tps
    return await self._commit_offsets(
  File "/opt/abc/nid-martens-sa-stream-processor/releases/20221122T140114/venv/lib64/python3.8/site-packages/faust/transport/consumer.py", line 943, in _commit_offsets
    did_commit = await self._commit(committable_offsets)
  File "/opt/abc/nid-martens-sa-stream-processor/releases/20221122T140114/venv/lib64/python3.8/site-packages/faust/transport/consumer.py", line 1311, in _commit
    return await self._thread.commit(offsets)
  File "/opt/abc/nid-martens-sa-stream-processor/releases/20221122T140114/venv/lib64/python3.8/site-packages/faust/transport/drivers/aiokafka.py", line 523, in commit
    return await self.call_thread(self._commit, offsets)
  File "/opt/abc/nid-martens-sa-stream-processor/releases/20221122T140114/venv/lib64/python3.8/site-packages/mode/threads.py", line 436, in call_thread
    result = await promise

2022-11-24T00:29:56.573Z nid_martens_sa_stream_processor INFO [logger={faust.worker}] [^Worker]: Signal received: Signals.SIGTERM (15)
```

Any information that could help on this ?
