### ISSUE TITLE
Unregognized partition

### ISSUE THREAD

**Issue by PGDataHome** [robinhood/faust#473]
## Checklist

- [ ] I have included information about relevant versions
- [ ] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce
1. start kafka and zookeeper
2 in 1 window : faust -A mini produce
3 in another one: faust -A mini worker

[traces.err.log](https://github.com/robinhood/faust/files/3855465/traces.err.log)
[mini.py.log](https://github.com/robinhood/faust/files/3855466/mini.py.log)

the mini.py.log is actually the mini.py file (only made this rename allowing to drag/drop file

## Expected behavior

Tell us what you expected to happen.

## Actual behavior

Tell us what happened instead.

## Full traceback

`hadoop@pascal-asus:~/kafka_2.11-2.3.0$ faust -A mini worker
┌ƒaµS† v1.9.0─┬──────────────────────────────────────────────────────┐
│ id          │ analytics-mini                                       │
│ transport   │ [URL('kafka://localhost:9092')]                      │
│ store       │ memory:                                              │
│ web         │ http://localhost:6066/                               │
│ log         │ -stderr- (warn)                                      │
│ pid         │ 23066                                                │
│ hostname    │ pascal-asus                                          │
│ platform    │ CPython 3.7.3 (Linux x86_64)                         │
│        +    │ Cython (GCC 8.3.0)                                   │
│ drivers     │                                                      │
│   transport │ aiokafka=1.1.3                                       │
│   web       │ aiohttp=3.5.4                                        │
│ datadir     │ /home/hadoop/kafka_2.11-2.3.0/analytics-mini-data    │
│ appdir      │ /home/hadoop/kafka_2.11-2.3.0/analytics-mini-data/v1 │
└─────────────┴──────────────────────────────────────────────────────┘
starting➢ 😊
[2019-11-17 10:59:19,120] [23066] [WARNING] urls: type(visit) <class 'mini.PageVisit'>  type(visit.url) <class 'str'> type(visit.id) <class 'str'> http://example.com/index.html  3 
[2019-11-17 10:59:19,150] [23066] [WARNING] urls: type(visit) <class 'mini.PageVisit'>  type(visit.url) <class 'str'> type(visit.id) <class 'str'> http://example.com/subscribe.html  2 
[2019-11-17 10:59:19,153] [23066] [WARNING] urls: type(visit) <class 'mini.PageVisit'>  type(visit.url) <class 'str'> type(visit.id) <class 'str'> http://example.com/404.html  0 
[2019-11-17 10:59:19,155] [23066] [WARNING] urls: type(visit) <class 'mini.PageVisit'>  type(visit.url) <class 'str'> type(visit.id) <class 'str'> http://example.com/index.html  0 
[2019-11-17 10:59:19,157] [23066] [ERROR] [^---ProducerBuffer]: Crashed reason=AssertionError('Unrecognized partition') 
Traceback (most recent call last):
  File "/home/hadoop/.local/lib/python3.7/site-packages/mode/services.py", line 770, in _execute_task
    await task
  File "/usr/local/lib/python3.7/dist-packages/faust-1.9.0-py3.7-linux-x86_64.egg/faust/transport/producer.py", line 96, in _handle_pending
    await send_pending(msg)
  File "/usr/local/lib/python3.7/dist-packages/faust-1.9.0-py3.7-linux-x86_64.egg/faust/transport/producer.py", line 72, in _send_pending
    await fut.message.channel.publish_message(fut, wait=False)
  File "/usr/local/lib/python3.7/dist-packages/faust-1.9.0-py3.7-linux-x86_64.egg/faust/topics.py", line 416, in publish_message
    headers=headers,
  File "/usr/local/lib/python3.7/dist-packages/faust-1.9.0-py3.7-linux-x86_64.egg/faust/transport/drivers/aiokafka.py", line 780, in send
    transactional_id=transactional_id,
  File "/home/hadoop/.local/lib/python3.7/site-packages/aiokafka/producer/producer.py", line 305, in send
    key_bytes, value_bytes)
  File "/home/hadoop/.local/lib/python3.7/site-packages/aiokafka/producer/producer.py", line 233, in _partition
    'Unrecognized partition'
AssertionError: Unrecognized partition
[2019-11-17 10:59:19,199] [23066] [WARNING] urls: type(visit) <class 'mini.PageVisit'>  type(visit.url) <class 'str'> type(visit.id) <class 'str'> http://example.com/subscribe.html  3 
[2019-11-17 10:59:19,201] [23066] [WARNING] urls: type(visit) <class 'mini.PageVisit'>  type(visit.url) <class 'str'> type(visit.id) <class 'str'> http://example.com/404.html  0 
[2019-11-17 10:59:19,203] [23066] [WARNING] urls: type(visit) <class 'mini.PageVisit'>  type(visit.url) <class 'str'> type(visit.id) <class 'str'> http://example.com/index.html  2 
[2019-11-17 10:59:19,205] [23066] [WARNING] urls: type(visit) <class 'mini.PageVisit'>  type(visit.url) <class 'str'> type(visit.id) <class 'str'> http://example.com/subscribe.html  1 
[2019-11-17 10:59:19,207] [23066] [WARNING] urls: type(visit) <class 'mini.PageVisit'>  type(visit.url) <class 'str'> type(visit.id) <class 'str'> http://example.com/404.html  2 
stopping➢ [2019-11-17 10:59:19,209] [23066] [WARNING] urls: type(visit) <class 'mini.PageVisit'>  type(visit.url) <class 'str'> type(visit.id) <class 'str'> http://example.com/index.html  2 
◣[2019-11-17 10:59:19,210] [23066] [WARNING] urls: type(visit) <class 'mini.PageVisit'>  type(visit.url) <class 'str'> type(visit.id) <class 'str'> http://example.com/subscribe.html  4 
◤[2019-11-17 10:59:19,364] [23066] [ERROR] [^Worker]: Error while stopping child <App(analytics-mini): [URL('kafka://localhost:9092')] crashed agents(<AgentManager: crashed >) 0x7f45a79b5320>: AssertionError('Unrecognized partition') 
Traceback (most recent call last):
  File "/home/hadoop/.local/lib/python3.7/site-packages/mode/services.py", line 849, in _default_stop_children
    await asyncio.shield(child.stop())
  File "/home/hadoop/.local/lib/python3.7/site-packages/mode/services.py", line 828, in stop
    await self.on_stop()
  File "/usr/local/lib/python3.7/dist-packages/faust-1.9.0-py3.7-linux-x86_64.egg/faust/app/base.py", line 1448, in on_stop
    await self._producer_flush(self.log)
  File "/usr/local/lib/python3.7/dist-packages/faust-1.9.0-py3.7-linux-x86_64.egg/faust/app/base.py", line 1454, in _producer_flush
    await self._producer.flush()
  File "/usr/local/lib/python3.7/dist-packages/faust-1.9.0-py3.7-linux-x86_64.egg/faust/transport/drivers/aiokafka.py", line 806, in flush
    await self.buffer.flush()
  File "/usr/local/lib/python3.7/dist-packages/faust-1.9.0-py3.7-linux-x86_64.egg/faust/transport/producer.py", line 52, in flush
    await send_pending(msg)
  File "/usr/local/lib/python3.7/dist-packages/faust-1.9.0-py3.7-linux-x86_64.egg/faust/transport/producer.py", line 72, in _send_pending
    await fut.message.channel.publish_message(fut, wait=False)
  File "/usr/local/lib/python3.7/dist-packages/faust-1.9.0-py3.7-linux-x86_64.egg/faust/topics.py", line 416, in publish_message
    headers=headers,
  File "/usr/local/lib/python3.7/dist-packages/faust-1.9.0-py3.7-linux-x86_64.egg/faust/transport/drivers/aiokafka.py", line 780, in send
    transactional_id=transactional_id,
  File "/home/hadoop/.local/lib/python3.7/site-packages/aiokafka/producer/producer.py", line 305, in send
    key_bytes, value_bytes)
  File "/home/hadoop/.local/lib/python3.7/site-packages/aiokafka/producer/producer.py", line 233, in _partition
    'Unrecognized partition'
AssertionError: Unrecognized partition
◤[2019-11-17 10:59:21,377] [23066] [CRITICAL] [^Worker]: We experienced a crash! Reraising original exception... 
hadoop@pascal-asus:~/kafka_2.11-2.3.0$ 

```

# Versions

* Python version
* Faust version
* Operating system
* Kafka version
* RocksDB version (if applicable)

**Comment by fr-ser** [comment]
I believe I had a similar problem.
While not being a solution my issue was, that I created a windowed table with a key index. The key index topic could not be created automatically though.
After manually creating the topic in Kafka myself everything worked peachy.
Can you check if the key topic for your tables is the issue?

I think in your case the topics should be:
- `analytics-mini-urls_total-key_index-changelog`
- `analytics-mini-users_total-key_index-changelog`

**Comment by PGDataHome** [comment]
OK, thank you, now like this, it works.

Could I ask you :
- the value elems of a table can only be simple python types, or could it
be some Class objects ?
- how to avoid the extra ouptputs (the initial banner, the timing and
status in front of each line


Le lun. 18 nov. 2019 à 09:09, Sergej Herbert <notifications@github.com> a
écrit :

**Comment by SteadBytes** [comment]
I'm able to reproduce this issue when using `key_index=True` for a windowed table as well. @fr-ser 's solution of creating the index changelog topics works. I'm fairly certain the issue is  to do with the registration of the index table https://github.com/robinhood/faust/blob/a3038332f518ee422d4d99e8efb76b9c15862b92/faust/tables/wrappers.py#L337 and it not being started before the app runs. Tables registered via `app.Table` are started by the `TableManager` https://github.com/robinhood/faust/blob/a3038332f518ee422d4d99e8efb76b9c15862b92/faust/tables/manager.py#L158 - is it possible that the key index tables aren't included in this? 

As an example, this can be done using `topic.maybe_declare()`:

```python3
foo_table_index_topic = app.topic(
    'myapp-foo_table-key_index-changelog'
)
foo_table = app.Table('foo_table', default=int).hopping(
    10, 5, expires=timedelta(minutes=10), key_index=True
)

@app.agent()
async def foo_processor(foos):
    # Ensure the index topic is available before processing the windowed table
    await foo_table_index_topic.maybe_declare()
    async for foo in foos:
        foo_table[foo] += 1

@app.agent(other_topic)
async def foo_producer(stream):
    async for item in stream:
        await foo_processor.send("foo" + item)
```

**Comment by dlmiddlecote** [comment]
Hey, is there any movement on this? Would be nice to not have to define the changelog topic manually, it seems like an 'internal' detail the users shouldn't have to worry about.
