### ISSUE TITLE
Tracing error with default/no tracer set: AttributeError: 'Span' object has no attribute 'operation_name'

### ISSUE THREAD

**Issue by fr-ser** [robinhood/faust#474]
I just created an issue for the bug mentioned in this slack thread to be able to link to it and check it every now and then, since I could not find an issue already.

https://fauststream.slack.com/archives/C7FL9CB5E/p1572530324130900

## Checklist

- [x] I have included information about relevant versions
- [ ] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

I cannot give a good reproducible case (it happens for us after a while), but this slack thread above is more detailed than anything I could come up with

## Expected behavior

Continue running (and receiving messages) without errors.

## Actual behavior

Upon receiving this error now further messages are consumed from Kafka (the consumer is also not shown anymore as a Kafka consumer)

## Full traceback

```pytb
[2019-10-31 13:52:43,247] [35] [ERROR] CRASHING HARD: COORDINATION ROUTINE GOT AttributeError("'Span' object has no attribute 'operation_name'") 
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/aiokafka/consumer/group_coordinator.py", line 698, in __coordination_routine
    self.flush_spans()
  File "/usr/local/lib/python3.7/dist-packages/aiokafka/consumer/group_coordinator.py", line 774, in flush_spans
    self._flush_spans()
  File "/usr/local/lib/python3.7/dist-packages/faust/transport/drivers/aiokafka.py", line 393, in flush_spans
    self._on_span_cancelled_early(span)
  File "/usr/local/lib/python3.7/dist-packages/faust/transport/drivers/aiokafka.py", line 377, in _on_span_cancelled_early
    op_name = span.operation_name
AttributeError: 'Span' object has no attribute 'operation_name'
```

# Versions

* Python version: 3.7.4
* Faust version: 1.9.0
* Operating system: Debian Buster
* Kafka version: 2.11-2.0.1
* RocksDB version (if applicable) n/a

**Comment by fr-ser** [comment]
I tried the fix from the slack thread with the following code, but recently I seem to get a lot of the errors again :man_shrugging: 

```python
import jaeger_client


def init_jaeger_tracer(app_name):
    config = jaeger_client.Config(config={"enabled": False}, service_name=app_name,
                                  validate=True)
    return config.initialize_tracer()

...

def get_app(app_name, configuration={}):
   ...

    APP_CONFIG = {
      ...
        "tracer": init_jaeger_tracer(app_name),
    }

    app = faust.App(app_name, broker=f'kafka://{KAFKA_ADDRESS}')
    app.config_from_object({**APP_CONFIG, **configuration})
    ...
    return app
```

**Comment by jwthomp** [comment]
I am hitting the same issue:

```
[2019-12-20 15:49:42,138] [9] [ERROR] CRASHING HARD: COORDINATION ROUTINE GOT AttributeError("'Span' object has no attribute 'operation_name'")
Traceback (most recent call last):
  File "/home/granular/.cache/pypoetry/virtualenvs/gb-listeners-9TtSrW0h-py3.7/lib/python3.7/site-packages/aiokafka/consumer/group_coordinator.py", line 698, in __coordination_routine
    self.flush_spans()
  File "/home/granular/.cache/pypoetry/virtualenvs/gb-listeners-9TtSrW0h-py3.7/lib/python3.7/site-packages/aiokafka/consumer/group_coordinator.py", line 774, in flush_spans
    self._flush_spans()
  File "/home/granular/.cache/pypoetry/virtualenvs/gb-listeners-9TtSrW0h-py3.7/lib/python3.7/site-packages/faust/transport/drivers/aiokafka.py", line 393, in flush_spans
    self._on_span_cancelled_early(span)
  File "/home/granular/.cache/pypoetry/virtualenvs/gb-listeners-9TtSrW0h-py3.7/lib/python3.7/site-packages/faust/transport/drivers/aiokafka.py", line 377, in _on_span_cancelled_early
    op_name = span.operation_name
AttributeError: 'Span' object has no attribute 'operation_name'
[2019-12-20 15:54:44,653] [9] [WARNING] [^--Consumer]: Warning: Task timed out!
[2019-12-20 15:54:44,653] [9] [WARNING] [^--Consumer]: Please make sure it's hanging before restart.
[2019-12-20 15:54:44,653] [9] [INFO] [^--Consumer]: [Flight Recorder-7] (started at Fri Dec 20 15:49:44 2019) Replaying logs...
[2019-12-20 15:54:44,653] [9] [INFO] [^--Consumer]: [Flight Recorder-7] (Fri Dec 20 15:49:44 2019) +consumer.commit()
[2019-12-20 15:54:44,653] [9] [INFO] [^--Consumer]: [Flight Recorder-7] -End of log-
[2019-12-20 15:54:44,653] [9] [INFO] [^--Consumer]: [Flight Recorder-7] Task traceback
[2019-12-20 15:54:44,655] [9] [INFO] [^--Consumer]: Stack for <Task pending coro=<Service._execute_task() running at /home/granular/.cache/pypoetry/virtualenvs/gb-listeners-9TtSrW0h-py3.7/lib/python3.7/site-packages/mode/services.py:770> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f3b8c3c8cd0>()]> cb=[Service._on_future_done()]> (most recent call last):
  File "/home/granular/.cache/pypoetry/virtualenvs/gb-listeners-9TtSrW0h-py3.7/lib/python3.7/site-packages/mode/services.py", line 770, in _execute_task
    await task
  File "/home/granular/.cache/pypoetry/virtualenvs/gb-listeners-9TtSrW0h-py3.7/lib/python3.7/site-packages/faust/transport/consumer.py", line 778, in _commit_handler
    await self.commit()
  File "/home/granular/.cache/pypoetry/virtualenvs/gb-listeners-9TtSrW0h-py3.7/lib/python3.7/site-packages/faust/transport/consumer.py", line 813, in commit
    start_new_transaction=start_new_transaction,
  File "/home/granular/.cache/pypoetry/virtualenvs/gb-listeners-9TtSrW0h-py3.7/lib/python3.7/site-packages/mode/services.py", line 456, in _and_transition
    return await fun(self, *args, **kwargs)
  File "/home/granular/.cache/pypoetry/virtualenvs/gb-listeners-9TtSrW0h-py3.7/lib/python3.7/site-packages/faust/transport/consumer.py", line 847, in force_commit
    commit_tps, start_new_transaction=start_new_transaction)
  File "/home/granular/.cache/pypoetry/virtualenvs/gb-listeners-9TtSrW0h-py3.7/lib/python3.7/site-packages/faust/transport/consumer.py", line 865, in _commit_tps
    start_new_transaction=start_new_transaction)
  File "/home/granular/.cache/pypoetry/virtualenvs/gb-listeners-9TtSrW0h-py3.7/lib/python3.7/site-packages/faust/transport/consumer.py", line 932, in _commit_offsets
    did_commit = await self._commit(committable_offsets)
  File "/home/granular/.cache/pypoetry/virtualenvs/gb-listeners-9TtSrW0h-py3.7/lib/python3.7/site-packages/faust/transport/consumer.py", line 1290, in _commit
    return await self._thread.commit(offsets)
  File "/home/granular/.cache/pypoetry/virtualenvs/gb-listeners-9TtSrW0h-py3.7/lib/python3.7/site-packages/faust/transport/drivers/aiokafka.py", line 422, in commit
    return await self.call_thread(self._commit, offsets)
  File "/home/granular/.cache/pypoetry/virtualenvs/gb-listeners-9TtSrW0h-py3.7/lib/python3.7/site-packages/mode/threads.py", line 389, in call_thread
    result = await promise
```

**Comment by roynico** [comment]
I'm getting the same issue. Difficult to reproduce it precisely, but it happens "sometimes". I have basically a script processing millions of Items, and sometimes it crashes. Here is the last crash I encountered: 

> [2020-01-06 10:47:40,002] [20273] [ERROR] OffsetCommit failed for group ai-pipeline-aitest due to group error ([Error 25] UnknownMemberIdError: ai-pipeline-aitest), will rejoin 
[2020-01-06 10:47:40,304] [20273] [ERROR] CRASHING HARD: COORDINATION ROUTINE GOT AttributeError("'Span' object has no attribute 'operation_name'") 
Traceback (most recent call last):
  File "/srv/authorid/kafkadam/venv/lib/python3.7/site-packages/aiokafka/consumer/group_coordinator.py", line 698, in __coordination_routine  
    self.flush_spans()
  File "/srv/authorid/kafkadam/venv/lib/python3.7/site-packages/aiokafka/consumer/group_coordinator.py", line 774, in flush_spans             
    self._flush_spans()
  File "/srv/authorid/kafkadam/venv/lib/python3.7/site-packages/faust/transport/drivers/aiokafka.py", line 393, in flush_spans                
    self._on_span_cancelled_early(span)
  File "/srv/authorid/kafkadam/venv/lib/python3.7/site-packages/faust/transport/drivers/aiokafka.py", line 377, in _on_span_cancelled_early   
    op_name = span.operation_name
AttributeError: 'Span' object has no attribute 'operation_name'

faust==1.9.0

**Comment by bobh66** [comment]
This appears to have been fixed by https://github.com/robinhood/faust/commit/236fc235983044001e9a0ebe7196fae6527eb7de but has not been released yet

**Comment by fr-ser** [comment]
> This appears to have been fixed by [236fc23](https://github.com/robinhood/faust/commit/236fc235983044001e9a0ebe7196fae6527eb7de) but has not been released yet

This looks indeed promising. By now it should have been released with v10.3.

I haven't upgraded yet, but looking at the code I would guess this can be closed. Right @ask ?
