### ISSUE TITLE
Faust worker fails on first bootup if there are too many topics being created

### ISSUE THREAD

**Issue by DhruvaPatil98** [robinhood/faust#501]
## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

Use the code below to start
```py
from faust_mod import App

app = App(
    'app_main',
    broker='kafka://kafka:9094',
    store='rocksdb://',
)

PARTITITONS = 1

event_topic = []
event_table = []
for i in range(20):
    event_topic.append(app.topic(
        f'event_topic_write{i}',
        internal=True,
        partitions=PARTITITONS,
    ))

    event_table.append(appTable(
        f'event_table{i}',
        partitions=PARTITITONS,
    ))


@app.agent(event_topic[0])
async def event_topic_write(streams):
    async for payload in streams.events():
        print(f'Got data: {payload}')
        event_table[0][payload.key] = payload.value
        for key in event_table[0]:
            print(f'Local key: {key}, value: {event_table[0][key]}')


if __name__ == '__main__':
    app.main()
```

## Expected behavior

The worker boots up normally.

## Actual behavior

The worker doesn't complete bootup and crashes.

## Full traceback

```pytb
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 775, in _execute_task
    await task
  File "/application/faust_mod/transport/conductor.py", line 232, in _subscriber
    await self.app.consumer.subscribe(await self._update_indices())
  File "/application/faust_mod/transport/conductor.py", line 272, in _update_indices
    for channel in self._topics:
RuntimeError: Set changed size during iteration
```

# Versions

* Python version: 3.6+
* Faust version: 1.8, 1.9, master
* Operating system
* Kafka version
* RocksDB version (if applicable)

**Comment by ask** [comment]
Should be fixed in master!
