### ISSUE TITLE
Consumer thread not yet started when enable_kafka = False

### ISSUE THREAD

**Issue by joekohlsdorf** [robinhood/faust#535]
I'd like to run a Faust worker without doing anything with Kafka, for example to run timers.

## Steps to reproduce

```
import faust
from faust.app.base import BootStrategy

class App(faust.App):
    class BootStrategy(BootStrategy):
         enable_kafka = False

app = App('test')
```

## Expected behavior

App starts.

## Actual behavior

App crashes initializing the TableManager:

```
[^Worker]: Error: ConsumerNotStarted('Consumer thread not yet started') 
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/mode/worker.py", line 273, in execute_from_commandline
    self.loop.run_until_complete(self._starting_fut)
  File "/usr/local/lib/python3.8/asyncio/base_events.py", line 612, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.8/site-packages/mode/services.py", line 736, in start
    await self._default_start()
  File "/usr/local/lib/python3.8/site-packages/mode/services.py", line 743, in _default_start
    await self._actually_start()
  File "/usr/local/lib/python3.8/site-packages/mode/services.py", line 767, in _actually_start
    await child.maybe_start()
  File "/usr/local/lib/python3.8/site-packages/mode/services.py", line 795, in maybe_start
    await self.start()
  File "/usr/local/lib/python3.8/site-packages/mode/services.py", line 736, in start
    await self._default_start()
  File "/usr/local/lib/python3.8/site-packages/mode/services.py", line 743, in _default_start
    await self._actually_start()
  File "/usr/local/lib/python3.8/site-packages/mode/services.py", line 767, in _actually_start
    await child.maybe_start()
  File "/usr/local/lib/python3.8/site-packages/mode/services.py", line 795, in maybe_start
    await self.start()
  File "/usr/local/lib/python3.8/site-packages/mode/services.py", line 736, in start
    await self._default_start()
  File "/usr/local/lib/python3.8/site-packages/mode/services.py", line 743, in _default_start
    await self._actually_start()
  File "/usr/local/lib/python3.8/site-packages/mode/services.py", line 760, in _actually_start
    await self.on_start()
  File "/usr/local/lib/python3.8/site-packages/faust/tables/manager.py", line 143, in on_start
    await self._update_channels()
  File "/usr/local/lib/python3.8/site-packages/faust/tables/manager.py", line 162, in _update_channels
    tp for tp in self.app.consumer.assignment()
  File "/usr/local/lib/python3.8/site-packages/faust/transport/consumer.py", line 1292, in assignment
    return self._thread.assignment()
  File "/usr/local/lib/python3.8/site-packages/faust/transport/drivers/aiokafka.py", line 754, in assignment
    return ensure_TPset(self._ensure_consumer().assignment())
  File "/usr/local/lib/python3.8/site-packages/faust/transport/drivers/aiokafka.py", line 792, in _ensure_consumer
    raise ConsumerNotStarted('Consumer thread not yet started')
faust.exceptions.ConsumerNotStarted: Consumer thread not yet started
```

# Versions

* Python version: 3.8.1
* Faust version: 1.10.3
* Operating system: Debian Buster

**Comment by joekohlsdorf** [comment]
Got it to work overwriting the TableManager showing that the BootStrategy shouldn't start the TableManager when Kafka is disabled:

```
import faust
from faust.app.base import BootStrategy
from faust.tables import TableManager

class NullTableManager(TableManager):
    async def on_start(self) -> None:
        return

class App(faust.App):
    class BootStrategy(BootStrategy):
         enable_kafka = False

app = App('test_app', TableManager=NullTableManager)
```
