### ISSUE TITLE
Faust on windows 10: ModuleNotFoundError: No module named 'faust.agents.agent'

### ISSUE THREAD

**Issue by thomas-chauvet** [robinhood/faust#567]
Hello,

I have an issue with Faust for windows.

I am trying to run a simple code:

app.py:
```python
import faust

app = faust.App('test-example')

class Order(faust.Record, serializer='json'):
    account_id: str
    product_id: str
    amount: int
    price: float

orders_topic = app.topic('orders', value_type=Order)
orders_for_account = app.Table('order-count-by-account', default=int)

@app.agent(orders_topic)
async def faust_agent(orders):
    async for order in orders.group_by(Order.account_id):
        orders_for_account[order.account_id] += 1
        yield order
```

test.py:
```python
from tests.testing.app import app, faust_agent, Order, orders_for_account

async def test_order():
    # start and stop the agent in this block
    async with faust_agent.test_context() as agent:
        order = Order(account_id='1', product_id='2', amount=1, price=300)
        # sent order to the test agents local channel, and wait
        # the agent to process it.
        await agent.put(order)
        # at this point the agent already updated the table
        assert orders_for_account[order.account_id] == 1
        await agent.put(order)
        assert orders_for_account[order.account_id] == 2

async def run_tests():
    app.conf.store = 'memory://'   # tables must be in-memory
    await test_order()

if __name__ == '__main__':
    import asyncio
    loop = asyncio.get_event_loop()
    loop.run_until_complete(run_tests())
```

When I run the `main.py`, I have:
```text
ModuleNotFoundError: No module named 'faust.agents.agent'
```

The full traceback is:
```pytb
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "C:\Users\.env\lib\site-packages\faust\agents\__init__.py", line 2, in <module>
    from .agent import Agent, AgentFun, AgentT, SinkT, current_agent
  File "C:\Program Files\JetBrains\PyCharm Community Edition 2019.1.2\plugins\python-ce\helpers\pydev\_pydev_bundle\pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'faust.agents.agent'
```

# Versions

* Python version 3.7.7
* Faust version: 1.10.4
* Operating system: Windows 10
* Kafka version - python lib: 1.4.7

**Comment by thomas-chauvet** [comment]
Nevermind, the issue is due to McAfee antivirus which deletes every file called `agent.py`...

My only workaround is to add this file manually after the install.
