### ISSUE TITLE
Setting on_error on an agent doesn't work

### ISSUE THREAD

**Issue by jorotenev** [robinhood/faust#572]
## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce
```python
async def on_error_cb(*args, **kwargs):
    print(args, kwargs)

@app.agent(some_topic, on_error=on_error_cb)
async def my_agent(stream):
    async for event in stream:
        assert False
```
## Expected behavior

I expect that the on_error_cb to be called when an event arrives to the stream
## Actual behavior
An exception is raised on app start 
## Full traceback

```pytb

Traceback (most recent call last):
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/georgi-tenev/Projects/xxx/src/xxx/xxxx/agents.py", line 32, in <module>
    async def my_agent(stream):
  File "/Users/georgi-tenev/.local/share/virtualenvs/xxx-c5l136Cr/lib/python3.7/site-packages/faust/app/base.py", line 874, in _inner
    **kwargs)
TypeError: ABCMeta object got multiple values for keyword argument 'on_error'

Process finished with exit code 1

```

# Versions

* Python version 3.7.5
* Faust version master, 1.11, 1.9
* Operating system MacOs 10.15.3
* Kafka version 
* RocksDB version (if applicable)

**Comment by jmaroeder** [comment]
I'd love to see #574 merged! For now, a workaround is to access the hidden `_on_error` property directly, e.g., 

```python
@app.agent(some_topic)
async def my_agent(stream):
    ...

my_agent._on_error = on_error_cb
```
