### ISSUE TITLE
Models with "type" class attribute

### ISSUE THREAD

**Issue by austinnichols101** [robinhood/faust#585]
Using "type" as the name for a class attribute creates a dict instead of a nested faust model.

In the example below, **B_Record** has a **type** class attribute.  After a loads, data in **B_Record** cannot be accessed using the dot separator (e.g. `test_2.b.bar`) and results in an `AttributeError`.  

Versions of Faust prior to 1.10.0 (tested with 1.9.0) do NOT show this same behavior.

## Steps to reproduce
```
import faust
import json


class A_Record(faust.Record, serializer="json"):

    foo: int = None
    record_type: str = "record_type_a"


class B_Record(faust.Record, serializer="json"):

    bar: int = None
    record_type: str = "record_type_b"
    type: str = "type_b"


class C_Record(faust.Record, serializer="json"):

    a: A_Record = A_Record()
    b: B_Record = B_Record()


def dump(model):
    print(
        json.dumps(
            json.loads(model.dumps()),
            sort_keys=True,
            indent=4)
    )
    print("")


if __name__ == "__main__":
    print("")

    data = {
        "a": {"foo": 1},
        "b": {"bar": 2}
    }
    data = json.dumps(data)

    print("Before loads...")
    test_1 = C_Record()
    dump(test_1)

    print("After loads...")
    test_2 = test_1.loads(data)
    dump(test_2)

    print(test_2.b.bar)

app = faust.App(
    id="faust-models"
)
```

## Results
```

Before loads...
{
    "__faust": {
        "ns": "app.C_Record"
    },
    "a": {
        "__faust": {
            "ns": "app.A_Record"
        },
        "foo": null,
        "record_type": "record_type_a"
    },
    "b": {
        "__faust": {
            "ns": "app.B_Record"
        },
        "bar": null,
        "record_type": "record_type_b",
        "type": "type_b"
    }
}

After loads...
{
    "__faust": {
        "ns": "app.C_Record"
    },
    "a": {
        "__faust": {
            "ns": "app.A_Record"
        },
        "foo": 1,
        "record_type": "record_type_a"
    },
    "b": {
        "bar": 2
    }
}

Traceback (most recent call last):
  File "app.py", line 51, in <module>
    print(test_2.b.bar)
AttributeError: 'dict' object has no attribute 'bar'
```
## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Full traceback
```
Traceback (most recent call last):
  File "app.py", line 51, in <module>
    print(test_2.b.bar)
AttributeError: 'dict' object has no attribute 'bar'
```

# Versions
* Faust 1.10.4
* Python 3.3.7

**Comment by austinnichols101** [comment]
To future readers of this issue - it's helps if you RTFM as it contains the solution.
https://faust.readthedocs.io/en/latest/userguide/models.html#fields-with-the-same-name-as-a-reserved-keyword

In summary, using reserved keywords as class attribute requires an extra step of mapping an `input_name` and `output_name` to "wrap" the reserved keyword/class attribute.

Here's an example of how to "wrap" an attribute named *type*

```
class A_Record(faust.Record, serializer="json"):

    foo: int = None
    record_type: str = "record_type_a"


class B_Record(faust.Record, serializer="json"):

    bar: int = None
    record_type: str = "record_type_b"
    # type: str = "type_b"
    _type: str = StringField(required=False, default="type_b", input_name='type', output_name='type')


class C_Record(faust.Record, serializer="json"):

    a: A_Record = A_Record()
    b: B_Record = B_Record()
```
