### ISSUE TITLE
Cannot Connect to Confluent using SASL 

### ISSUE THREAD

**Issue by sariabod** [robinhood/faust#608]
## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce
Try to connect to a Confluent Kafka Instance using SASL (no authentication works perfectly)

Took test code that was running against local Confluent installation and changed the url to point to a cloud instance and enabled SASL

## Expected behavior
Sample code that ran locally should work the same against cloud instance
## Actual behavior
Get an error 
```asyncio.streams.IncompleteReadError: 3 bytes read on a total of 352518912 expected bytes```

## Full traceback

```pytb
[2020-06-08 21:58:46,426] [13287] [INFO] [^Worker]: Starting...
[2020-06-08 21:58:46,428] [13287] [INFO] [^-App]: Starting...
[2020-06-08 21:58:46,428] [13287] [INFO] [^--Monitor]: Starting...
[2020-06-08 21:58:46,428] [13287] [INFO] [^--Producer]: Starting...
[2020-06-08 21:58:46,428] [13287] [INFO] [^---ProducerBuffer]: Starting...
[2020-06-08 21:58:46,839] [13287] [ERROR] [^Worker]: Error: ConnectionError('Connection at xxxxxx.centralus.azure.confluent.cloud:9092 closed')
Traceback (most recent call last):
  File "/home/sariabod/source/faust/venv/lib/python3.7/site-packages/aiokafka/conn.py", line 336, in _on_read_task_error
    read_task.result()
  File "/home/sariabod/source/faust/venv/lib/python3.7/site-packages/aiokafka/conn.py", line 475, in _read
    resp = await reader.readexactly(size)
  File "/home/sariabod/anaconda3/lib/python3.7/asyncio/streams.py", line 677, in readexactly
    raise IncompleteReadError(incomplete, n)
asyncio.streams.IncompleteReadError: 3 bytes read on a total of 352518912 expected bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/sariabod/source/faust/venv/lib/python3.7/site-packages/mode/worker.py", line 273, in execute_from_commandline
    self.loop.run_until_complete(self._starting_fut)
  File "/home/sariabod/anaconda3/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/home/sariabod/source/faust/venv/lib/python3.7/site-packages/mode/services.py", line 736, in start
    await self._default_start()
  File "/home/sariabod/source/faust/venv/lib/python3.7/site-packages/mode/services.py", line 743, in _default_start
    await self._actually_start()
  File "/home/sariabod/source/faust/venv/lib/python3.7/site-packages/mode/services.py", line 767, in _actually_start
    await child.maybe_start()
  File "/home/sariabod/source/faust/venv/lib/python3.7/site-packages/mode/services.py", line 795, in maybe_start
    await self.start()
  File "/home/sariabod/source/faust/venv/lib/python3.7/site-packages/mode/services.py", line 736, in start
    await self._default_start()
  File "/home/sariabod/source/faust/venv/lib/python3.7/site-packages/mode/services.py", line 743, in _default_start
    await self._actually_start()
  File "/home/sariabod/source/faust/venv/lib/python3.7/site-packages/mode/services.py", line 767, in _actually_start
    await child.maybe_start()
  File "/home/sariabod/source/faust/venv/lib/python3.7/site-packages/mode/services.py", line 795, in maybe_start
    await self.start()
  File "/home/sariabod/source/faust/venv/lib/python3.7/site-packages/mode/services.py", line 736, in start
    await self._default_start()
  File "/home/sariabod/source/faust/venv/lib/python3.7/site-packages/mode/services.py", line 743, in _default_start
    await self._actually_start()
  File "/home/sariabod/source/faust/venv/lib/python3.7/site-packages/mode/services.py", line 760, in _actually_start
    await self.on_start()
  File "/home/sariabod/source/faust/venv/lib/python3.7/site-packages/faust/transport/drivers/aiokafka.py", line 1021, in on_start
    await producer.start()
  File "/home/sariabod/source/faust/venv/lib/python3.7/site-packages/aiokafka/producer/producer.py", line 178, in start
    await self.client.bootstrap()
  File "/home/sariabod/source/faust/venv/lib/python3.7/site-packages/aiokafka/client.py", line 203, in bootstrap
    version_hint=version_hint)
  File "/home/sariabod/source/faust/venv/lib/python3.7/site-packages/aiokafka/conn.py", line 90, in create_conn
    await conn.connect()
  File "/home/sariabod/source/faust/venv/lib/python3.7/site-packages/aiokafka/conn.py", line 216, in connect
    await self._do_sasl_handshake()
  File "/home/sariabod/source/faust/venv/lib/python3.7/site-packages/aiokafka/conn.py", line 245, in _do_sasl_handshake
    response = await self.send(sasl_handshake)
  File "/home/sariabod/anaconda3/lib/python3.7/asyncio/tasks.py", line 442, in wait_for
    return fut.result()
kafka.errors.ConnectionError: ConnectionError: Connection at  xxxxxxx.centralus.azure.confluent.cloud:9092 closed
[2020-06-08 21:58:46,846] [13287] [INFO] [^Worker]: Stopping...
[2020-06-08 21:58:46,847] [13287] [INFO] [^-App]: Stopping...
[2020-06-08 21:58:46,847] [13287] [INFO] [^-App]: Flush producer buffer...
[2020-06-08 21:58:46,847] [13287] [INFO] [^--TableManager]: Stopping...
[2020-06-08 21:58:46,848] [13287] [INFO] [^---Fetcher]: Stopping...
[2020-06-08 21:58:46,849] [13287] [INFO] [^---Conductor]: Stopping...
[2020-06-08 21:58:46,850] [13287] [INFO] [^--AgentManager]: Stopping...
[2020-06-08 21:58:46,850] [13287] [INFO] [^Agent: test.process_well]: Stopping...
[2020-06-08 21:58:46,851] [13287] [INFO] [^--ReplyConsumer]: Stopping...
[2020-06-08 21:58:46,851] [13287] [INFO] [^--LeaderAssignor]: Stopping...
[2020-06-08 21:58:46,852] [13287] [INFO] [^--Consumer]: Stopping...
[2020-06-08 21:58:46,853] [13287] [INFO] [^--Producer]: Stopping...
[2020-06-08 21:58:46,853] [13287] [INFO] [^---ProducerBuffer]: Stopping...
[2020-06-08 21:58:46,854] [13287] [INFO] [^--Monitor]: Stopping...
[2020-06-08 21:58:46,856] [13287] [INFO] [^Worker]: Gathering service tasks...
[2020-06-08 21:58:46,856] [13287] [INFO] [^Worker]: Gathering all futures...
[2020-06-08 21:58:47,858] [13287] [INFO] [^Worker]: Closing event loop
```

# Versions

* Python version - 3.7.4
* Faust version - v1.10.4 and v1.11.0a1
* Operating system - Ubuntu 19.10 and MacOS10.15.4
* Kafka version - 2.5 (confluent 5.5)
* RocksDB version (if applicable) - NA testing with memory

I searched a lot and cannot find any info on this error. I am using the kafka connector for this. If I use confluent connector, I do not get an error that crashes the worker, but the worker never does anything. It will perpetually say 
``` [INFO] [^---ConfluentConsumerThread]: Still waiting for assignment...```

Sample Code:
```py
import faust

broker_credentials=faust.SASLCredentials(username='xxx',password='xxx')

app = faust.App(
    "sam-test",
    broker="kafka://xxxx.centralus.azure.confluent.cloud:9092",
    value_serializer="json",
    processing_guarantee="exactly_once",
    store="memory://",
    broker_credentials=broker_credentials
)

class Sam(faust.Record):
    info: str
    count: int
    psi: int
    osi: int

sam_topic = app.topic("sam_test", value_type=Sam)

@app.agent(sam_topic)
async def process_well(sam_data):
    async for sam in sam_data:
        print(sam)
```

**Comment by sariabod** [comment]
So digging into the issue, it seems this may not be directly linked to Faust. I tried to use simple aiokafka example and was able reproduce this same error. Adding link to that issue and closing this one.
https://github.com/aio-libs/aiokafka/issues/627

**Comment by shmarts** [comment]
Hi @sariabod, did you have any success fixing this using Faust? I can get it to work with aiokafka but can't see how to apply this to setting the connection up with Faust. An example would be much appreciated if possible, been banging my head against this all day ):

**Comment by sariabod** [comment]
Hello @shmarts , I was able to connect and the app would run for a bit but then die. Of course this was almost a year and a half ago, below is how I got around the sasl issue. 

```
import faust
from aiokafka.helpers import create_ssl_context

ssl_context = create_ssl_context()
broker_credentials=faust.SASLCredentials(mechanism='PLAIN', ssl_context=ssl_context,username='USERNAME',password='PASSWORD')

app = faust.App(
    "app-name",
    broker="kafka://CONFLUENT_URL:PORT",
    value_serializer="json",
    processing_guarantee="exactly_once",
    store="memory://",
    broker_credentials=broker_credentials,
)
```

**Comment by architgupta13** [comment]
+1 for a possible fix to this issue.

Hi @sariabod, I too am stuck with the same issue. Did you try another workaround for your use case or used another library altogether, in which case which one?
