### ISSUE TITLE
AttributeError: module 'faust.worker' has no attribute 'Worker'

### ISSUE THREAD

**Issue by phoenix-mstu** [robinhood/faust#615]
I'm trying to run basic example from https://faust.readthedocs.io/en/latest/ and get the error.
I tried installing the latest faust version, but the problem still exists.

I run it on MacOS

```
> python --version
Python 3.7.7
> python -m pip show faust
Name: faust
Version: 1.11.0a1
...
> python -c "import faust.worker"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/tmp/venv/lib/python3.7/site-packages/faust/worker.py", line 19, in <module>
    from aiokafka.structs import TopicPartition
  File "/tmp/venv/lib/python3.7/site-packages/aiokafka/__init__.py", line 3, in <module>
    from .abc import ConsumerRebalanceListener
  File "/tmp/venv/lib/python3.7/site-packages/aiokafka/abc.py", line 2, in <module>
    from kafka import ConsumerRebalanceListener as BaseConsumerRebalanceListener
  File "/tmp/kafka.py", line 35, in <module>
    @app.agent(value_type=Order)
  File "/tmp/venv/lib/python3.7/site-packages/faust/app/base.py", line 862, in _inner
    agent = self.conf.Agent(
  File "/tmp/venv/lib/python3.7/site-packages/faust/app/base.py", line 1795, in conf
    self._configure()
  File "/tmp/venv/lib/python3.7/site-packages/faust/app/base.py", line 1739, in _configure
    conf = self._load_settings(silent=silent)
  File "/tmp/venv/lib/python3.7/site-packages/faust/app/base.py", line 1751, in _load_settings
    return self.Settings(appid, **self._prepare_compat_settings(conf))
  File "/tmp/venv/lib/python3.7/site-packages/faust/types/settings/base.py", line 92, in _new_init
    self._init_entrypoint(*args, **kwargs)
  File "/tmp/venv/lib/python3.7/site-packages/faust/types/settings/base.py", line 138, in _init_entrypoint
    self._init_settings(kwargs)
  File "/tmp/venv/lib/python3.7/site-packages/faust/types/settings/base.py", line 165, in _init_settings
    param.on_init_set_default(conf, provided_value)
  File "/tmp/venv/lib/python3.7/site-packages/faust/types/settings/params.py", line 429, in on_init_set_default
    self.prepare_init_default(conf, default_value))
  File "/tmp/venv/lib/python3.7/site-packages/faust/types/settings/params.py", line 465, in prepare_init_default
    return self.to_python(conf, value)
  File "/tmp/venv/lib/python3.7/site-packages/faust/types/settings/params.py", line 713, in to_python
    return cast(OT, symbol_by_name(value))
  File "/tmp/venv/lib/python3.7/site-packages/mode/utils/imports.py", line 275, in symbol_by_name
    return cast(_T, getattr(module, attribute_name))
AttributeError: module 'faust.worker' has no attribute 'Worker'
```

**Comment by wesley-tanner-zefr** [comment]
I was able to reproduce this, and it is likely an issue regarding the module search path. From the stacktrace, you appear to have a Python module named "kafka.py" in your current working directory, which likely conflicts with a module in either this library or a dependency.

**Comment by phoenix-mstu** [comment]
I spent several hours and tested almost everything but missed that. Thank you! Sorry for reporting this.
