### ISSUE TITLE
Allow accessing table data through `timedelta`

### ISSUE THREAD

**Issue by KPostOffice** [robinhood/faust#659]
## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

I created a table of consumer offsets in a windowed table so that I could replay messages using a web request to a `app.page`.  In the documentation for tables it states that you cannot alter a table outside of a stream, but I would like some way of accessing the data in the stream so that I can use it to seek the consumer offsets based on a timestamp.

## Expected behavior

Allow calls to table such as: `offset_table[(topic, p)].delta(delta_seconds)`

## Actual behavior

```
RuntimeError: Operation outside of stream iteration
```

## Full traceback

```pytb
[2020-09-24 16:59:42,632] [123382] [ERROR] Error handling request 
Traceback (most recent call last):
  File "/home/kpostlet/.local/share/virtualenvs/message_replay-Dxv_qimG/lib64/python3.6/site-packages/aiohttp/web_protocol.py", line 418, in start
    resp = await task
  File "/home/kpostlet/.local/share/virtualenvs/message_replay-Dxv_qimG/lib64/python3.6/site-packages/aiohttp/web_app.py", line 458, in _handle
    resp = await handler(request)
  File "/home/kpostlet/.local/share/virtualenvs/message_replay-Dxv_qimG/lib/python3.6/site-packages/faust/web/drivers/aiohttp.py", line 242, in _dispatch
    return await handler(request)
  File "/home/kpostlet/.local/share/virtualenvs/message_replay-Dxv_qimG/lib/python3.6/site-packages/faust/web/views.py", line 77, in __call__
    return await self.dispatch(request)
  File "/home/kpostlet/.local/share/virtualenvs/message_replay-Dxv_qimG/lib/python3.6/site-packages/faust/web/views.py", line 93, in dispatch
    response = await method(cast(Request, request), **kwargs)
  File "/home/kpostlet/kpostoffice/message_replay/consumer.py", line 46, in seek_offset
    copy[(topic.get_topic_name, p)].delta(delta_seconds)
  File "/home/kpostlet/.local/share/virtualenvs/message_replay-Dxv_qimG/lib/python3.6/site-packages/faust/tables/wrappers.py", line 237, in delta
    return table._windowed_delta(self.key, d, event or self.event)
  File "/home/kpostlet/.local/share/virtualenvs/message_replay-Dxv_qimG/lib/python3.6/site-packages/faust/tables/base.py", line 550, in _windowed_delta
    window.delta(self._relative_event(event), d)),
  File "/home/kpostlet/.local/share/virtualenvs/message_replay-Dxv_qimG/lib/python3.6/site-packages/faust/tables/base.py", line 516, in _relative_event
    raise RuntimeError('Operation outside of stream iteration')
RuntimeError: Operation outside of stream iteration
```

# Versions

* Python: 3.6.12
* Faust: 1.10.4
* OS: Fedora32
* Kafka: 5.5.1
* RocksDB: N/A

**Comment by KPostOffice** [comment]
:cry:
