### ISSUE TITLE
app.on_configured.connect doesnt work

### ISSUE THREAD

**Issue by pikhovkin** [robinhood/faust#668]
## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

I used this code

```
import os
import faust

app = faust.App('myapp')

@app.on_configured.connect
def configure(app, conf, **kwargs):
    conf.broker = os.environ.get('FAUST_BROKER')
```

## Expected behavior

Connection to FAUST_BROKER='kafka://kafka1:19092'

## Actual behavior

kafka.errors.ConnectionError: ConnectionError: Unable to bootstrap from [('localhost', 9092, <AddressFamily.AF_UNSPEC: 0>)]

## Full traceback

```pytb
[2020-10-12 16:19:31,488] [1] [ERROR] Unable connect to "localhost:9092": Multiple exceptions: [Errno 111] Connect call failed ('127.0.0.1', 9092), [Errno 99] Cannot assign requested address 
[2020-10-12 16:19:31,493] [1] [ERROR] [^Worker]: Error: ConnectionError("Unable to bootstrap from [('localhost', 9092, <AddressFamily.AF_UNSPEC: 0>)]",) 
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/mode/worker.py", line 273, in execute_from_commandline
    self.loop.run_until_complete(self._starting_fut)
  File "/usr/local/lib/python3.6/asyncio/base_events.py", line 488, in run_until_complete
    return future.result()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 736, in start
    await self._default_start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 743, in _default_start
    await self._actually_start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 767, in _actually_start
    await child.maybe_start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 795, in maybe_start
    await self.start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 736, in start
    await self._default_start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 743, in _default_start
    await self._actually_start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 767, in _actually_start
    await child.maybe_start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 795, in maybe_start
    await self.start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 736, in start
    await self._default_start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 743, in _default_start
    await self._actually_start()
  File "/usr/local/lib/python3.6/site-packages/mode/services.py", line 760, in _actually_start
    await self.on_start()
  File "/usr/local/lib/python3.6/site-packages/faust/transport/drivers/aiokafka.py", line 1021, in on_start
    await producer.start()
  File "/usr/local/lib/python3.6/site-packages/aiokafka/producer/producer.py", line 178, in start
    await self.client.bootstrap()
  File "/usr/local/lib/python3.6/site-packages/aiokafka/client.py", line 231, in bootstrap
    'Unable to bootstrap from {}'.format(self.hosts))
kafka.errors.ConnectionError: ConnectionError: Unable to bootstrap from [('localhost', 9092, <AddressFamily.AF_UNSPEC: 0>)]
```

# Versions

* Python version 3.6
* Faust version 1.10.4
* Operating system Ubuntu
* Kafka version https://hub.docker.com/layers/confluentinc/cp-kafka/5.5.1
* RocksDB version (if applicable) not used

**Comment by kenluck2001** [comment]
I am a newbie though, but it look like a configuration issue. Kafka is trying to connect to 'kafka://kafka1:19092' which is the address of your broker, but you provided http://localhost:9092
Use a template from the official documentation / examples as a basis for your project.

**Comment by pikhovkin** [comment]
@kenluck2001  find `http://localhost:9092` in `kafka://kafka1:19092`

**Comment by marcosschroh** [comment]
@pikhovkin nice that you found the reason. Can we close the issue?

**Comment by pikhovkin** [comment]
@marcosschroh what are you speaking about? Reason doesnt found! The error somewhere inside the Faust.

**Comment by marcosschroh** [comment]
Based on your comment:

> @kenluck2001 find `http://localhost:9092` in `kafka://kafka1:19092`

I thought that you figured out what is the problem that you are facing.

Your issue is not a bug in `faust`, the problem is that you are setting the wrong `brokers url` . I have a working example using `@app.on_configured.connect`. Please, use the correct kafka url.

**Comment by pikhovkin** [comment]
This code works
```
import os
import faust

app = faust.App('myapp', broker=os.environ.get('FAUST_BROKER'))
```
but if it replace with 
```
import os
import faust

app = faust.App('myapp')

@app.on_configured.connect
def configure(app, conf, **kwargs):
    conf.broker = os.environ.get('FAUST_BROKER')
```
then it doesnt work.

The error (about `http://localhost:9092`) occurs even when `FAUST_BROKER = 'kafka://kafka2:19093;kafka3:19094'` (where kafka2 and kafka3 are inner IPs of docker).

**Comment by kenluck2001** [comment]
Try to run your example outside a docker environment. If it is working on your default network configuration on your system, then you can proceed to run in docker. You seem to have multiple layers of indirection, because it could also a network issue inside your docker configuration too. `FAUST_BROKER` is an environment variable, so if you write `echo $FAUST_BROKER` on your Linux shell then you should get `FAUST_BROKER = 'kafka://kafka2:19093;kafka3:19094'` or whatever you have provided.

**Comment by pikhovkin** [comment]
For code
```
import os
import faust

app = faust.App('myapp')

@app.on_configured.connect
def configure(app, conf, **kwargs):
    conf.broker = 'kafka://kafka2:19093;kafka3:9094'
```
is log

```
faust_1      | +ƒaµS† v1.10.4+------------------------------------------+
faust_1      | | id          | kafka_to_db                              |
faust_1      | | transport   | [URL('kafka://localhost:9092')]          |
faust_1      | | store       | memory:                                  |
faust_1      | | web         | http://localhost:6066/                   |
faust_1      | | log         | -stderr- (warn)                          |
```

For code
```
import os
import faust

app = faust.App('myapp', broker='kafka://kafka2:19093;kafka3:9094')
```

is log

```
faust_1      | +ƒaµS† v1.10.4+-------------------------------------------------------------+
faust_1      | | id          | kafka_to_db                                                 |
faust_1      | | transport   | [URL('kafka://kafka2:19093'), URL('kafka://kafka3:19094')]  |
faust_1      | | store       | memory:                                                     |
faust_1      | | web         | http://localhost:6066/                                      |
faust_1      | | log         | -stderr- (warn)                                             |
```

**Comment by ei-grad** [comment]
I'm facing the same issue. Faust doesn't even call the configure function. Trying to find minimal reproducible example.

**Comment by ei-grad** [comment]
Probably there should be a warning if `app.on_configured.connect` is called after the `on_configured` already fired.
