### ISSUE TITLE
Using compiled proto in schema not working

### ISSUE THREAD

**Issue by Locustv2** [robinhood/faust#683]
## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce
https://faust.readthedocs.io/en/latest/userguide/models.html#schemas
I am trying to use compiled protobuf classes to deserialize the data when reading the events as follows:

```py
import faust
from proto.topic_pb2 import topic


app = faust.App(
    'faust-consumer',
    broker='kafka://',
    store="memory://",
    cache="memory://",
)

schema = faust.Schema(
    key_type=topic.PK,
    value_type=topic,
    key_serializer="raw",
    value_serializer="raw",
)

topic = app.topic(
    'topic',
    schema=schema
)


@app.agent(topic)
async def consume(topic):
    async for event in topic:
        print(event)


if __name__ == "__main__":
    app.main()
```

## Expected behavior

I would expect to read deserialized messages from the topic

## Actual behavior

I am getting the following error:

```pytb
[^----Agent*: __main__.consume]: Crashed reason=KeyDecodeError('from_data')
Traceback (most recent call last):
  File "/app/.venv/lib/python3.8/site-packages/faust/serializers/registry.py", line 56, in loads_key
    return cast(K, self._prepare_payload(typ, payload))
  File "/app/.venv/lib/python3.8/site-packages/faust/serializers/registry.py", line 123, in _prepare_payload
    return model.from_data(value, preferred_type=model)
AttributeError: from_data

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/app/.venv/lib/python3.8/site-packages/faust/agents/agent.py", line 647, in _execute_actor
    await coro
  File "src/app.py", line 43, in consume
    async for event in topic:
  File "/app/.venv/lib/python3.8/site-packages/faust/streams.py", line 860, in _py_aiter
    raise chan_errors.popleft()
  File "/app/.venv/lib/python3.8/site-packages/faust/transport/conductor.py", line 95, in on_message
    event = await chan.decode(message, propagate=True)
  File "/app/.venv/lib/python3.8/site-packages/faust/serializers/schemas.py", line 137, in decode
    k: K = schema_loads_key(app, message, loads=loads_key)
  File "/app/.venv/lib/python3.8/site-packages/faust/serializers/schemas.py", line 73, in loads_key
    return cast(KT, loads(
File "/app/.venv/lib/python3.8/site-packages/faust/serializers/registry.py", line 60, in loads_key
    raise KeyDecodeError(str(exc)).with_traceback(
  File "/app/.venv/lib/python3.8/site-packages/faust/serializers/registry.py", line 56, in loads_key
    return cast(K, self._prepare_payload(typ, payload))
  File "/app/.venv/lib/python3.8/site-packages/faust/serializers/registry.py", line 123, in _prepare_payload
    return model.from_data(value, preferred_type=model)
faust.exceptions.KeyDecodeError: from_data
```
# Versions

* Python version: 3.8
* Faust version: 1.10.4
* Operating system: Mac
* Kafka version
* RocksDB version (if applicable)

**Comment by guilatrova** [comment]
I'm facing the same issue.

**Comment by hemantkashniyal** [comment]
Here's an implementation of faust with Protobuf https://github.com/hemantkashniyal/faust-protobuf

**Comment by Locustv2** [comment]
We also came to a similar solution that @hemantkashniyal posted.
Extend the codec and adapt based on your protobuf requirements.
