### ISSUE TITLE
NotImplementedError when using matplotlib/Pillow inside agent code

### ISSUE THREAD

**Issue by cjh1** [robinhood/faust#731]
## Checklist

- [x] I have included information about relevant versions
- [x] I have verified that the issue persists when using the `master` branch of Faust.

## Steps to reproduce

Use matplotlib/Pillow inside faust, something like:

```
plt.imsave(path, img)
```

## Expected behavior

Writes out the image.

## Actual behavior

A `NotImplementedError` is throw from the `mode` package. It appears that `sys.stdout` is being set to an instance of [FileLogProxy](https://github.com/ask/mode/blob/master/mode/utils/logging.py#L823) and `Pillow` is doing a comparison with `sys.stdout.buffer` [here](https://github.com/python-pillow/Pillow/blob/master/src/PIL/ImageFile.py#L497) and `FileLogProxy` doesn't implement this property. Not sure where a fix should be applied.

## Full traceback

```pytb
Traceback (most recent call last):
  File "/home/XXX/.virtualenvs/4ddist/lib/python3.8/site-packages/faust/agents/agent.py", line 647, in _execute_actor
    await coro
  File "/home/XXX/work/source/still/backend/faust/worker.py", line 63, in watch_for_haadf_events
    image_path = await generate_image(tmp, path, scan_id)
  File "/home/XXX/work/source/still/backend/faust/worker.py", line 38, in generate_haadf_image
    plt.imsave(str(path), img)
  File "/home/XXX/.virtualenvs/4ddist/lib/python3.8/site-packages/matplotlib/pyplot.py", line 2412, in imsave
    return matplotlib.image.imsave(fname, arr, **kwargs)
  File "/home/XXX/.virtualenvs/4ddist/lib/python3.8/site-packages/matplotlib/image.py", line 1616, in imsave
    image.save(fname, **pil_kwargs)
  File "/home/XXX/.virtualenvs/4ddist/lib/python3.8/site-packages/PIL/Image.py", line 2235, in save
    save_handler(self, fp, filename)
  File "/home/XXX/.virtualenvs/4ddist/lib/python3.8/site-packages/PIL/PngImagePlugin.py", line 1349, in _save
    ImageFile._save(im, _idat(fp, chunk), [("zip", (0, 0) + im.size, 0, rawmode)])
  File "/home/XXX/.virtualenvs/4ddist/lib/python3.8/site-packages/PIL/ImageFile.py", line 497, in _save
    stdout = fp == sys.stdout or fp == sys.stdout.buffer
  File "/home/XXX/.virtualenvs/4ddist/lib/python3.8/site-packages/mode/utils/logging.py", line 849, in buffer
    raise NotImplementedError()
NotImplementedError

```

# Versions

* Python version: 3.8.10
* Faust version: 1.10.4
* Operating system: Linux
* Kafka version: latest

**Comment by FR4NKESTI3N** [comment]
@cjh1 Did you find a solution for this issue?
